### ISSUE TITLE
Error while configuring postgresql-instead-of-hypersonic (Deploy-Natively-11)

### ISSUE THREAD

**Issue by dineshr93** [eclipse/sw360#1019]
Deploying sw360 11 in Fresh instance with OS: ubuntu 18.04 LTS and with RAM 32g

sw360 commit: C27a46075912c1fd82bc7b0cbf3ef84ffd676960    or  **sw360-11.0.0-M1-37-gc27a4607**

Following the wiki [Deploy-Natively-11](https://github.com/eclipse/sw360/wiki/Deploy-Natively-11)

May I have more details for the step  [Deploy-Natively-11#postgresql-instead-of-hypersonic](https://github.com/eclipse/sw360/wiki/Deploy-Natively-11#postgresql-instead-of-hypersonic)

Cause I dont know  how to do it.. and when I start the tomcat & access the portal at `http://localhost:8443` The portal is not up
So I tried `http://localhost:8080` I find the below portal asking to config.. I am not sure how to configure or whats default user & password or how to create one.. I get the below error in screen because of it

![image](https://user-images.githubusercontent.com/4498415/96079804-f78cc780-0eb5-11eb-9ff9-6bce5969b51e.png)

**Comment by mcjaeger** [comment]
Please understand that this is an issue for lIferay not SW360. Please also consider for such general question that search engines can be a good way to find a solution. For example:

https://another-software-development-blog.blogspot.com/2016/11/liferay-with-different-database.html

http://roufid.com/setup-liferay-postgresql-database/

http://roufid.com/liferay-database-configuration/

https://stackoverflow.com/questions/28916406/liferay-using-postgresql

As an alternative, you can looks up how to configure prerequisites for sw360 in the sw360vagrant project, for example:

https://github.com/sw360/sw360vagrant/blob/master/shared/scripts/liferay-install.sh

https://github.com/sw360/sw360vagrant/blob/02693923d1ee6c6e51d2d2bf097761ea481b912a/puppet/manifests/sw360-single.pp#L56

https://github.com/sw360/sw360vagrant/blob/02693923d1ee6c6e51d2d2bf097761ea481b912a/puppet/modules/sw360/templates/liferay_portal-ext.properties.erb#L82
