### ISSUE TITLE
Reporting: Get statistics on the (main) license per component/release

### ISSUE THREAD

**Issue by maierthomas** [eclipse/sw360#105]
<a href="https://github.com/tngraf"><img src="https://avatars1.githubusercontent.com/u/1225388?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [tngraf](https://github.com/tngraf)**
_Monday Feb 13, 2017 at 09:38 GMT_
_Originally opened as https://github.com/sw360/sw360portal/issues/333_

----

**Comment by maierthomas** [comment]
<a href="https://github.com/mcjaeger"><img src="https://avatars1.githubusercontent.com/u/3418977?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [mcjaeger](https://github.com/mcjaeger)**
_Thursday Feb 16, 2017 at 16:30 GMT_

----

@tngraf as for #332 please provide suggestions where and how this should be displayed. major question would be if that is displayed right at the components list view or in a separate view that allows for aggregation

**Comment by maierthomas** [comment]
<a href="https://github.com/tngraf"><img src="https://avatars1.githubusercontent.com/u/1225388?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [tngraf](https://github.com/tngraf)**
_Wednesday Mar 08, 2017 at 09:38 GMT_

----

I like to propose the following steps:
1. It must be possible to retrieve this information via the REST API.
2. I create a tool that uses the REST API got get the information, allows filtering and the creation of charts.
3. When we can successfully us the tool, then we think about a UI for SW360.

**Comment by mcjaeger** [comment]
@tngraf I think this is done, right?

**Comment by tngraf** [comment]
agreed, this is done
