### ISSUE TITLE
Feature to link file list with the corresponding licenses 

### ISSUE THREAD

**Issue by arunazhakesan** [eclipse/sw360#1052]
**Present**

In the SW360, there is now provision to view the `file list` associated with each licenses. 

**Proposal**

To add a new `button` / `hyperlink` along with the `licenses` displayed in the `Main License` &  the proposed ` Other License` field. This will enable the user to view the `files` associated with each `licenses` from the UI itself without the need of downloading the reports.

_(Lets discuss on where to add this new feature in the UI)_

**Comment by mcjaeger** [comment]
maybe to add: this serves the use case to check if the dlivery contains files under a particular license
