### ISSUE TITLE
This portlet could not be found.

### ISSUE THREAD

**Issue by keinblue** [eclipse/sw360#1065]
I deployed version 7.3.3 using Vagrant.
The following message is displayed for all portlets.
The result is the same after a few tries again.
I'm looking for someone to help me.

"This portlet could not be found. Please redeploy it or remove it from the page."

VirtualBox 5.2.42_Ubuntur137960
Vagrant 2.2.14
Ubuntu 18.04.5 LTS \n \l

![Screenshot from 2020-12-08 17-20-20](https://user-images.githubusercontent.com/30192477/101460050-6a796280-397c-11eb-9885-5623c4bf887c.png)
![Screenshot from 2020-12-08 17-20-41](https://user-images.githubusercontent.com/30192477/101460069-6fd6ad00-397c-11eb-8599-b4ee3f92ce27.png)
![Screenshot from 2020-12-08 17-21-27](https://user-images.githubusercontent.com/30192477/101460084-72390700-397c-11eb-89f0-3564851cdf94.png)

**Comment by mcjaeger** [comment]
I am sorry,. I think tgere is a bug in vagrant. Please allow us a day or so to fix it. It was also reported in the slack

**Comment by keinblue** [comment]
It was a version issue of the download package.
Thanks for any help.

https://github.com/eclipse/sw360/wiki/Deploy-Natively-11#install-prerequisites
