### ISSUE TITLE
About the function to automatically sort "Additional Data"

### ISSUE THREAD

**Issue by chanrai** [eclipse/sw360#1096]
Like the attached screen capture(Release_AdditonalData_1.jpg), when registering the contents in "Additional Data" in "Release" of SW360, they are registered in order like a, b, c, d. But If you change some variable names, the registration order will change without permission (Release_AdditonalData_2.jpg). It doesn't seem to be in alphabetical order, it seems to sorts automatically with some rules.

Could you tell me which rule is used for automatic sorting? Also, please tell me if there is a method to register "Additional Data" in the order of registration without sorting.

Best regards

![Release_AdditonalData_1](https://user-images.githubusercontent.com/35596645/105648173-6d5cf200-5eed-11eb-8037-05002fbe13a5.jpg)
Release_AdditonalData_1.jpg

![Release_AdditonalData_2](https://user-images.githubusercontent.com/35596645/105648176-72ba3c80-5eed-11eb-95a5-549b270ae26a.jpg)
Release_AdditonalData_2.jpg

**Comment by mcjaeger** [comment]
I am not aware of any sorting mechanism in sw360 for this. I am also not aware of any particular sort conventions or functionality for key value structure or dictionaries in most programming environments. I think it is OK to add one if the order is important.

**Comment by mcjaeger** [comment]
that said, is it important to add sorting?

**Comment by chanrai** [comment]
>is it important to add sorting?

That's right. Currently, a lot of information is committed in "Additional Data", but the information of the same classification is displayed separately and it is very difficult to see. 

We want to display in the order of commit even if I can't sort.

**Comment by KoukiHama** [comment]
Rather than sorting, it may be more important to be able to freely set the display order when using the API.

**Comment by KoukiHama** [comment]
Solved by #1297
