### ISSUE TITLE
Also add notice texts to the disclosure document

### ISSUE THREAD

**Issue by maierthomas** [eclipse/sw360#110]
<a href="https://github.com/maxhbr"><img src="https://avatars3.githubusercontent.com/u/1187050?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [maxhbr](https://github.com/maxhbr)**
_Saturday May 13, 2017 at 06:55 GMT_
_Originally opened as https://github.com/sw360/sw360portal/issues/400_

----

Besides Copyright and License information, there are also `<spdx:noticeText>`-tags in the SPDX document which contain strings like
```
[...]
                        <spdx:noticeText>Apache Commons Lang
Copyright 2001-2011 The Apache Software Foundation

This product includes software developed by
The Apache Software Foundation (http://www.apache.org/).

This product includes software from the Spring Framework,
under the Apache License 2.0 (see: StringUtils.containsWhitespace())</spdx:noticeText>
[...]
```
(taken from the `SPDXRdfExample-v2.0.rdf`).

We are currently not using this to the disclosure document generation, but it might be necessary.  Right?

**Comment by maierthomas** [comment]
<a href="https://github.com/mcjaeger"><img src="https://avatars1.githubusercontent.com/u/3418977?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [mcjaeger](https://github.com/mcjaeger)**
_Monday May 15, 2017 at 15:36 GMT_

----

allright! Maybe the notice text is even not generated by fossology. that would be a super good improvement

**Comment by maierthomas** [comment]
<a href="https://github.com/maxhbr"><img src="https://avatars3.githubusercontent.com/u/1187050?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [maxhbr](https://github.com/maxhbr)**
_Monday May 15, 2017 at 15:38 GMT_

----

where in the disclosure document should the noticeTexts be placed?

**Comment by maierthomas** [comment]
<a href="https://github.com/mcjaeger"><img src="https://avatars1.githubusercontent.com/u/3418977?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [mcjaeger](https://github.com/mcjaeger)**
_Monday Jun 12, 2017 at 16:00 GMT_

----

there is already some place for this?

for example:

https://github.com/sw360/sw360portal/blob/master/backend/src/src-licenseinfo/src/main/resources/licenseInfoFile.vm

here:

```
....
Acknowledgements

#foreach($compName in $acknowledgements.keySet())
$compName

#set($acks = $acknowledgements.get($compName))
#foreach($ack in ${acks}   )
$ack##[[License Acknowledgement Of the Open Source Component#1]]

#end
#end
....
```

**Comment by mcjaeger** [comment]
I think so too...

so there is the new notice text template, which can be in 1) `WEB-INF/classes of the war file or 2) in `/etc/sw360``. And users can paste in their own notice texts.
