### ISSUE TITLE
Clean Up CSS Files And Their Usage

### ISSUE THREAD

**Issue by maierthomas** [eclipse/sw360#111]
<a href="https://github.com/alexbrdn"><img src="https://avatars0.githubusercontent.com/u/16780167?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [alexbrdn](https://github.com/alexbrdn)**
_Wednesday May 17, 2017 at 08:36 GMT_
_Originally opened as https://github.com/sw360/sw360portal/issues/408_

----

- We should import css files at one place only: `liferay-portlet.xml` and in the correct order.
- main.css should be merged with sw360.css and deleted.

**Comment by mcjaeger** [comment]
see also https://github.com/eclipse/sw360/issues/187

**Comment by lepokle** [comment]
@mcjaeger 
Can be closed from my point of view.

**Comment by mcjaeger** [comment]
agree
