### ISSUE TITLE
Not be able to operate the Obligation information by API

### ISSUE THREAD

**Issue by chanrai** [eclipse/sw360#1126]
Obligation information cannot be read and write by the API. 

Do you plan to implement it?

Best regards

**Comment by mcjaeger** [comment]
not so far, any plan heard. The main point is that the obligations are mybe rather static, so automation is maybe not a big pain to edit these. @chanrai what is the use case you have had in mind?

**Comment by KoukiHama** [comment]
When user migrate license data with obligation to new instance, api which manipulate obligation  is helpful.

**Comment by KoukiHama** [comment]
This issue was solved by  #1266
