### ISSUE TITLE
ORT integration: project is created every time ORT runs, even if the project has been created one run before

### ISSUE THREAD

**Issue by mcjaeger** [eclipse/sw360#1134]
it is in the project creation method to check for an existing project entry.

happens supposedly here: https://github.com/oss-review-toolkit/ort/blob/6e5dbfc828d4b5e4fbaea4865e716235b0244955/cli/src/main/kotlin/commands/UploadResultToSw360Command.kt#L105

**Comment by sschuberth** [comment]
@bs-ondem can you maybe have a look at this?

**Comment by bs-ondem** [comment]
The function in `orElse` is always evaluated regardless if Optional is present, I just replaced `orElse` with `orElseGet`.

PR https://github.com/oss-review-toolkit/ort/pull/3721

**Comment by sschuberth** [comment]
The ORT PR was merged, so this has been fixed upstream already.

**Comment by neubs-bsi** [comment]
Since this issue has been fixed upstream, this issue here can be closed.
