### ISSUE TITLE
Additional Check box to filter the My Projects in Homepage based on Project clearing state

### ISSUE THREAD

**Issue by ravi110336** [eclipse/sw360#1136]
Add 3 additional Check Box for project clearing state in the My Projects Dropdown to filter the projects based on the user selection in the UI.

My Projects has currently below filter check boxes based on the Role:
Creator
Moderator
Contributor
Project Owner
Lead Architect
Project Responsible
Security Responsible

Additional Filter based on the project clearing state:
Open
Closed 
In Progress

**Comment by mcjaeger** [comment]
looks good:

<img width="444" alt="Screenshot 2021-03-31 at 21 48 24" src="https://user-images.githubusercontent.com/3418977/113202271-d739a500-926a-11eb-875a-c0e7c593c3a4.png">
