### ISSUE TITLE
SW360 can't get license ( include "+", such as, GPL-2.0+ ) info from SPDX which made by fossology with SPDX compatible "Yes"

### ISSUE THREAD

**Issue by KoukiHama** [eclipse/sw360#1153]
[//]: # (Copyright Siemens AG, 2021. Part of the SW360 Portal Project)
[//]: # (This program and the accompanying materials are made)
[//]: # (available under the terms of the Eclipse Public License 2.0)
[//]: # (which is available at https://www.eclipse.org/legal/epl-2.0/)
[//]: # (SPDX-License-Identifier: EPL-2.0)

### Description

_Originally posted by @tienlee in https://github.com/eclipse/sw360/issues/1129#issuecomment-797203856_
This is different from #1129 
( This issue is not effect to other SPDX attachments)

#### How to reproduce

Attached & Import
https://github.com/eclipse/sw360/files/6120408/SPDX2_drivers.zip_1567589134-spdx.zip

#### Screenshots

![image](https://user-images.githubusercontent.com/39894802/111951505-1b200200-8b27-11eb-912d-d55ab1ff1483.png)

### Versions

* Last commit id on master: Version: 13.1.0-SNAPSHOT | Branch: master (ce69b3b)
* Operating System (lsb_release -a):

### Logs

Any logs (if any) generated in

#### SW360 logs

Logs generated under /var/log/sw360/sw360.log

#### Tomcat logs

Logs generated under /var/log/tomcat/error.log

**Comment by mcjaeger** [comment]
merged: https://github.com/eclipse/sw360/pull/1138

@KoukiHama would the issue be Ok?

**Comment by KoukiHama** [comment]
After merged #1138 , it seems that this issues is fix
 @tienlee what do you think? Do you know any other err cases?

**Comment by tienlee** [comment]
Hello Michael, Hama-san,

Yes, it's. After merging #1138 , this issue was fixed. It also works with some my sample SPDX files. Thank you.

**Comment by KoukiHama** [comment]
OK.I close it.
