### ISSUE TITLE
 Restrict visibility of each component/release like Project

### ISSUE THREAD

**Issue by KoukiHama** [eclipse/sw360#1155]
[//]: # (Copyright Siemens AG, 2021. Part of the SW360 Portal Project)
[//]: # (This program and the accompanying materials are made)
[//]: # (available under the terms of the Eclipse Public License 2.0)
[//]: # (which is available at https://www.eclipse.org/legal/epl-2.0/)
[//]: # (SPDX-License-Identifier: EPL-2.0)

### Description

 Set visibility like project to component/release.

[ Comments from Slack](https://sw360chat.slack.com/archives/C68C2RYS3/p1604509612026900?thread_ts=1604495620.023400&cid=C68C2RYS3)
>  it could be added maybe in the sme way as it works for projects. Actually, we have discussed to make the Components/Releases/Vendor info over REST API even without authentication ... （

Similar to #120 

#### Steps followed and expected result

Describe the steps followed by you and your expected results after following the steps.

**Comment by mcjaeger** [comment]
how about having it `everyone` by default and allow users to set it to secret.

Keep in mind that similar to subproject, visibility issues will occur, if a user has access to some super-element, but not visibility of a linked element further down the tree.

**Comment by KoukiHama** [comment]
Now I have an image how to restrict licenses.

At first getting release data as usual, then frontend program restricted visibility.



![ComponentView_20210609_1](https://user-images.githubusercontent.com/39894802/122894579-48788800-d382-11eb-9a7a-23643aab0d5c.png)
