### ISSUE TITLE
Spreadsheet export with subprojects for a project

### ISSUE THREAD

**Issue by maierthomas** [eclipse/sw360#116]
<a href="https://github.com/mcjaeger"><img src="https://avatars1.githubusercontent.com/u/3418977?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [mcjaeger](https://github.com/mcjaeger)**
_Thursday Jun 08, 2017 at 13:21 GMT_
_Originally opened as https://github.com/sw360/sw360portal/issues/435_

----

Currently we have:

1. Spreadsheet export for projects with releases on project listing page -> no sub-project relation information. 

Solution could be to have a row for each release in the hierarchy (see list "linked Projects and Releases" fully unfolded) in the exported spreadsheet and one additonal column with the path of the subproject hierarchy from where the release comes in.

Then an addtional menue item "Projects with linked releases including subprojects" lets the user select this third export option.

* Spreadsheet export of sub-view "clearing status" of involved releases -> no information about which releases belong to which project / sub-project 

Here the additonal column with the path origin could be also added with a column.

See #335 could be same solution

**Comment by maierthomas** [comment]
<a href="https://github.com/mcjaeger"><img src="https://avatars1.githubusercontent.com/u/3418977?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [mcjaeger](https://github.com/mcjaeger)**
_Wednesday Aug 16, 2017 at 14:40 GMT_

----

duplicate of #335

**Comment by maierthomas** [comment]
<a href="https://github.com/imaykay"><img src="https://avatars2.githubusercontent.com/u/27430165?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [imaykay](https://github.com/imaykay)**
_Tuesday Aug 22, 2017 at 14:50 GMT_

----

Hi @mcjaeger - I know we spent some time last week discussing this issue, but once I started working on it further questions arose:

1. Is it correct that the new export should be implemented for a single project and not for the project list?
2. In the single project view, the tab "Linked Releases And Projects" is the one where the new export should be added?
3. An export from this tab in the variant "Projects with linked releases" today already contains all subprojects - at least on my current branch which is basically the same as current master regarding exports. Is that also the case on your stage and production machines or has something changed in the meantime on master?
4. Compared to my current branch there would not be any new rows added to the new export but instead only a new column near the project name where the project hierarchy would be shown (the issue sounded to me as if a lot of new rows would be necessary to fulfill the requested feature) - is that correct?

All available colleagues were also a bit lost regarding those questions so I have to get back to you...

**Comment by maierthomas** [comment]
<a href="https://github.com/mcjaeger"><img src="https://avatars1.githubusercontent.com/u/3418977?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [mcjaeger](https://github.com/mcjaeger)**
_Friday Aug 25, 2017 at 12:53 GMT_

----

hi, for 
1: should be both
2: better would be both, but it was missing in the clearing status
3: if it is there this way, it is OK like that
4: yes, only new column is also my understanding

**Comment by mcjaeger** [comment]
(from discussion) reviewed it and it looks like
* project origin is there when generating from "clearing Status"
* releases are ther when generating from "Linked Releases and Projects" and selecting "with releases"
