### ISSUE TITLE
Display link to license generates wrong url [Liferay 7.3]

### ISSUE THREAD

**Issue by KoukiHama** [eclipse/sw360#1164]
[//]: # (Copyright Siemens AG, 2021. Part of the SW360 Portal Project)
[//]: # (This program and the accompanying materials are made)
[//]: # (available under the terms of the Eclipse Public License 2.0)
[//]: # (which is available at https://www.eclipse.org/legal/epl-2.0/)
[//]: # (SPDX-License-Identifier: EPL-2.0)

### Description

#635  is closed but latest sw360 still have same issue.
(Solution is also written in #635)
Sw360 admin need to change friendly URL setting whenever they make sw360 instance.
So modifying  root causes is good for them.
(Re-making lar file is required?)

#### How to reproduce

Clicking on Main Licenses hyperlink in Components tab opens Not Found page.
example: AGPL-3.0.

#### Screenshots

**license1** is in friendly url. We should remove 1.

![license1_issue](https://user-images.githubusercontent.com/39894802/112600837-06a87600-8e55-11eb-854f-742af12b7223.png)

Clicking on Main Licenses hyperlink in Components tab opens Not Found page.
example: AGPL-3.0.

![license1_issue1](https://user-images.githubusercontent.com/39894802/112601262-964e2480-8e55-11eb-9b7c-a4251fee67a7.png)

### Versions

* Last commit id on master: Version: 13.1.0-SNAPSHOT | Branch: master (ce69b3b)
* Operating System (lsb_release -a):

### Logs

Any logs (if any) generated in

#### SW360 logs

Logs generated under /var/log/sw360/sw360.log

#### Tomcat logs

Logs generated under /var/log/tomcat/error.log

**Comment by mcjaeger** [comment]
seems to be related with: https://github.com/eclipse/sw360/issues/1130

**Comment by KoukiHama** [comment]
And related #872 too.
