### ISSUE TITLE
UI: Feature to copy the document id in Project/Component/Release details page

### ISSUE THREAD

**Issue by akapti** [eclipse/sw360#1165]
[//]: # (Copyright Siemens AG, 2021. Part of the SW360 Portal Project)
[//]: # (This program and the accompanying materials are made)
[//]: # (available under the terms of the Eclipse Public License 2.0)
[//]: # (which is available at https://www.eclipse.org/legal/epl-2.0/)
[//]: # (SPDX-License-Identifier: EPL-2.0)

### Description
Please describe your situation in few words here:

- Add an button/icon to copy (clipboard) the project/component/release id from details page.
- User should be able to copy the document id to clipboard by clicking on icon/button

**Comment by mcjaeger** [comment]
it is about this here at some data -> not only ids but also REST tokens for example:

<img width="433" alt="Screenshot 2021-03-31 at 21 54 41" src="https://user-images.githubusercontent.com/3418977/113203057-d35a5280-926b-11eb-9c4d-d2a175aa6848.png">

**Comment by akapti** [comment]
Closing the issue, as PR https://github.com/eclipse/sw360/pull/1168 is already merged.
