### ISSUE TITLE
Manage info about "FSF Free/Libre" and "OSI Approved" in each license pages.   

### ISSUE THREAD

**Issue by KoukiHama** [eclipse/sw360#1166]
[//]: # (Copyright Siemens AG, 2021. Part of the SW360 Portal Project)
[//]: # (This program and the accompanying materials are made)
[//]: # (available under the terms of the Eclipse Public License 2.0)
[//]: # (which is available at https://www.eclipse.org/legal/epl-2.0/)
[//]: # (SPDX-License-Identifier: EPL-2.0)

### Description

Like [SPDX License Page](https://spdx.org/licenses/), adding colums of  "FSF Free/Libre?" and "OSI Approved?", to license pages

#### Steps followed and expected result

Add "Yes/No"  in license each page like GPL compatible.
Hopefully, admin user import these info from spdx page like other spdx info. and update these info automatically if they are changed.

Being able to get these info from (https://spdx.org/licenses/licenses.json)

>  "isOsiApproved": true

Each licenses have OSI appeove "true/false" like above.

More details :
(https://github.com/spdx/license-list-data/tree/master/json/details)

#### Screenshots

![license_osi](https://user-images.githubusercontent.com/39894802/112980039-5314ee00-9194-11eb-812d-0a5e9d0f521f.png)

**Comment by shi9qiu** [comment]
I think it may be good to add a new column here named "SPDX Approved" to declare whether this license is included in the SPDX License List or not.
