### ISSUE TITLE
Add release to project from release view (or component release listing)

### ISSUE THREAD

**Issue by maierthomas** [eclipse/sw360#117]
<a href="https://github.com/mcjaeger"><img src="https://avatars1.githubusercontent.com/u/3418977?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [mcjaeger](https://github.com/mcjaeger)**
_Thursday Jun 08, 2017 at 13:58 GMT_
_Originally opened as https://github.com/sw360/sw360portal/issues/443_

----

Currently, linking a release to a project works from the project edit view.

Another workflow mode is possible:
* user is at some release (because she created that release, the a button (proposed at the top button row as with other elements) can directly open a dialogue box for linking this release to a project
* use is at release overview of a component. An icon at the right allows the user to directly link this release to a project by displaying dialogue box
* optionally,: let the adding user to edit the two values that are part of the relation: project mainline state and release relation
* moderation and so should work in the same way as with editing the project.

**Comment by lepokle** [comment]
I'm on it now.
