### ISSUE TITLE
User add Vulnerabilities info by themselves

### ISSUE THREAD

**Issue by KoukiHama** [eclipse/sw360#1170]
[//]: # (Copyright Siemens AG, 2021. Part of the SW360 Portal Project)
[//]: # (This program and the accompanying materials are made)
[//]: # (available under the terms of the Eclipse Public License 2.0)
[//]: # (which is available at https://www.eclipse.org/legal/epl-2.0/)
[//]: # (SPDX-License-Identifier: EPL-2.0)

### Description
Now, sw360 get CVE info and manage this data, but user cannot add this kinds of data.

#### Steps followed and expected result
User add Vulnerabilities  by GUI or API, user can link component/release and  Vulnerabilities by manually.

Need to consider what kind of roles add/change?
For example : Only security admin and admin ?
 https://github.com/eclipse/sw360/wiki/Dev-Role-Authorisation-Model#security-admin-liferay-role

#### Screenshots
![Add_Vul](https://user-images.githubusercontent.com/39894802/113397450-07eb1d00-93d8-11eb-9027-b86fa968cfa7.png)

**Comment by KoukiHama** [comment]
#1257
#1258

Realizing this issue by API

**Comment by mcjaeger** [comment]
so since the APi is there, the portal could use the same backend call ...

**Comment by tienlee** [comment]
Hello,

I would like to share the GUI of create, update, delete Vulnerability.
We refer to CVSS v2.
https://www.first.org/cvss/v2/guide

Now, we are implementing these GUIs.
About API, linking component/release and Vulnerabilities by manually and roles, I will check and discuss with @KoukiHama later.

If you have any comment about the GUI, please let me know

**Index page**

![Vulnerabilities-index-page](https://user-images.githubusercontent.com/15809618/160072784-d1fa497e-8c79-4e55-a8b5-2b5796e1ef52.png)

**Add page**

![Vulnerabilities-add-page](https://user-images.githubusercontent.com/15809618/160072778-7f3b370e-0c53-4d6d-9c35-a3d8623a878c.png)

**Edit page**

![Vulnerabilities-edit-page](https://user-images.githubusercontent.com/15809618/160072767-0fa3cc24-01aa-4f22-aa06-61353ce8c348.png)
