### ISSUE TITLE
Re-Evaluate if Linked Projects and Releases and Linked Releases could be unified.

### ISSUE THREAD

**Issue by maierthomas** [eclipse/sw360#118]
<a href="https://github.com/mcjaeger"><img src="https://avatars1.githubusercontent.com/u/3418977?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [mcjaeger](https://github.com/mcjaeger)**
_Friday Jun 09, 2017 at 08:51 GMT_
_Originally opened as https://github.com/sw360/sw360portal/issues/445_

----

Currently there is some overlap between the linked releases and the linked projects as they show very similar things.

Discussion is, if the two view could be unified to one. Major issue might be response time.

**Comment by mcjaeger** [comment]
(from discussion), actually, thre three views could be unified:
* linked projects and releases
* linked releases
* clearing status

-> clearing status could have a switch view between flat mode and hierarchy.

**Comment by mcjaeger** [comment]
actually it has been finally done: 

<img width="1458" alt="Screenshot 2021-03-24 at 22 41 32" src="https://user-images.githubusercontent.com/3418977/112387472-1a879700-8cf2-11eb-9ee1-062e42b56efd.png">
