### ISSUE TITLE
Need REST API to add/edit "Linked release Comment" section when Linking releases to SW360 Project

### ISSUE THREAD

**Issue by JaideepPalit** [eclipse/sw360#1192]
### Description

(from sw360 user)

As per the existing SW360 Rest API guide, A POST/PATCH request is used to link releases to the project(i.e, An array of release ids to be linked as request body)
Our Requirement :

While Linking releases to the SW360 Project using REST API Call, we would like to add/edit the "Comment" section of the Linked Release.
We the Clearing Automation team, need an REST API to add/edit the "Linked release Comment" section along with each Release ID's to be linked (in array) to the SW360 project using REST API call

Purpose :
In future , to identify whether the release is linked to the SW360 Project by an automation tool.

**Comment by KoukiHama** [comment]
#863 This is  almost same issue.
