### ISSUE TITLE
Automatic logoff is happening way too early.  How to increase the session time?

### ISSUE THREAD

**Issue by dineshr93** [eclipse/sw360#1219]
[//]: # (Copyright Siemens AG, 2021. Part of the SW360 Portal Project)
[//]: # (This program and the accompanying materials are made)
[//]: # (available under the terms of the Eclipse Public License 2.0)
[//]: # (which is available at https://www.eclipse.org/legal/epl-2.0/)
[//]: # (SPDX-License-Identifier: EPL-2.0)

### Description

Automatic logoff is happening way too early. How to increase the session time?

### Versions

Last commit id on master: 13.3.0-M1
Operating System (lsb_release -a): Ubuntu 18.04

**Comment by nam-np** [comment]
I think can increase the session time:

> LIFERAY_HOME/tomcat/webapps/ROOT/WEB-INF/web.xml


```
<session-config>
   <session-timeout>30</session-timeout>
</session-config>
```

**Comment by dineshr93** [comment]
Thanks @nam-np .. It worked
