### ISSUE TITLE
Clearing state for releases in a project should only for clearing admins

### ISSUE THREAD

**Issue by maierthomas** [eclipse/sw360#122]
<a href="https://github.com/mcjaeger"><img src="https://avatars1.githubusercontent.com/u/3418977?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [mcjaeger](https://github.com/mcjaeger)**
_Monday Jun 19, 2017 at 13:30 GMT_
_Originally opened as https://github.com/sw360/sw360portal/issues/463_

----

The change of the project-specific clearing state of a linked release shall be changeable only the clearing admin. Please note that this should be done on API level (not in the UI), also instead of a moderation request maybe rejection could be considered.

**Comment by mcjaeger** [comment]
is there even project clearing state is open:

<img width="1053" alt="Screenshot 2020-03-05 at 01 03 38" src="https://user-images.githubusercontent.com/3418977/75934587-32894000-5e7d-11ea-8621-660cd257533c.png">
