### ISSUE TITLE
Component list  Sorting Error base on component name 

### ISSUE THREAD

**Issue by KoukiHama** [eclipse/sw360#1223]
[//]: # (Copyright Siemens AG, 2021. Part of the SW360 Portal Project)
[//]: # (This program and the accompanying materials are made)
[//]: # (available under the terms of the Eclipse Public License 2.0)
[//]: # (which is available at https://www.eclipse.org/legal/epl-2.0/)
[//]: # (SPDX-License-Identifier: EPL-2.0)

### Description

As far as I know, 13.1 or older version use alphabetical sort in component tab.
But new one  use other sort algorithm and make mistakes.  

#1199 have reported similar issue, but that mention about license name or vender name.

#### Screenshots

I made 12 component. And I show them all at once. 
Then I select "Show 25 entries"

![image](https://user-images.githubusercontent.com/39894802/118923959-5a2bd180-b977-11eb-80ea-db98393880d2.png)

After I changed  "Show 10 entries"

![image](https://user-images.githubusercontent.com/39894802/118924106-952e0500-b977-11eb-9b15-0158ee7124a3.png)

2 Components are missing.  
(If they are sorted by alphabetical order, Component "A" and Component "Browser" should be there  )

If I go to next page (page2), I can find  Component A and Component "Browser"

![image](https://user-images.githubusercontent.com/39894802/118924361-f524ab80-b977-11eb-94cf-167f34400af0.png)

And if I use sort bottom (in page1), The results seems to be fine  

![image](https://user-images.githubusercontent.com/39894802/118925737-2900d080-b97a-11eb-8cd2-3ac9daed892b.png)

### Versions

* Last commit id on master:  Version: 13.4.0-SNAPSHOT | Branch: master (ee4ea77) 
* Operating System (lsb_release -a):

### Logs

Any logs (if any) generated in

#### SW360 logs

Logs generated under /var/log/sw360/sw360.log

#### Tomcat logs

Logs generated under /var/log/tomcat/error.log

**Comment by mcjaeger** [comment]
might be solved with the cloudant migration, needs retest

**Comment by KoukiHama** [comment]
> might be solved with the cloudant migration, needs retest

As far as I know, after cloudant migration this issued is happened.

**Comment by AlbertHjy** [comment]
The code below causes this issue.
 
https://github.com/eclipse/sw360/blob/5255b1f5e70a82015dce3afb00f05cefee849e03/frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/components/ComponentPortlet.java#L2003

```
        PaginationData pageData = new PaginationData();
        pageData.setRowsPerPage(paginationParameters.getDisplayLength());
        pageData.setDisplayStart(paginationParameters.getDisplayStart());
        pageData.setAscending(paginationParameters.isAscending().get());
        int sortParam = -1;
        if (paginationParameters.getSortingColumn().isPresent()) {
            sortParam = paginationParameters.getSortingColumn().get();
            if (sortParam == 1 && Integer.valueOf(paginationParameters.getEcho()) == 1) {
                pageData.setSortColumnNumber(-1);
            }
        } else {
            pageData.setSortColumnNumber(sortParam);
        }

        Map<PaginationData, List<Component>> pageDataComponentList = getFilteredComponentList(request, pageData);
```

paginationParameters.getSortingColumn().isPresent() always is true, when you select `Component Name` as the order column, the value of `paginationParameters.getEcho()` is not 1, so the `sortColumnNumber` in `pageData` is not set, then the default value `0` is passed to `getFilteredComponentList(request, pageData)`, so actually the component is ordered by  vendor, not by component name.

I don't know if there is any special reason why sortColumnNumber is set to `-1`, need to get clarification before fix the issue.

**Comment by smrutis1** [comment]
Sorry for coming to this lately.

1. The `-1` here signifies the default sorting(`byCreatedOn`), when we click on the components tab. May be we need to update it to `byname` to make it consistent with the older version.
Ref: https://github.com/eclipse/sw360/blob/137113a8a692a7e450491be507e26abb62fc60e9/backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/ComponentRepository.java#L259

**Comment by KoukiHama** [comment]
Still existed this issue.

**Comment by KoukiHama** [comment]
Currently, if the user goes to the component page at the first time, the components will be sorted by "CreatedOn". After that, the user goes to the next page, the components will be sorted by "Name".
The behavior is not incorrect, but it will cause misunderstanding for users.
