### ISSUE TITLE
Build failure of sw360dev.Dockerfile and compileWithDocker.sh

### ISSUE THREAD

**Issue by ymdysk** [eclipse/sw360#1230]
[//]: # (Copyright Siemens AG, 2021. Part of the SW360 Portal Project)
[//]: # (This program and the accompanying materials are made)
[//]: # (available under the terms of the Eclipse Public License 2.0)
[//]: # (which is available at https://www.eclipse.org/legal/epl-2.0/)
[//]: # (SPDX-License-Identifier: EPL-2.0)

### Description

SW360 build failure of sw360dev.Dockerfile and compileWithDocker.sh

- What you intended to do?
 SW360 can be built successfully.

- What did you observe?
 SW360 couldn’t build for following error.

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project datahandler: Fatal error compiling: invalid target release: 11 -> [Help 1]

- Why do you think it is wrong
 SW360 can be built with “Dockerfile”, though cannot be built with "sw360dev.Dockerfile".

"Dockerfile" is newer and uses maven:3.6.3-openjdk-11-slim image, based on Debian.
"sw360dev.Dockerfile" uses maven:3.5.0-jdk-8-alpine image based on Alpine.
Currently, "su-exec" command is used for the old maven image, though the newer image based on Debian does not have "su-exec" command, so need to use equivalent feature to use the newer image.

#### How to reproduce

Execute scripts/compileWithDocker.sh

#### Screenshots

Execution:
![sw360docker_fix1_1](https://user-images.githubusercontent.com/17672118/119658398-0eda5d00-be68-11eb-9459-b7cbbabc3ffc.png)

Result:
![sw360docker_fix1_2](https://user-images.githubusercontent.com/17672118/119658419-1568d480-be68-11eb-9c03-88212090381c.png)

### Versions

* Last commit id on master:
SW360 v13.1.0, Git commit ID: 72ae005a6b4dfc7f6e2c84195b4037024ae4aff4
* Operating System (lsb_release -a):
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.5 LTS
Release:        18.04
Codename:       bionic

**Comment by mcjaeger** [comment]
tested it with current master https://github.com/eclipse/sw360/commit/a54e93e8d651b3c50434d91fa0418f59e62f7a91 and runs again
