### ISSUE TITLE
The search is inconsistent

### ISSUE THREAD

**Issue by maierthomas** [eclipse/sw360#124]
<a href="https://github.com/maxhbr"><img src="https://avatars3.githubusercontent.com/u/1187050?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [maxhbr](https://github.com/maxhbr)**
_Wednesday Jun 21, 2017 at 08:31 GMT_
_Originally opened as https://github.com/sw360/sw360portal/issues/468_

----

With the search portlet, you can generate two types of lucene-queries:
with search mask (i.e. with some of the six possible types checked) or
without search mask (no type is checked).
The latter should search for _all_ types, also types that are not in the list.
Searching for a common search string such as "GPL" returns a smaller number of search results when searching without search mask, than when searching with "license" checked. This is unexpected and inconsistent. -> when license is checked, then results should be licenses only.

It turns out that the method `searchView(luceneSearchView, queryString)` from class `LuceneAwareDatabaseConnector` and with `luceneSearchView` defined in class `DatabaseSearchHandler` returns more rows for `queryString`  "(type:license) text*" than for `queryString`   "text*".

**Comment by maierthomas** [comment]
<a href="https://github.com/maxhbr"><img src="https://avatars3.githubusercontent.com/u/1187050?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [maxhbr](https://github.com/maxhbr)**
_Thursday Jul 06, 2017 at 13:36 GMT_

----

relates #361

**Comment by maierthomas** [comment]
<a href="https://github.com/mcjaeger"><img src="https://avatars1.githubusercontent.com/u/3418977?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [mcjaeger](https://github.com/mcjaeger)**
_Wednesday Nov 22, 2017 at 12:30 GMT_

----

one trick is that the 'search mask' (the pane of checkboxes) actually adds users to this while the plain search when nothing is selected does not involve users. For licenses this seems to have a similar effect.

Indeed, the search without anything checked should be the same as with all items checked. In fact it would be even better if the checkboxes would be checked by default, so the user is not confused. and then if no checkbox is checked, then search button turns disabled.

**Comment by mcjaeger** [comment]
(from discussion) needs to be tested with almost new instance (and SPDX Licenses imported) to have full clarity. Initial tests on productive data sets did not show obvious issues.

**Comment by mcjaeger** [comment]
search seems to be consistent now after some productive experience, using quotes will help a lot.
