### ISSUE TITLE
Clearing Request: Agreed clearing date needs to be same or future day to close the CR 

### ISSUE THREAD

**Issue by akapti** [eclipse/sw360#1247]
[//]: # (Copyright Siemens AG, 2021. Part of the SW360 Portal Project)
[//]: # (This program and the accompanying materials are made)
[//]: # (available under the terms of the Eclipse Public License 2.0)
[//]: # (which is available at https://www.eclipse.org/legal/epl-2.0/)
[//]: # (SPDX-License-Identifier: EPL-2.0)

### Description

`Clearing request` cannot be closed, once `Agreed clearing date` is passed.
The only way to close the `CR` is to unset the `Agreed clearing date` or set it to future date.

#### How to reproduce

Create a `Clearing request`, set the `Agreed clearing date` to some previous date in database (for reproducing the issue)
Now you'll not be able to `Close` the `CR`.

**Comment by mcjaeger** [comment]
@akapti  close the issue?
