### ISSUE TITLE
Clearing Request: Feature enhancement.

### ISSUE THREAD

**Issue by akapti** [eclipse/sw360#1248]
[//]: # (Copyright Siemens AG, 2021. Part of the SW360 Portal Project)
[//]: # (This program and the accompanying materials are made)
[//]: # (available under the terms of the Eclipse Public License 2.0)
[//]: # (which is available at https://www.eclipse.org/legal/epl-2.0/)
[//]: # (SPDX-License-Identifier: EPL-2.0)

### Description

1. Add a new field `Priority` with following values: (This field should be displayed in Open clearing request table)
    1. LOW
    2. MEDIUM
    3. HIGH
    4. CRITICAL

2. Remove (hide) the clearing team field from Open CR table.
3. Enable Priority to be set by the clearing team (in Edit mode).
4. Enable `Requester comment` while re-opening the CR. 
    1. This comment should be added as a part of CR update comment.
5. Change the logic of selecting the `Preferred clearing date`, such that.
    1. User with role `Admin` should be able to decide the number of future days to be disabled while selecting `Preferred clearing date`.
6. When the requester needs the clearing before the `Preferred clearing date` threshold set in step 5, Then requester can mark it as `Critical` in UI (via checkbox). This should create the `CR` with priority as `Critical`.
    1. This should be possible if and only if there are less than 2 critical CR.
    2. If there are 2 or more critical CR, then `Critical` checkbox should not be shown.
    3. The checkbox should have following info text `In case you need the clearing at an earlier date than the preferred date that is available, please check the critical checkbox and reselect the preferred clearing date.`
7. Log a comment, if there is a change in clearing team email.

**Comment by mcjaeger** [comment]
@akapti so the isue could be closed?

**Comment by akapti** [comment]
PR is merged. closing the issue.
