### ISSUE TITLE
improve CouchDB performance by implementing "Joins" on repository level

### ISSUE THREAD

**Issue by maierthomas** [eclipse/sw360#125]
<a href="https://github.com/maxhbr"><img src="https://avatars3.githubusercontent.com/u/1187050?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [maxhbr](https://github.com/maxhbr)**
_Thursday Jul 06, 2017 at 12:11 GMT_
_Originally opened as https://github.com/sw360/sw360portal/issues/480_

----

It is possible to implement a CouchDB view which does something like a "Join" (see: http://www.cmlenz.net/archives/2007/10/couchdb-joins). This would allow us to requests from CouchDB a list of Projects together with all Releases for the Project sorted by complex keys.

The problem is, how to implement that in Ektorp or how to deserialize the response from CouchDB.

One problem is that the result set may not have mixed result types (like projects and releases) for Ektorp currently. Maybe a contribution for the ektorp project is required.

**Comment by maierthomas** [comment]
<a href="https://github.com/mcjaeger"><img src="https://avatars1.githubusercontent.com/u/3418977?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [mcjaeger](https://github.com/mcjaeger)**
_Wednesday Nov 22, 2017 at 12:26 GMT_

----

discussion has been continued here:
https://github.com/sw360/sw360portal/pull/596

**Comment by mcjaeger** [comment]
ektorp is being moved out and cloudant is coming in:

https://github.com/eclipse/sw360/pull/1149
