### ISSUE TITLE
Missing milestone releases for the SW360 client library

### ISSUE THREAD

**Issue by sschuberth** [eclipse/sw360#1259]
At https://repo.eclipse.org/content/repositories/sw360-releases/org/eclipse/sw360/client/ there's a milestone release for the 13.1.0 series ([13.1.0-m1](https://repo.eclipse.org/content/repositories/sw360-releases/org/eclipse/sw360/client/13.1.0-m1/)), but no milestone releases for the 13.2.0 and 13.3.0 series. While I'm personally ok with not getting any retrospective milestone releases for those past series, would it be possible to get a milestone release for 13.4.0 once it's final?

**Comment by mcjaeger** [comment]
yes i think that is the plan

**Comment by sschuberth** [comment]
FYI, there's still no `13.4.0-m1` release for the client library at https://repo.eclipse.org/content/repositories/sw360-releases/org/eclipse/sw360/client/.

**Comment by sschuberth** [comment]
@JaideepPalit looks like the issue persist for the new 14.0.0-M1 release. Can you please have a look?

**Comment by sschuberth** [comment]
@heliocastro is there something you can do to help addressing this, and finally get some a milestone (i.e. non-weekly) release for the client library for use in ORT?

**Comment by heliocastro** [comment]
@sschuberth I will add a main point on this one to next meeting. Is even a little cumbersome since the library is really old

**Comment by sschuberth** [comment]
Thanks @heliocastro!

**Comment by mcjaeger** [comment]
I suspect that `build.eclipe.org` has been renamed to `ci.eclipse.org` and thus why it is failing now (see logs for the failing jobs): https://ci.eclipse.org/sw360/job/sw360.deploy/
as a consequence the deploy to the nexus fails. I will dig further into it.

**Comment by heliocastro** [comment]
Fixed on last main commit. Jenkins builds are green.
If new issues appears on resulting artifacts please open a new issue

* Postmortem
build.eclipse.org was decommissioned and Maven plugin jarsigner was too outdated, so the combination causes system to try use an invalid host.
