### ISSUE TITLE
Irretating tooltip for download of attachment bundles

### ISSUE THREAD

**Issue by maierthomas** [eclipse/sw360#127]
<a href="https://github.com/lepokle"><img src="https://avatars1.githubusercontent.com/u/499823?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [lepokle](https://github.com/lepokle)**
_Monday Jul 10, 2017 at 14:47 GMT_
_Originally opened as https://github.com/sw360/sw360portal/issues/487_

----

Due to a bugfix during #424, the tooltip for downloading an attachment bundle is now "Download AttachmentBundle.zip" instead of "Download  ". However, if only one attachment is present, this file is downloaded directly wo zip container.
There are two solutions:
1) (very simple) Change tooltip to attachment name if only one attachment is present
2) (unknown) Always create zip container, event if there is only one attachment

**Comment by nutanv1contr** [comment]
I am looking into it.
