### ISSUE TITLE
Update Velocity version

### ISSUE THREAD

**Issue by maierthomas** [eclipse/sw360#128]
<a href="https://github.com/bs-jokri"><img src="https://avatars2.githubusercontent.com/u/13886571?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [bs-jokri](https://github.com/bs-jokri)**
_Monday Jul 10, 2017 at 15:48 GMT_
_Originally opened as https://github.com/sw360/sw360portal/issues/489_

----

We have Velocity and Velocity tools as dependencies. Velocity tools introduces a very old struts version that has a dependency to a very old antlr version.

Velocity will be released in version 2.0 in the near future
http://mail-archives.apache.org/mod_mbox/velocity-dev/201706.mbox/browser

We should keep an eye on it and update asap.

**Comment by maierthomas** [comment]
<a href="https://github.com/bs-jokri"><img src="https://avatars2.githubusercontent.com/u/13886571?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [bs-jokri](https://github.com/bs-jokri)**
_Monday Jul 10, 2017 at 15:49 GMT_

----

Corresponding ticket in Velocity issue tracker is
https://issues.apache.org/jira/browse/VELTOOLS-171

**Comment by maierthomas** [comment]
<a href="https://github.com/bs-jokri"><img src="https://avatars2.githubusercontent.com/u/13886571?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [bs-jokri](https://github.com/bs-jokri)**
_Tuesday Jul 18, 2017 at 08:02 GMT_

----

New Velocity version available 
https://dist.apache.org/repos/dist/dev/velocity/velocity-engine/2.0/release-notes.html

Velocity tools will be released soon(as stated in the Velocity release notes).

**Comment by lepokle** [comment]
This issue is ready for review and testing.
