### ISSUE TITLE
Multi Group visibility Error by name matching method

### ISSUE THREAD

**Issue by KoukiHama** [eclipse/sw360#1281]
[//]: # (Copyright Siemens AG, 2021. Part of the SW360 Portal Project)
[//]: # (This program and the accompanying materials are made)
[//]: # (available under the terms of the Eclipse Public License 2.0)
[//]: # (which is available at https://www.eclipse.org/legal/epl-2.0/)
[//]: # (SPDX-License-Identifier: EPL-2.0)

### Description

If the Visibility of the project is set to "Group and Moderators", the user's Department name is being compared to the BusinessUnit of the Project by left-hand match(Prefix match,  by "startsWith()" method )  .

For example, if the user's organization is named "DEPARTMENT", it will also match projects such as "DEPARTMENT3", and these will be displayed.

https://github.com/eclipse/sw360/blob/024aff8504a8a942f2879d46d589e2268816c69f/libraries/lib-datahandler/src/main/java/org/eclipse/sw360/datahandler/permissions/ProjectPermissions.java#L67-L71

For https://github.com/eclipse/sw360/pull/1187, perfect match method should be used.

#### Screenshots

Describe the bug and list the steps you used when the issue occurred.

Creating Project by non admin user who belong to DEPARTMENT3,

![image](https://user-images.githubusercontent.com/39894802/123219662-1abd4b80-d508-11eb-93f2-7c2a2da44ed9.png)

Logout and Open the project page by user who belong DEPARTMENT.

![image](https://user-images.githubusercontent.com/39894802/123219943-67088b80-d508-11eb-98ff-90433b81f5e9.png)

This page is only for DEPARTMENT3 and moderator, but "**the user who is a member of DEPARTMENT  and is not member of DEPARTMENT3**" can see this page.

![image](https://user-images.githubusercontent.com/39894802/123220020-7ee00f80-d508-11eb-8cad-d0ceef7a2d79.png)

### Versions

* Last commit id on master:  de98ec2
* Operating System (lsb_release -a):

**Comment by nam-np** [comment]
The java string `startsWith()` method checks if this string starts with given prefix. It returns `true` if this string starts with given prefix else returns `false`.

**Comment by mcjaeger** [comment]
maybe it could be changed from `startsWith()` to a kind of `equals()`. It will be better if it is equals, otherwise we have always the issue with "Department", "Department2", "Department1"

**Comment by shi9qiu** [comment]
> maybe it could be changed from `startsWith()` to a kind of `equals()`. It will be better if it is equals, otherwise we have always the issue with "Department", "Department2", "Department1"

Yes it is. I am fixing and testing this.

**Comment by KoukiHama** [comment]
> maybe it could be changed from `startsWith()` to a kind of `equals()`. It will be better if it is equals, otherwise we have always the issue with "Department", "Department2", "Department1"

You point out this bug?

Make "DEPARTMENT2" (written in uppercase letter) Project with  "Group and Moderators" 

![image](https://user-images.githubusercontent.com/39894802/125010383-5c6dfa80-e0a1-11eb-94ff-faf2714f3942.png)

add  "department2" (written in lowercase letter) and add  User5 who is a member of "department2"

![image](https://user-images.githubusercontent.com/39894802/125010401-655ecc00-e0a1-11eb-8652-8905ba4f507f.png)

department2 's(lowercase) User5 can see DEPARTMENT2(uppercase) project.

![image](https://user-images.githubusercontent.com/39894802/125010415-6d1e7080-e0a1-11eb-9b9a-ee7cdce2d5cf.png)

**Comment by KoukiHama** [comment]
Solved by #1307
