### ISSUE TITLE
startCouchdbForTests.sh is outdated

### ISSUE THREAD

**Issue by KoukiHama** [eclipse/sw360#1287]
[//]: # (Copyright Siemens AG, 2021. Part of the SW360 Portal Project)
[//]: # (This program and the accompanying materials are made)
[//]: # (available under the terms of the Eclipse Public License 2.0)
[//]: # (which is available at https://www.eclipse.org/legal/epl-2.0/)
[//]: # (SPDX-License-Identifier: EPL-2.0)

### Description

startCouchdbForTests.sh is useful for doing test.
But, this script install couchdb1.7

We should update.

But, which version should sw360 use now, couchdb:2.3.1 or couchdb:3 ? 

https://github.com/eclipse/sw360/blob/ddce31ebe80eab7ef23ba3606ce6f0176561780f/scripts/startCouchdbForTests.sh#L22-L27

#### Steps followed and expected result

Describe the steps followed by you and your expected results after following the steps.

**Comment by KoukiHama** [comment]
Related  #1084

**Comment by KoukiHama** [comment]
https://github.com/eclipse/sw360/blob/ddce31ebe80eab7ef23ba3606ce6f0176561780f/scripts/docker-config/install_scripts/install_configure_couchdb.sh#L25

Should we update this 2.3.X or 3.x too?

**Comment by mcjaeger** [comment]
in my opinion 3.X would be better. let's not support two versions, because it could mean more effort.

**Comment by KoukiHama** [comment]
OK I will make pull request for updating  couch3.x from 1.x or 2.x.

**Comment by KoukiHama** [comment]
>Tests in error:
  testGetAttachmentsUsagesWithFilter(org.eclipse.sw360.attachments.AttachmentHandlerTest): 405 Method Not Allowed at http://localhost:5984/sw360_test_db/_design/AttachmentUsage/_view/usagesByAttachmentUsageType/queries. Error: method_not_allowed. Reason: Only GET,POST,HEAD allowed.
  testGetAttachmentUsagesWithFilter(org.eclipse.sw360.attachments.AttachmentHandlerTest): 405 Method Not Allowed at http://localhost:5984/sw360_test_db/_design/AttachmentUsage/_view/usagesByAttachmentUsageType/queries. Error: method_not_allowed. Reason: Only GET,POST,HEAD allowed.
  testGetAttachmentsUsages(org.eclipse.sw360.attachments.AttachmentHandlerTest): 405 Method Not Allowed at http://localhost:5984/sw360_test_db/_design/AttachmentUsage/_view/usagesByAttachment/queries. Error: method_not_allowed. Reason: Only GET,POST,HEAD allowed.
  testGetAttachmentUsages(org.eclipse.sw360.attachments.AttachmentHandlerTest): 405 Method Not Allowed at http://localhost:5984/sw360_test_db/_design/AttachmentUsage/_view/usagesByAttachment/queries. Error: method_not_allowed. Reason: Only GET,POST,HEAD allowed.

> Tests run: 21, Failures: 0, Errors: 4, Skipped: 0

>[INFO] src-attachments .................................... FAILURE [02:23 min]


If I use coucdb 2.1.2. Test Error is happened, This may be another reason that we need to update couchdb version.

**Comment by KoukiHama** [comment]
It is Solved by #1309
