### ISSUE TITLE
SW360Admin can not see projects of "Me and Moderators" visibility

### ISSUE THREAD

**Issue by ymdysk** [eclipse/sw360#1290]
[//]: # (Copyright Siemens AG, 2021. Part of the SW360 Portal Project)
[//]: # (This program and the accompanying materials are made)
[//]: # (available under the terms of the Eclipse Public License 2.0)
[//]: # (which is available at https://www.eclipse.org/legal/epl-2.0/)
[//]: # (SPDX-License-Identifier: EPL-2.0)

### Description

- What you intended to do?
 SW360Admin would be able to see all projects, including visibility:Me and Moderators

- What did you observe?
 SW360Admin couldn't see user's project with visibility "Me and Moderators"
![sw360admin_project_invisibility](https://user-images.githubusercontent.com/17672118/124280191-5947ab80-db83-11eb-893f-2327fa1844fa.png)

- Why do you think it is wrong
 SW360Admin would be able to see all project. For reference, see access matrix below.  
 I think it's natural that Administrator can see any projects, excluding private project.
![sw360admin_project_invisibility2](https://user-images.githubusercontent.com/17672118/124280542-c78c6e00-db83-11eb-8c54-8027ff5f32b9.png)
https://github.com/eclipse/sw360/wiki/Dev-Role-Authorisation-Model

#### How to reproduce

Describe the bug and list the steps you used when the issue occurred.

#### Screenshots

Please see the first screenshot in this thread.

### Versions

* Last commit id on master: 72ae005a6b4dfc7f6e2c84195b4037024ae4aff4
* Operating System (lsb_release -a):
Distributor ID: Ubuntu
Description: Ubuntu 18.04.5 LTS
Release: 18.04
Codename: bionic

**Comment by KoukiHama** [comment]
This is related to #178 

Especially,
-  admin should be able to see everything

from  https://github.com/eclipse/sw360/issues/178#issuecomment-384681218

**Comment by mcjaeger** [comment]
(from discussion of the telco). actually it was a feature that the sw360 cannot see private projects. but it could be a configure option.

**Comment by KoukiHama** [comment]
#113 is microsoft relation to this issue, but
It is also admin issue.
