### ISSUE TITLE
globally remember **show [10/25/50/100] entries** drop down selection as personal default

### ISSUE THREAD

**Issue by maierthomas** [eclipse/sw360#132]
<a href="https://github.com/AndreasSchirm"><img src="https://avatars2.githubusercontent.com/u/14091910?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [AndreasSchirm](https://github.com/AndreasSchirm)**
_Friday Jul 14, 2017 at 12:40 GMT_
_Originally opened as https://github.com/sw360/sw360portal/issues/501_

----

## Actual State
default of the select 10/25/50/100 entries drop down box is value of 10.  
see:
![img_2017 07 14_ 14 39 10](https://user-images.githubusercontent.com/14091910/28212544-3784749a-68a2-11e7-83d5-5ab2f9cd64ce.png)

## Fix
remember the  selected value globally. 
As a user I expect that when I select 100, leave come back to sw360 the next day, this selection of 100 is default for my personal setting.
![img_2017 07 14_ 14 31 43](https://user-images.githubusercontent.com/14091910/28212350-5887a212-68a1-11e7-9135-5fd842ac0793.png)

## Improvement
add show all

**Comment by maierthomas** [comment]
<a href="https://github.com/mcjaeger"><img src="https://avatars1.githubusercontent.com/u/3418977?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [mcjaeger](https://github.com/mcjaeger)**
_Wednesday Aug 16, 2017 at 11:10 GMT_

----

we will pull this out again once the listing of components will be faster

**Comment by maierthomas** [comment]
<a href="https://github.com/AndreasSchirm"><img src="https://avatars2.githubusercontent.com/u/14091910?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [AndreasSchirm](https://github.com/AndreasSchirm)**
_Wednesday Aug 16, 2017 at 11:29 GMT_

----

If sw360 will be fast enough to show all entries less then one second it is absolutely fine for me to drop this feature request.

**Comment by mcjaeger** [comment]
actually closing because we have the view limit eliminated with paging added to the master.
