### ISSUE TITLE
Edit Clearing Request gives JS error

### ISSUE THREAD

**Issue by JaideepPalit** [eclipse/sw360#1320]
### Description

Edit Clearing Request gives JS error

![image](https://user-images.githubusercontent.com/56534710/126953680-1e78b592-4b6e-464c-8660-0249e721eab3.png)

![image](https://user-images.githubusercontent.com/56534710/126953941-374beb47-de34-4d6a-8150-9b81d97bad4b.png)

**Comment by mcjaeger** [comment]
ok, after merged it is also solved ...
