### ISSUE TITLE
(question) put component type (OSS, COTS, ...) in release

### ISSUE THREAD

**Issue by maierthomas** [eclipse/sw360#133]
<a href="https://github.com/mcjaeger"><img src="https://avatars1.githubusercontent.com/u/3418977?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [mcjaeger](https://github.com/mcjaeger)**
_Wednesday Jul 19, 2017 at 08:26 GMT_
_Originally opened as https://github.com/sw360/sw360portal/issues/507_

----

There is some discussion why the component type in component not in release, because:
* there could be OSS (community edition) releases and commercial release of the same component
* there is the problem that data quality is not good anyways so maybe the components place is better
* solution could be to have this at components, which is automatically inherited by a releases, and at the release, the user can overwrite it.
* But that is difficult to display, because what would be the value that is set for a new release of the component when there are one OSS release and one COTS release at the component before and the aggregated value at the component is then [OSS,COTS] ...

**Comment by mcjaeger** [comment]
(from discussion) let's close it for now because there does not seem to be a strong reason for having either one or another.
