### ISSUE TITLE
Output the change log of the project, component, and release

### ISSUE THREAD

**Issue by shi9qiu** [eclipse/sw360#1339]
[//]: # (Copyright Siemens AG, 2021. Part of the SW360 Portal Project)
[//]: # (This program and the accompanying materials are made)
[//]: # (available under the terms of the Eclipse Public License 2.0)
[//]: # (which is available at https://www.eclipse.org/legal/epl-2.0/)
[//]: # (SPDX-License-Identifier: EPL-2.0)

### Description

Some users may want to output the change log of the project, component, and release, but now there is no this kind of function.

#### Steps followed and expected result

When users do the change (add, update, delete, etc.) to the project, component, or release, the change log should be output to somewhere.

**Comment by KoukiHama** [comment]
This issue was solved by #1341
