### ISSUE TITLE
Handle HttpClientErrorException in liferayAuthCheckRequest() method

### ISSUE THREAD

**Issue by shi9qiu** [eclipse/sw360#1340]
[//]: # (Copyright Siemens AG, 2021. Part of the SW360 Portal Project)
[//]: # (This program and the accompanying materials are made)
[//]: # (available under the terms of the Eclipse Public License 2.0)
[//]: # (which is available at https://www.eclipse.org/legal/epl-2.0/)
[//]: # (SPDX-License-Identifier: EPL-2.0)

### Description

https://github.com/eclipse/sw360/blob/c7b1335d4561c1736285d37baa61277c6420ae02/rest/authorization-server/src/main/java/org/eclipse/sw360/rest/authserver/security/basicauth/Sw360LiferayAuthenticationProvider.java#L123-L124

These lines may throw HttpClientErrorException. I think this exception should be catched and handled just like other exceptions in this liferayAuthCheckRequest() method.

#### How to reproduce

Describe the bug and list the steps you used when the issue occurred.

### Versions

* Last commit id on master: c7b1335
* Operating System (lsb_release -a): Ubuntu 18.04 LTS

### Logs

Any logs (if any) generated in

#### SW360 logs

Logs generated under /var/log/sw360/sw360.log

#### Tomcat logs

Logs generated under /var/log/tomcat/error.log

**Comment by KoukiHama** [comment]
This is solved by #1342
