### ISSUE TITLE
Project usage at Release Summary view is broken

### ISSUE THREAD

**Issue by maierthomas** [eclipse/sw360#136]
<a href="https://github.com/mcjaeger"><img src="https://avatars1.githubusercontent.com/u/3418977?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [mcjaeger](https://github.com/mcjaeger)**
_Wednesday Jul 26, 2017 at 09:35 GMT_
_Originally opened as https://github.com/sw360/sw360portal/issues/518_

----

In the release summary page, the bottom most elements is the usage in projects. Opposed to the same counterpart in the Components summary, the Group and Project Responsible is not visible (even it is set)
It should be there ...

**Comment by maierthomas** [comment]
<a href="https://github.com/alexbrdn"><img src="https://avatars0.githubusercontent.com/u/16780167?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [alexbrdn](https://github.com/alexbrdn)**
_Wednesday Jul 26, 2017 at 09:37 GMT_

----

`ProjectRepository.searchByReleaseId(String id, User user)` returns a different summary compared to `searchByReleaseId(Set<String> ids, User user)`. The short summary of projects doesn't contain the group and project responsible fields.

**Comment by mcjaeger** [comment]
It is fixed now and works quite good.
