### ISSUE TITLE
Failure when run 'mvn install' (Test failed)

### ISSUE THREAD

**Issue by quan-tv** [eclipse/sw360#1373]
### Description

Failed to build the latest source code from master branch.

#### How to reproduce

1. Check out the source code from master branch.

2. Execute 'mvn install'

> Tests run: 64, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.243 sec
> Running org.eclipse.sw360.datahandler.permissions.DocumentPermissionsTest
> Tests run: 8, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.005 sec
> Running org.eclipse.sw360.datahandler.permissions.ReleasePermissionsTest
> Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.054 sec
> Running org.eclipse.sw360.datahandler.resourcelists.PaginationResultTest
> Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0 sec
> Running org.eclipse.sw360.datahandler.resourcelists.ResourceComparatorGeneratorTest
> Tests run: 13, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.024 sec
> Running org.eclipse.sw360.datahandler.resourcelists.ResourceListControllerTest
> Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.008 sec
> Running org.eclipse.sw360.datahandler.resourcelists.PaginationOptionsTest
> Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.001 sec
> Running org.eclipse.sw360.datahandler.test.TestServiceHandlerTest
> Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.002 sec
> Running org.eclipse.sw360.datahandler.couchdb.DatabaseConnectorTest
> **Tests run: 14, Failures: 0, Errors: 14, Skipped: 0, Time elapsed: 0.116 sec <<< FAILURE!**
> **testGetDocument(org.eclipse.sw360.datahandler.couchdb.DatabaseConnectorTest)  Time elapsed: 0.095 sec  <<< ERROR!**

### Versions

* Last commit id on master: https://github.com/eclipse/sw360/commit/90b5fe43f99b7b7e28af8268dd733fcda0bae454
* CouchDB version: 2.1.2

### Logs
[log.txt](https://github.com/eclipse/sw360/files/7158738/log.txt)

Not sure it is related to this issue or not: https://github.com/eclipse/sw360/issues/1333

**Comment by KoukiHama** [comment]
I did test on CouchDB3.1 and Thrift14 and set couchdb-test.properties in /etc/sw360
and All test is passed without problem

couchdb-test.properties

> couchdb.url = http://localhost:5984
couchdb.user = admin
couchdb.password = password
couchdb.database = sw360_test_db
couchdb.usersdb = sw360_test_users
couchdb.attachments = sw360_test_attachments
couchdb.config = sw360_test_config
couchdb.vulnerability_management = sw360_test_vm
couchdb.lucene.url = http://localhost:8080/couchdb-lucene

**Comment by quan-tv** [comment]
Clean everything and re-build SW360, everything is fine.

It seems that this is my local environment issue.

Issue closed.
