### ISSUE TITLE
Revision History in SW360

### ISSUE THREAD

**Issue by maierthomas** [eclipse/sw360#138]
<a href="https://github.com/ImfeldC"><img src="https://avatars2.githubusercontent.com/u/4012160?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [ImfeldC](https://github.com/ImfeldC)**
_Thursday Jul 27, 2017 at 14:42 GMT_
_Originally opened as https://github.com/sw360/sw360portal/issues/524_

----

sw360 should provide a revision history, to track changes.

Track changes ...
- It should be possible to track changes done on "data sets"
- Collect: "Data set" before, "Data set" afterwards, **when** was the change done, **where** was the change done (e.g. in case multiple servers/clients are used) and **who** has made the changes

Display changes ...
- "Simple view" for all users (if required due legal constraints, w/o personal user information)
- "Detailed view" for power users or administrators

(This CR is also tracked with https://code.siemens.com/sw360/sw360portal/issues/70 )

Some examples of possible views:
---------------------------
![image](https://user-images.githubusercontent.com/3418977/41648506-670f695c-7479-11e8-86c0-ec3f2f9c674d.png)
---------------------------
![image](https://user-images.githubusercontent.com/3418977/41648557-8ae44d8e-7479-11e8-89c2-e7eeb93c4359.png)

---------------------------

---------------------------

**Comment by mcjaeger** [comment]
(from discussion, relevant link) https://stackoverflow.com/questions/2825438/couchdb-versioning-auditing

**Comment by mcjaeger** [comment]
I think it is there, there are proposals for improvements, such as the clear name of a release instead of the id, but in general, it is working.
