### ISSUE TITLE
Double Quotes in Components and Release Name breaks Listing

### ISSUE THREAD

**Issue by maierthomas** [eclipse/sw360#139]
<a href="https://github.com/mcjaeger"><img src="https://avatars1.githubusercontent.com/u/3418977?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [mcjaeger](https://github.com/mcjaeger)**
_Wednesday Aug 16, 2017 at 11:01 GMT_
_Originally opened as https://github.com/sw360/sw360portal/issues/534_

----

When using double quotes in component name or release name or version, the according liustings are broken (=do not display any entry). Display values should use HTML escaped quotes.

(For Project listing with single or double quote it works).

**Comment by maierthomas** [comment]
<a href="https://github.com/bodetc"><img src="https://avatars2.githubusercontent.com/u/22469333?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [bodetc](https://github.com/bodetc)**
_Tuesday Nov 07, 2017 at 10:20 GMT_

----

Fixed by https://github.com/sw360/sw360portal/issues/327

**Comment by maierthomas** [comment]
<a href="https://github.com/adrian-evo"><img src="https://avatars0.githubusercontent.com/u/19324942?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [adrian-evo](https://github.com/adrian-evo)**
_Wednesday Nov 15, 2017 at 09:35 GMT_

----

Not fully fixed for component name. On edit page, the quoted name is not displayed.

![quote](https://user-images.githubusercontent.com/19324942/32828859-fc0e3cf8-c9f8-11e7-9ea0-618302bcc84b.PNG)

**Comment by maierthomas** [comment]
<a href="https://github.com/mcjaeger"><img src="https://avatars1.githubusercontent.com/u/3418977?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [mcjaeger](https://github.com/mcjaeger)**
_Wednesday Nov 22, 2017 at 13:34 GMT_

----

confirm, same error is still there

**Comment by maierthomas** [comment]
<a href="https://github.com/maierthomas"><img src="https://avatars1.githubusercontent.com/u/29916928?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [maierthomas](https://github.com/maierthomas)**
_Thursday Nov 23, 2017 at 16:47 GMT_

----

please verify also

```
> ./homepage/signup/view.jsp: value="${newuser.givenname}" id="given_name">
> ./homepage/signup/view.jsp: value="${newuser.lastname}" id="last_name">
> ./homepage/signup/view.jsp:  <option value="${org.name}" class="textlabel stackedLabel"
> ./homepage/signup/view.jsp:  >${org.name}</option>
> ./projects/view.jsp: value="${name}" id="project_name" class="filterInput">
> ./projects/view.jsp:  <option value="${org.name}" class="textlabel stackedLabel"
> ./projects/view.jsp:  >${org.name}</option>
> ./projects/includes/projects/vulnerabilities.jspf:  "0": "${vulnerability.intReleaseName}",
> ./projects/includes/projects/vulnerabilities.jspf:  "6": '<div class="dataTables_cell_nowrap">${vulnerability.action}</div>'
> ./licenses/detail.jsp:  class="pageHeaderBigSpan">License: ${licenseDetail.fullname} (${licenseDetail.shortname})</span>
> ./licenses/includes/editDetailText.jspf:  placeholder="Enter the License-Text here...">${licenseDetail.text}</textarea>
> ./licenses/includes/detailText.jspf:  ${licenseDetail.text}
> ./licenses/includes/detailSummary.jspf:  <thead><tr><th colspan="2">License Details: ${licenseDetail.fullname} (${licenseDetail.shortname})</th></tr></thead>
> ./licenses/includes/detailTodos.jspf:  <form action="${editLicenseTodosURL}" method="post" id="FormTodosWhitelist" name="FormTodosWhitelist">
> ./components/detailRelease.jsp:  <p class="pageHeader"><label id="releaseHeaderLabel"> <span class="pageHeaderBigSpan"> Component: ${component.name}</span>
> ./components/detail.jsp:  <p class="pageHeader"><span class="pageHeaderBigSpan">Component: ${component.name}</span>
> ./components/view.jsp: value="${name}" id="component_name">
> ./components/view.jsp: value="${categories}" id="categories">
> ./components/view.jsp: value="${languages}" id="languages">
> ./components/view.jsp: value="${softwarePlatforms}" id="software_platforms">
> ./components/view.jsp: value="${operatingSystems}" id="operating_systems">
> ./components/view.jsp: value="${vendorNames}" id="vendor_names">
> ./components/view.jsp: value="${mainLicenseIds}" id="main_licenses">
> ./components/includes/components/editBasicInfo.jspf: value="${component.name}"/>
> ./components/includes/components/editBasicInfo.jspf:  var checkComponentNameUrl = '${checkComponentNameUrl}',
> ./components/includes/components/vulnerabilities.jspf:  "0": "${vulnerability.intReleaseName}",
> ./moderation/components/delete.jsp:<p class="pageHeader"><span class="pageHeaderBigSpan">Moderation Delete Component: ${component.name}</span>
> ./moderation/components/merge.jsp:<p class="pageHeader"><span class="pageHeaderBigSpan">Moderation Change Component: ${component.name}</span>
> ./utils/ajax/linkedProjectsRows.jspf:  value="${projectLink.name} ${projectLink.version}" maxChar="60"
> ./utils/includes/linkedReleaseDetails.jspf:  data-scope-group-id="${pageContext.getAttribute('scopeGroupId')}"
> ./utils/includes/usingComponentsTable.jspf:  <th colspan="4">${documentName} is used by the following components</th>
> ./utils/includes/usingProjectsTable.jspf:  <th colspan="3">${documentName} is used by the following projects</th>
> ./utils/includes/attachmentsDetail.jsp:  "fileName": "${attachment.filename}"
```

**Comment by maierthomas** [comment]
<a href="https://github.com/maierthomas"><img src="https://avatars1.githubusercontent.com/u/29916928?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [maierthomas](https://github.com/maierthomas)**
_Friday Dec 01, 2017 at 17:23 GMT_

----

please verify also
- projects/administrationEdit.jsp -> licenseInfoHeaderText

**Comment by maierthomas** [comment]
<a href="https://github.com/bodetc"><img src="https://avatars2.githubusercontent.com/u/22469333?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [bodetc](https://github.com/bodetc)**
_Wednesday Dec 13, 2017 at 10:30 GMT_

----

- [x] ./homepage/signup/view.jsp: value="${newuser.givenname}" id="given_name">
- [x] ./homepage/signup/view.jsp: value="${newuser.lastname}" id="last_name">
- [x] ./homepage/signup/view.jsp:  <option value="${org.name}" class="textlabel stackedLabel"
- [x] ./homepage/signup/view.jsp:  >${org.name}</option>
- [x] ./projects/view.jsp: value="${name}" id="project_name" class="filterInput">
- [x] ./projects/view.jsp:  <option value="${org.name}" class="textlabel stackedLabel"
- [x] ./projects/view.jsp:  >${org.name}</option>
- [x] ./projects/includes/projects/vulnerabilities.jspf:  "0": "${vulnerability.intReleaseName}",
- [x] ./projects/includes/projects/vulnerabilities.jspf:  "6": '<div class="dataTables_cell_nowrap">${vulnerability.action}</div>'
- [x] ./licenses/detail.jsp:  class="pageHeaderBigSpan">License: ${licenseDetail.fullname} (${licenseDetail.shortname})</span>
- [x] ./licenses/includes/editDetailText.jspf:  placeholder="Enter the License-Text here...">${licenseDetail.text}</textarea>
- [x] ./licenses/includes/detailText.jspf:  ${licenseDetail.text}
- [x] ./licenses/includes/detailSummary.jspf:  <thead><tr><th colspan="2">License Details: ${licenseDetail.fullname} (${licenseDetail.shortname})</th></tr></thead>
- [x] ./licenses/includes/detailTodos.jspf:  <form action="${editLicenseTodosURL}" method="post" id="FormTodosWhitelist" name="FormTodosWhitelist">
- [x] ./components/detailRelease.jsp:  <p class="pageHeader"><label id="releaseHeaderLabel"> <span class="pageHeaderBigSpan"> Component: ${component.name}</span>
- [x] ./components/detail.jsp:  <p class="pageHeader"><span class="pageHeaderBigSpan">Component: ${component.name}</span>
- [x] ./components/view.jsp: value="${name}" id="component_name">
- [x] ./components/view.jsp: value="${categories}" id="categories">
- [x] ./components/view.jsp: value="${languages}" id="languages">
- [x] ./components/view.jsp: value="${softwarePlatforms}" id="software_platforms">
- [x] ./components/view.jsp: value="${operatingSystems}" id="operating_systems">
- [x] ./components/view.jsp: value="${vendorNames}" id="vendor_names">
- [x] ./components/view.jsp: value="${mainLicenseIds}" id="main_licenses">
- [x] ./components/includes/components/editBasicInfo.jspf: value="${component.name}"/>
- [x] ./components/includes/components/editBasicInfo.jspf:  var checkComponentNameUrl = '${checkComponentNameUrl}',
- [x] ./components/includes/components/vulnerabilities.jspf:  "0": "${vulnerability.intReleaseName}",
- [x] ./moderation/components/delete.jsp:<p class="pageHeader"><span class="pageHeaderBigSpan">Moderation Delete Component: ${component.name}</span>
- [x] ./moderation/components/merge.jsp:<p class="pageHeader"><span class="pageHeaderBigSpan">Moderation Change Component: ${component.name}</span>
- [x] ./utils/ajax/linkedProjectsRows.jspf:  value="${projectLink.name} ${projectLink.version}" maxChar="60"
- [x] ./utils/includes/linkedReleaseDetails.jspf:  data-scope-group-id="${pageContext.getAttribute('scopeGroupId')}"
- [x] ./utils/includes/usingComponentsTable.jspf:  <th colspan="4">${documentName} is used by the following components</th>
- [x] ./utils/includes/usingProjectsTable.jspf:  <th colspan="3">${documentName} is used by the following projects</th>
- [x] ./utils/includes/attachmentsDetail.jsp:  "fileName": "${attachment.filename}"
- [x] ./utils/includes/attachmentsDetail.jsp:  "fileName": "${attachment.filename}"
- [x] ./projects/administrationEdit.jsp -> licenseInfoHeaderText

**Comment by mcjaeger** [comment]
(from discussion) looks like Cedric has covered this quite systematically. Pls. consider opening again or create a new issue for new cases.
