### ISSUE TITLE
To support uploading of new automatically generated scan reports to SW360, a new type of clearingState shall be added to sw360

### ISSUE THREAD

**Issue by JaideepPalit** [eclipse/sw360#1390]
### Description

(from sw360 user) 

To support uploading of new automatically generated scan reports to SW360, a new type of clearingState shall be added to sw360

Also, a corresponding new attachment type should be created probably with a different color code. And attachments with this `ATTACHMENT_TYPE` should not trigger a `CLEARING_STATE` change. (e.g from `NEW` to `REPORT_AVAILABLE`) like how the `CLX` and `CRT` does at present.

**Comment by JaideepPalit** [comment]
some queries.
1. What should be the name of Attachment Type.
   - Currently using `INITIAL_SCAN_REPORT` kindly suggest 
      - Is new Attachment Type of Ok or needs to be changed?
      - Is there any existing type which can be reused like `SCAN_RESULT_REPORT = 7,  SCAN_RESULT_REPORT_XML = 8,`

2. Since Clearing State(disabled in UI and Rest) of a Release is automatically calculated based on attachments and fossology scan from sw360.
   - Here is what I am Planning to do.
   - Change Clearing State to new option(`SCAN_AVAILABLE`) , when there is an attachment present of type (`INITIAL_SCAN_REPORT`) , Status of attachments can be `Not Checked`, `Approved` or ` Rejected`.
       - However this will happen after previous old evaluation is complete like `CLX and CRT does at present.` and  `fossology scan`. After these old evaluation, if Clearing State is still `New` only then (`SCAN_AVAILABLE`) evaluation will be considered.
Hope it is ok ? Kindly suggest if some changes are required.

```
enum AttachmentType {
    DOCUMENT = 0,
    SOURCE = 1,
    DESIGN = 2,
    REQUIREMENT = 3,
    CLEARING_REPORT = 4,
    COMPONENT_LICENSE_INFO_XML = 5,
    COMPONENT_LICENSE_INFO_COMBINED = 6,
    SCAN_RESULT_REPORT = 7,
    SCAN_RESULT_REPORT_XML = 8,
    SOURCE_SELF = 9,
    BINARY = 10,
    BINARY_SELF = 11,
    DECISION_REPORT = 12,
    LEGAL_EVALUATION = 13,
    LICENSE_AGREEMENT = 14,
    SCREENSHOT = 15,
    OTHER = 16,
    README_OSS = 17,
    INITIAL_SCAN_REPORT = 18
}
```

**Comment by arunazhakesan** [comment]
Hi @JaideepPalit 

1. The `SCAN_AVAILABLE` state should change the color of the button to `Yellow` or `Orange`

> However this will happen after previous old evaluation is complete like CLX and CRT does at present. and fossology scan. After these old evaluation, if Clearing State is still New only then (SCAN_AVAILABLE) evaluation will be considered.
Hope it is ok ? Kindly suggest if some changes are required.

I did not understand the above comment, could you please elaborate?

The ideal workflow should be as follows:

1. User/BOT uploads the `INITIAL)SCAN_REPORT` (ISR) to SW360
2. Clearing state is now changed to `SCAN_AVAILABLE` from `New` (button color - Yellow/orange)
3.  The attachment type should not permitted to be approved by any user
4.  This attachment type should not be considered for `Readme_OSS` generation

**Comment by JaideepPalit** [comment]
Hi @arunazhakesan 

> I did not understand the above comment, could you please elaborate?

- Currently Clearing State is a disabled field. And value changes based of 
   - type of attachments - CLX and CRT does at present.
   - Fossology scan triggered from sw360
- Question is what happens when 
   - Clearing State is already approved/available/any-other-value and User/BOT uploads the INITIAL)SCAN_REPORT (ISR) to SW360 ?
   - As a solution to above scenario - I was suggesting that after all previous evaluation is considered like
        - type of attachments - CLX and CRT does at present.
        - Fossology scan triggered from sw360
        - Still if State is NEW then 
            - Clearing state is changed to SCAN_AVAILABLE if INITIAL_SCAN_REPORT is available

**Comment by arunazhakesan** [comment]
@JaideepPalit , Please go ahead with the color `Orange` for `scan available`
