### ISSUE TITLE
Fossology token is not accepted by sw360 but token works well if executed in api testing sw Insomnia (like postman)

### ISSUE THREAD

**Issue by dineshr93** [eclipse/sw360#1392]
[//]: # (Copyright Siemens AG, 2021. Part of the SW360 Portal Project)
[//]: # (This program and the accompanying materials are made)
[//]: # (available under the terms of the Eclipse Public License 2.0)
[//]: # (which is available at https://www.eclipse.org/legal/epl-2.0/)
[//]: # (SPDX-License-Identifier: EPL-2.0)

### Description

refer  https://github.com/fossology/fossology/issues/2105#issue-1014116898

From this comment https://github.com/fossology/fossology/issues/2105#issuecomment-933656756

SW360 requires some change in the URL.

#### How to reproduce

refer  https://github.com/fossology/fossology/issues/2105#issue-1014116898

#### Screenshots
please check this fossology ticket https://github.com/fossology/fossology/issues/2105

### Versions

* Last commit id on master:  13.4.0 | Branch: UNKNOWN (e9856a4)
* Operating System (lsb_release -a): Ubuntu 18.04

### Logs

refer https://github.com/fossology/fossology/issues/2105#issue-1014116898

**Comment by GMishx** [comment]
Thank you @dineshr93 , so it goes to `/repo/api/v1/folders` :+1:
