### ISSUE TITLE
Show selected Project/Component Name in Browser Tab / Document Title

### ISSUE THREAD

**Issue by maierthomas** [eclipse/sw360#140]
<a href="https://github.com/AndreasSchirm"><img src="https://avatars2.githubusercontent.com/u/14091910?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [AndreasSchirm](https://github.com/AndreasSchirm)**
_Tuesday Sep 05, 2017 at 08:32 GMT_
_Originally opened as https://github.com/sw360/sw360portal/issues/550_

----

## Expected Behavior
A browser tab should contain the actual selected project or component.

## Current Behavior
![img_2017 09 05_ 10 26 35](https://user-images.githubusercontent.com/14091910/30052104-bd06d81e-9224-11e7-843c-f5917bdc4cf4.png)
It is always the generic text `Projects - SW360` ot `Components - SW360`.

## Possible Solution
Set html title to the corresponding Project/Component.

**Comment by nutanv1contr** [comment]
I would like to work on this.
