### ISSUE TITLE
Similar components dialog is open despite empty list

### ISSUE THREAD

**Issue by maierthomas** [eclipse/sw360#141]
<a href="https://github.com/alexbrdn"><img src="https://avatars0.githubusercontent.com/u/16780167?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [alexbrdn](https://github.com/alexbrdn)**
_Tuesday Sep 05, 2017 at 09:14 GMT_
_Originally opened as https://github.com/sw360/sw360portal/issues/552_

----

When creating a component, the dialog that shows components with similar names (#528) should not be displayed or should be closed automatically when no components with similar names were found. As it is right now, the dialog only serves to annoy the user by basically saying "Check out these similar components... er, we didn't find any similar ones, actually".

**Comment by maierthomas** [comment]
<a href="https://github.com/imaykay"><img src="https://avatars2.githubusercontent.com/u/27430165?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [imaykay](https://github.com/imaykay)**
_Wednesday Sep 06, 2017 at 12:25 GMT_

----

The idea behind this behavior is just to tell the user that a similar component search happened. Me as a user, I would ask myself if I can add the component safely when no dialog opens - after I got used to see similar components in some cases. I am into consistency ;-)

So I would prefer an auto close mechanism after two seconds or something.

**Comment by maierthomas** [comment]
<a href="https://github.com/alexbrdn"><img src="https://avatars0.githubusercontent.com/u/16780167?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [alexbrdn](https://github.com/alexbrdn)**
_Wednesday Sep 06, 2017 at 12:44 GMT_

----

I'm fine with the autoclose. I just don't like the extra click necessary to get rid of the dialog that doesn't tell me anything I really need to know.

**Comment by maierthomas** [comment]
<a href="https://github.com/mcjaeger"><img src="https://avatars1.githubusercontent.com/u/3418977?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [mcjaeger](https://github.com/mcjaeger)**
_Wednesday Nov 22, 2017 at 13:08 GMT_

----

(from discussion) we should test whether stopping the user with open/close is more confusing or maybe open/close directly is even more confusing.

**Comment by mcjaeger** [comment]
is not there anymore
