### ISSUE TITLE
Make the feature -Restrict visibility of each component/release like Project Configurable.

### ISSUE THREAD

**Issue by ravi110336** [eclipse/sw360#1425]
[//]: # (Copyright Siemens AG, 2021. Part of the SW360 Portal Project)
[//]: # (This program and the accompanying materials are made)
[//]: # (available under the terms of the Eclipse Public License 2.0)
[//]: # (which is available at https://www.eclipse.org/legal/epl-2.0/)
[//]: # (SPDX-License-Identifier: EPL-2.0)

### Description

As discussed in our meeting we want to make component visibility feature configurable for the user who wants to use this feature or not. Because as in Siemens we want to share all our information on components and releases.

#### Steps followed and expected result

Describe the steps followed by you and your expected results after following the steps.

**Comment by ravi110336** [comment]
PR reference:
https://github.com/eclipse/sw360/pull/1357

**Comment by KoukiHama** [comment]
I'll do my best to get it done as soon as possible.

**Comment by KoukiHama** [comment]
I followed this issue.  
Merged #1357
