### ISSUE TITLE
link vulnerabilities that are affected by a specific vulnerability

### ISSUE THREAD

**Issue by maierthomas** [eclipse/sw360#144]
<a href="https://github.com/bs-jokri"><img src="https://avatars2.githubusercontent.com/u/13886571?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [bs-jokri](https://github.com/bs-jokri)**
_Monday Sep 11, 2017 at 12:17 GMT_
_Originally opened as https://github.com/sw360/sw360portal/issues/574_

----

As a security admin I want to see the releases in the sw360 database that are affected by a specific vulnerability. For that:
- Implemented backend to get releases associated with vulnerabilities
- Implemented frontend to display the releases associated with each vulnerability

**Comment by blaumeiser-at-bosch** [comment]
Obsolete
