### ISSUE TITLE
LicenseInfo file in DOCX format has some formatting issues

### ISSUE THREAD

**Issue by maierthomas** [eclipse/sw360#145]
<a href="https://github.com/bs-jokri"><img src="https://avatars2.githubusercontent.com/u/13886571?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [bs-jokri](https://github.com/bs-jokri)**
_Monday Sep 11, 2017 at 12:22 GMT_
_Originally opened as https://github.com/sw360/sw360portal/issues/575_

----

- License names have LicenseRef prefix in License Info Documents when using SPDX
- License Texts miss formatting in lLicense Info document when using SPDX RDF
- License Texts are present multiple times in License Info Doc if generated from spdx report

**Comment by blaumeiser-at-bosch** [comment]
Obsolete
