### ISSUE TITLE
Attachments served with gzip header triggers auto unpack in Chrome

### ISSUE THREAD

**Issue by maierthomas** [eclipse/sw360#146]
<a href="https://github.com/mcjaeger"><img src="https://avatars1.githubusercontent.com/u/3418977?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [mcjaeger](https://github.com/mcjaeger)**
_Monday Sep 11, 2017 at 14:57 GMT_
_Originally opened as https://github.com/sw360/sw360portal/issues/576_

----

.. but should not. what happens actually:

* Download tar.gz as attachment
* will be saved but unpacked apparently with *.gz file ending. on Chrome, so it is not a *.gz anymore
* removing the *.gz manuelly solved the problem

tested with two attachments.

it is described here:
https://superuser.com/questions/940605/chromium-prevent-unpacking-tar-gz

maybe an issue of nginx (or tomcat).

**Comment by mcjaeger** [comment]
closed by https://github.com/eclipse/sw360/pull/306
