### ISSUE TITLE
One lisence cound add only 10 obligations [13.4]

### ISSUE THREAD

**Issue by wang-fut** [eclipse/sw360#1463]
### Description

Basiclly everything is in the title already.

#### How to reproduce

I cound add more than 10 obligations in the "Select License Obligations to be added" page,
and also I can check more than 10 obligations before clicking the "Update" button.
But after clicking the "Update" button, there are only 10 obligations left in the "Linked Obligations" tab.

I checked the db and found that only 10 "obligationDatabaseIds" linked in the license document
so I think it is not a display error.

#### Screenshots

1. Edit page
![image](https://user-images.githubusercontent.com/95271446/153341608-36d482c2-3ac5-41f8-b986-84803e1efde3.png)

2. Updated
![image](https://user-images.githubusercontent.com/95271446/153341682-be24a201-477a-42c1-9d6d-e4512e526c74.png)

### Versions

* 13.4.0-M1
* docker build and native build on RHEL 8

**Comment by KoukiHama** [comment]
@wang-fut 
we fix this. Please check master branch if you have time.
