### ISSUE TITLE
Fossology scan failed

### ISSUE THREAD

**Issue by AlexanderMiske** [eclipse/sw360#1478]
[//]: # (Copyright Siemens AG, 2021. Part of the SW360 Portal Project)
[//]: # (This program and the accompanying materials are made)
[//]: # (available under the terms of the Eclipse Public License 2.0)
[//]: # (which is available at https://www.eclipse.org/legal/epl-2.0/)
[//]: # (SPDX-License-Identifier: EPL-2.0)

### Description

Trigger a Fossology scan failed.
On Log I get the entry:  

#### How to reproduce

Create  a component and add a release. After that trigger the fossology scan.

#### Screenshots

![image](https://user-images.githubusercontent.com/101117395/157045531-69264f64-414d-4cc3-a094-ea3022132547.png)

### Versions
I used the branch: sw360_single_fossology.

### Logs

Any logs (if any) generated in

#### SW360 logs

Logs generated under /var/log/sw360/sw360.log

#### Tomcat logs

Logs generated under /var/log/tomcat/error.log

**Comment by mcjaeger** [comment]
It looks like with current master and currently merged docker it works for me:
![Screenshot 2022-03-16 at 12 50 24](https://user-images.githubusercontent.com/3418977/159659323-eddf47e5-1d4c-4431-b956-b2004289f368.png)

from the error message it looks like there is not attachment with the type `source code` at the release.

**Comment by heliocastro** [comment]
@AlexanderMiske Can we close the ticket ?

**Comment by AlexanderMiske** [comment]
Yes.

**Comment by heliocastro** [comment]
Fixed on Fossology. 
Reference https://github.com/fossology/fossology/pull/2174
