### ISSUE TITLE
Filtering with Query: Partial Loading Setting Confusing

### ISSUE THREAD

**Issue by maierthomas** [eclipse/sw360#148]
<a href="https://github.com/mcjaeger"><img src="https://avatars1.githubusercontent.com/u/3418977?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [mcjaeger](https://github.com/mcjaeger)**
_Monday Sep 18, 2017 at 11:23 GMT_
_Originally opened as https://github.com/sw360/sw360portal/issues/584_

----

For Component and Vulnerabilities: when querying for a (truncated) name, for example the result table loads, but the setting for the partial loading from the data base is set to a confusing default value: "50" while the loaded items can be more like what the filter query actually returns.

In fact when doing the filtering query, the partial loading is not active.

The user should see that the partial loading is not active and thus should e deactivated like made grey unless filtered query is removed again.

**Comment by mcjaeger** [comment]
it is removed in the Liferay 7 UI, so closing ...
