### ISSUE TITLE
The value of "visibility" is not correct when getting the list of all projects with REST API

### ISSUE THREAD

**Issue by shi9qiu** [eclipse/sw360#1484]
[//]: # (Copyright Siemens AG, 2021. Part of the SW360 Portal Project)
[//]: # (This program and the accompanying materials are made)
[//]: # (available under the terms of the Eclipse Public License 2.0)
[//]: # (which is available at https://www.eclipse.org/legal/epl-2.0/)
[//]: # (SPDX-License-Identifier: EPL-2.0)

### Description

When I use REST API to get the list of all projects, The value of "visibility" is not correct. The value of "Visibility" is always "BUISNESSUNIT_AND_MODERATORS" instead of the correct one.

#### How to reproduce

Just use REST API（\*\*\*/resource/api/projects）to get the list of all projects. In the response, you can confirm this issue. For example,

````json
            {
                "name": "Application001",
                "version": "",
                "securityResponsibles": [],
                "projectType": "CUSTOMER",
                "visibility": "BUISNESSUNIT_AND_MODERATORS",
                "_links": {
                    "self": {
                        "href": "http://***/resource/api/projects/0ab67cf249"
                    }
                }
            },
````
However, if the "allDetails=true" option is added, we could get the correct value.

### Versions

* Last commit id on master: e9762d149af6795cbdfe004b5a3a9d160f622f78
* Operating System (lsb_release -a):

### Logs

Any logs (if any) generated in

#### SW360 logs

Logs generated under /var/log/sw360/sw360.log

#### Tomcat logs

Logs generated under /var/log/tomcat/error.log

**Comment by nam-np** [comment]
I think that maybe related to
https://github.com/eclipse/sw360/blob/e3a48500b5ac01517a4fb1045d9f99d912138641/rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/core/RestControllerHelper.java#L419-L427

You can try and new line:
`embeddedProject.setVisibility(project.getVisibility()); 
`

**Comment by KoukiHama** [comment]
Fixed
