### ISSUE TITLE
Generate sw360 example data

### ISSUE THREAD

**Issue by maierthomas** [eclipse/sw360#150]
<a href="https://github.com/mcjaeger"><img src="https://avatars1.githubusercontent.com/u/3418977?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [mcjaeger](https://github.com/mcjaeger)**
_Thursday Sep 21, 2017 at 12:35 GMT_
_Originally opened as https://github.com/sw360/sw360portal/issues/593_

----

For testing and presentation we should have sw360 example data sets for components/releases, projects,licenses and vulnerabilities.

**Comment by mcjaeger** [comment]
today, it could be done with SPDX BOM import using a RDX/XMl file to have some project with components and releases.

**Comment by mcjaeger** [comment]
it is an almost three year old issue ... closing
