### ISSUE TITLE
The file Private_Pages_7_3_3_GA4.lar cannot be imported.

### ISSUE THREAD

**Issue by yyosioka** [eclipse/sw360#1501]
[//]: # (Copyright Siemens AG, 2021. Part of the SW360 Portal Project)
[//]: # (This program and the accompanying materials are made)
[//]: # (available under the terms of the Eclipse Public License 2.0)
[//]: # (which is available at https://www.eclipse.org/legal/epl-2.0/)
[//]: # (SPDX-License-Identifier: EPL-2.0)

### Description

The file Private_Pages_7_3_3_GA4.lar cannot be imported.

When does this problem occur?
For example, can it occur when the communication port is restricted?

#### How to reproduce
The environment was constructed with reference to the following page.
https://github.com/eclipse/sw360/blob/master/README_DOCKER.md

1 git clone https://github.com/eclipse/sw360.git
2 cd sw360
3 ./docker_build.sh
The build was successful with no problems.
4 Connect to "http://xx.xx.xxx.xxx:8080/" in your chrome browser and sign in
5 Select "Publishing" from the side menu, then "Import
6 Select +.
7 I imported the "Private_Pages_7_3_GA4.lar" file that I had downloaded from"https://github.com/eclipse/sw360/tree/master/frontend/configuration".
8 The following error is displayed
The file Public_Pages_7_3_3_GA4.lar cannot be imported.
The following error occurred within com.liferay.portlet.exportimport.service.impl.ExportImportLocalServiceImpl: java.util.zip.ZipException: zip END header not found.

#### Screenshots
![cannot-be-import](https://user-images.githubusercontent.com/62535924/162178872-dbd80e43-e34b-4727-a376-a1d3f385b1f0.png)

### Versions
2022/4/7 latest acquisition

#### sw360 logs
sw360         | 2022-04-07 07:17:34.743 WARN  [http-nio-8080-exec-2][PortalImpl:1037] Redirect URL http://xx.xx.xx.xx:8080/group/guest/~/control_panel/manage?p_p_id=com_liferay_exportimport_web_portlet_ImportPortlet&p_p_lifecycle=0&p_p_state=normal&p_p_state_rcv=1&p_p_auth=HvLKxD5S is not allowed
sw360         | 2022-04-07 07:17:39.798 WARN  [http-nio-8080-exec-9][PortalImpl:1037] Redirect URL http://xx.xx.xx.xx:8080/group/guest/~/control_panel/manage?p_p_id=com_liferay_exportimport_web_portlet_ImportPortlet&p_p_lifecycle=0&p_p_state=normal&p_p_state_rcv=1&p_p_auth=HvLKxD5S is not allowed
sw360         | 2022-04-07 07:17:39.852 WARN  [http-nio-8080-exec-9][PortalImpl:1037] Redirect URL http://xx.xx.xx.xx:8080/group/guest/~/control_panel/manage?p_p_id=com_liferay_exportimport_web_portlet_ImportPortlet&p_p_lifecycle=0&p_p_state=maximized&_com_liferay_exportimport_web_portlet_ImportPortlet_mvcPath=%2Fimport%2Fview.jsp&p_p_auth=HvLKxD5S is not allowed
sw360         | 2022-04-07 07:17:53.737 ERROR [http-nio-8080-exec-4][StagingImpl:1056] com.liferay.exportimport.kernel.exception.ExportImportRuntimeException: java.util.zip.ZipException: zip END header not found
sw360         | com.liferay.exportimport.kernel.exception.ExportImportRuntimeException: java.util.zip.ZipException: zip END header not found
sw360         | 	at com.liferay.portlet.exportimport.service.impl.ExportImportLocalServiceImpl.validateImportLayoutsFile(ExportImportLocalServiceImpl.java:612)
sw360         | 	at com.liferay.portlet.exportimport.service.impl.ExportImportLocalServiceImpl.validateImportLayoutsFile(ExportImportLocalServiceImpl.java:634)
sw360         | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
sw360         | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
sw360         | 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
sw360         | 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
sw360         | 	at com.liferay.portal.spring.aop.AopMethodInvocationImpl.proceed(AopMethodInvocationImpl.java:50)
sw360         | 	at com.liferay.portal.spring.transaction.TransactionInterceptor.invoke(TransactionInterceptor.java:69)
sw360         | 	at com.liferay.portal.spring.aop.AopMethodInvocationImpl.proceed(AopMethodInvocationImpl.java:57)
sw360         | 	at com.liferay.change.tracking.internal.aop.CTTransactionAdvice.invoke(CTTransactionAdvice.java:72)
sw360         | 	at com.liferay.portal.spring.aop.AopMethodInvocationImpl.proceed(AopMethodInvocationImpl.java:57)
sw360         | 	at com.liferay.portal.spring.aop.AopInvocationHandler.invoke(AopInvocationHandler.java:49)
sw360         | 	at com.sun.proxy.$Proxy118.validateImportLayoutsFile(Unknown Source)
sw360         | 	at com.liferay.portlet.exportimport.service.impl.ExportImportServiceImpl.validateImportLayoutsFile(ExportImportServiceImpl.java:277)
sw360         | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
sw360         | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
sw360         | 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
sw360         | 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
sw360         | 	at com.liferay.portal.spring.aop.AopMethodInvocationImpl.proceed(AopMethodInvocationImpl.java:50)
sw360         | 	at com.liferay.portal.spring.transaction.TransactionInterceptor.invoke(TransactionInterceptor.java:69)
sw360         | 	at com.liferay.portal.spring.aop.AopMethodInvocationImpl.proceed(AopMethodInvocationImpl.java:57)
sw360         | 	at com.liferay.portal.kernel.aop.ChainableMethodAdvice.invoke(ChainableMethodAdvice.java:64)
sw360         | 	at com.liferay.portal.spring.aop.AopMethodInvocationImpl.proceed(AopMethodInvocationImpl.java:57)
sw360         | 	at com.liferay.change.tracking.internal.aop.CTTransactionAdvice.invoke(CTTransactionAdvice.java:72)
sw360         | 	at com.liferay.portal.spring.aop.AopMethodInvocationImpl.proceed(AopMethodInvocationImpl.java:57)
sw360         | 	at com.liferay.portal.spring.aop.AopInvocationHandler.invoke(AopInvocationHandler.java:49)
sw360         | 	at com.sun.proxy.$Proxy138.validateImportLayoutsFile(Unknown Source)
sw360         | 	at com.liferay.exportimport.web.internal.portlet.action.ImportLayoutsMVCActionCommand.validateFile(ImportLayoutsMVCActionCommand.java:438)
sw360         | 	at com.liferay.exportimport.web.internal.portlet.action.ImportLayoutsMVCActionCommand.validateFile(ImportLayoutsMVCActionCommand.java:387)
sw360         | 	at com.liferay.exportimport.web.internal.portlet.action.ImportLayoutsMVCActionCommand.doProcessAction(ImportLayoutsMVCActionCommand.java:212)
sw360         | 	at com.liferay.portal.kernel.portlet.bridges.mvc.BaseMVCActionCommand.processAction(BaseMVCActionCommand.java:61)
sw360         | 	at com.liferay.portal.kernel.portlet.bridges.mvc.MVCPortlet.callActionMethod(MVCPortlet.java:359)
sw360         | 	at com.liferay.portal.kernel.portlet.LiferayPortlet.processAction(LiferayPortlet.java:89)
sw360         | 	at com.liferay.portal.kernel.portlet.bridges.mvc.MVCPortlet.processAction(MVCPortlet.java:249)
sw360         | 	at com.liferay.portlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:77)
sw360         | 	at com.liferay.portal.kernel.portlet.PortletFilterUtil.doFilter(PortletFilterUtil.java:50)
sw360         | 	at com.liferay.portal.kernel.servlet.PortletServlet.service(PortletServlet.java:115)
sw360         | 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
sw360         | 	at org.eclipse.equinox.http.servlet.internal.registration.EndpointRegistration.service(EndpointRegistration.java:153)
sw360         | 	at org.eclipse.equinox.http.servlet.internal.servlet.ResponseStateHandler.processRequest(ResponseStateHandler.java:62)
sw360         | 	at org.eclipse.equinox.http.servlet.internal.context.DispatchTargets.doDispatch(DispatchTargets.java:120)
sw360         | 	at org.eclipse.equinox.http.servlet.internal.servlet.RequestDispatcherAdaptor.include(RequestDispatcherAdaptor.java:48)
sw360         | 	at com.liferay.portlet.internal.InvokerPortletImpl.invoke(InvokerPortletImpl.java:571)
sw360         | 	at com.liferay.portlet.internal.InvokerPortletImpl.invokeAction(InvokerPortletImpl.java:611)
sw360         | 	at com.liferay.portlet.internal.InvokerPortletImpl.processAction(InvokerPortletImpl.java:286)
sw360         | 	at com.liferay.portal.monitoring.internal.portlet.MonitoringInvokerPortlet.processAction(MonitoringInvokerPortlet.java:195)
sw360         | 	at com.liferay.portlet.internal.PortletContainerImpl._processAction(PortletContainerImpl.java:521)
sw360         | 	at com.liferay.portlet.internal.PortletContainerImpl.lambda$processAction$0(PortletContainerImpl.java:148)
sw360         | 	at com.liferay.portlet.internal.PortletContainerImpl._preserveGroupIds(PortletContainerImpl.java:425)
sw360         | 	at com.liferay.portlet.internal.PortletContainerImpl.processAction(PortletContainerImpl.java:141)
sw360         | 	at com.liferay.portlet.SecurityPortletContainerWrapper.processAction(SecurityPortletContainerWrapper.java:92)
sw360         | 	at com.liferay.portlet.RestrictPortletContainerWrapper.processAction(RestrictPortletContainerWrapper.java:72)
sw360         | 	at com.liferay.portal.kernel.portlet.PortletContainerUtil.processAction(PortletContainerUtil.java:117)
sw360         | 	at com.liferay.portal.action.LayoutAction.processLayout(LayoutAction.java:347)
sw360         | 	at com.liferay.portal.action.LayoutAction.execute(LayoutAction.java:170)
sw360         | 	at com.liferay.portal.struts.PortalRequestProcessor._process(PortalRequestProcessor.java:408)
sw360         | 	at com.liferay.portal.struts.PortalRequestProcessor.process(PortalRequestProcessor.java:154)
sw360         | 	at com.liferay.portal.internal.servlet.MainServlet.doPost(MainServlet.java:214)
sw360         | 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:660)
sw360         | 	at com.liferay.portal.internal.servlet.MainServlet.service(MainServlet.java:621)
sw360         | 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
sw360         | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
sw360         | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
sw360         | 	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
sw360         | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
sw360         | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
sw360         | 	at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.doFilter(InvokerFilterChain.java:124)
sw360         | 	at com.liferay.portal.kernel.servlet.BaseFilter.processFilter(BaseFilter.java:147)
sw360         | 	at com.liferay.portal.upload.servlet.request.filter.internal.UploadServletRequestFilter.processFilter(UploadServletRequestFilter.java:120)
sw360         | 	at com.liferay.portal.kernel.servlet.BaseFilter.doFilter(BaseFilter.java:49)
sw360         | 	at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.processDoFilter(InvokerFilterChain.java:215)
sw360         | 	at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.doFilter(InvokerFilterChain.java:116)
sw360         | 	at com.liferay.portal.remote.cors.internal.servlet.filter.PortalCORSServletFilter.processFilter(PortalCORSServletFilter.java:232)
sw360         | 	at com.liferay.portal.kernel.servlet.BaseFilter.doFilter(BaseFilter.java:49)
sw360         | 	at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.processDoFilter(InvokerFilterChain.java:215)
sw360         | 	at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.doFilter(InvokerFilterChain.java:116)
sw360         | 	at com.liferay.portal.servlet.filters.password.modified.PasswordModifiedFilter.processFilter(PasswordModifiedFilter.java:62)
sw360         | 	at com.liferay.portal.kernel.servlet.BaseFilter.doFilter(BaseFilter.java:49)
sw360         | 	at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.processDoFilter(InvokerFilterChain.java:215)
sw360         | 	at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.doFilter(InvokerFilterChain.java:116)
sw360         | 	at com.liferay.portal.servlet.filters.lockout.LockoutFilter.processFilter(LockoutFilter.java:58)
sw360         | 	at com.liferay.portal.kernel.servlet.BaseFilter.doFilter(BaseFilter.java:49)
sw360         | 	at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.processDoFilter(InvokerFilterChain.java:215)
sw360         | 	at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.doFilter(InvokerFilterChain.java:116)
sw360         | 	at com.liferay.portal.kernel.servlet.BaseFilter.processFilter(BaseFilter.java:147)
sw360         | 	at com.liferay.portal.servlet.filters.secure.BaseAuthFilter.processFilter(BaseAuthFilter.java:340)
sw360         | 	at com.liferay.portal.kernel.servlet.BaseFilter.doFilter(BaseFilter.java:49)
sw360         | 	at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.processDoFilter(InvokerFilterChain.java:215)
sw360         | 	at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.doFilter(InvokerFilterChain.java:116)
sw360         | 	at com.liferay.portal.kernel.servlet.BaseFilter.processFilter(BaseFilter.java:147)
sw360         | 	at com.liferay.portal.monitoring.internal.servlet.filter.MonitoringFilter.processFilter(MonitoringFilter.java:183)
sw360         | 	at com.liferay.portal.kernel.servlet.BaseFilter.doFilter(BaseFilter.java:49)
sw360         | 	at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.processDoFilter(InvokerFilterChain.java:215)
sw360         | 	at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.doFilter(InvokerFilterChain.java:116)
sw360         | 	at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilter.doFilter(InvokerFilter.java:104)
sw360         | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
sw360         | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
sw360         | 	at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:712)
sw360         | 	at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:459)
sw360         | 	at org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:384)
sw360         | 	at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:312)
sw360         | 	at com.liferay.friendly.url.internal.servlet.FriendlyURLServlet.service(FriendlyURLServlet.java:468)
sw360         | 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
sw360         | 	at com.liferay.portal.servlet.ServletAdapter.service(ServletAdapter.java:99)
sw360         | 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
sw360         | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
sw360         | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
sw360         | 	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
sw360         | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
sw360         | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
sw360         | 	at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.doFilter(InvokerFilterChain.java:124)
sw360         | 	at com.liferay.portal.kernel.servlet.BaseFilter.processFilter(BaseFilter.java:147)
sw360         | 	at com.liferay.portal.upload.servlet.request.filter.internal.UploadServletRequestFilter.processFilter(UploadServletRequestFilter.java:120)
sw360         | 	at com.liferay.portal.kernel.servlet.BaseFilter.doFilter(BaseFilter.java:49)
sw360         | 	at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.processDoFilter(InvokerFilterChain.java:215)
sw360         | 	at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.doFilter(InvokerFilterChain.java:116)
sw360         | 	at com.liferay.portal.remote.cors.internal.servlet.filter.PortalCORSServletFilter.processFilter(PortalCORSServletFilter.java:232)
sw360         | 	at com.liferay.portal.kernel.servlet.BaseFilter.doFilter(BaseFilter.java:49)
sw360         | 	at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.processDoFilter(InvokerFilterChain.java:215)
sw360         | 	at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.doFilter(InvokerFilterChain.java:116)
sw360         | 	at com.liferay.portal.kernel.servlet.BaseFilter.processFilter(BaseFilter.java:147)
sw360         | 	at com.liferay.portal.servlet.filters.i18n.I18nFilter.processFilter(I18nFilter.java:368)
sw360         | 	at com.liferay.portal.kernel.servlet.BaseFilter.doFilter(BaseFilter.java:49)
sw360         | 	at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.processDoFilter(InvokerFilterChain.java:215)
sw360         | 	at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.doFilter(InvokerFilterChain.java:116)
sw360         | 	at com.liferay.portal.servlet.filters.password.modified.PasswordModifiedFilter.processFilter(PasswordModifiedFilter.java:62)
sw360         | 	at com.liferay.portal.kernel.servlet.BaseFilter.doFilter(BaseFilter.java:49)
sw360         | 	at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.processDoFilter(InvokerFilterChain.java:215)
sw360         | 	at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.doFilter(InvokerFilterChain.java:116)
sw360         | 	at com.liferay.portal.servlet.filters.lockout.LockoutFilter.processFilter(LockoutFilter.java:58)
sw360         | 	at com.liferay.portal.kernel.servlet.BaseFilter.doFilter(BaseFilter.java:49)
sw360         | 	at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.processDoFilter(InvokerFilterChain.java:215)
sw360         | 	at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.doFilter(InvokerFilterChain.java:116)
sw360         | 	at com.liferay.portal.kernel.servlet.BaseFilter.processFilter(BaseFilter.java:147)
sw360         | 	at com.liferay.portal.servlet.filters.secure.BaseAuthFilter.processFilter(BaseAuthFilter.java:340)
sw360         | 	at com.liferay.portal.kernel.servlet.BaseFilter.doFilter(BaseFilter.java:49)
sw360         | 	at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.processDoFilter(InvokerFilterChain.java:215)
sw360         | 	at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.doFilter(InvokerFilterChain.java:116)
sw360         | 	at com.liferay.portal.kernel.servlet.BaseFilter.processFilter(BaseFilter.java:147)
sw360         | 	at com.liferay.portal.servlet.filters.etag.ETagFilter.processFilter(ETagFilter.java:87)
sw360         | 	at com.liferay.portal.kernel.servlet.BaseFilter.doFilter(BaseFilter.java:49)
sw360         | 	at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.processDoFilter(InvokerFilterChain.java:215)
sw360         | 	at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.doFilter(InvokerFilterChain.java:116)
sw360         | 	at com.liferay.portal.kernel.servlet.BaseFilter.processFilter(BaseFilter.java:147)
sw360         | 	at com.liferay.portal.servlet.filters.autologin.AutoLoginFilter.processFilter(AutoLoginFilter.java:264)
sw360         | 	at com.liferay.portal.kernel.servlet.BaseFilter.doFilter(BaseFilter.java:49)
sw360         | 	at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.processDoFilter(InvokerFilterChain.java:215)
sw360         | 	at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.doFilter(InvokerFilterChain.java:116)
sw360         | 	at com.liferay.portal.kernel.servlet.BaseFilter.processFilter(BaseFilter.java:147)
sw360         | 	at com.liferay.portal.sharepoint.SharepointFilter.processFilter(SharepointFilter.java:88)
sw360         | 	at com.liferay.portal.kernel.servlet.BaseFilter.doFilter(BaseFilter.java:49)
sw360         | 	at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.processDoFilter(InvokerFilterChain.java:215)
sw360         | 	at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.doFilter(InvokerFilterChain.java:116)
sw360         | 	at com.liferay.portal.kernel.servlet.BaseFilter.processFilter(BaseFilter.java:147)
sw360         | 	at com.liferay.portal.servlet.filters.virtualhost.VirtualHostFilter.processFilter(VirtualHostFilter.java:250)
sw360         | 	at com.liferay.portal.kernel.servlet.BaseFilter.doFilter(BaseFilter.java:49)
sw360         | 	at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.processDoFilter(InvokerFilterChain.java:215)
sw360         | 	at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.doFilter(InvokerFilterChain.java:116)
sw360         | 	at com.liferay.portal.kernel.servlet.BaseFilter.processFilter(BaseFilter.java:147)
sw360         | 	at com.liferay.portal.monitoring.internal.servlet.filter.MonitoringFilter.processFilter(MonitoringFilter.java:183)
sw360         | 	at com.liferay.portal.kernel.servlet.BaseFilter.doFilter(BaseFilter.java:49)
sw360         | 	at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.processDoFilter(InvokerFilterChain.java:215)
sw360         | 	at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.doFilter(InvokerFilterChain.java:116)
sw360         | 	at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.processDirectCallFilter(InvokerFilterChain.java:196)
sw360         | 	at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.doFilter(InvokerFilterChain.java:99)
sw360         | 	at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.processDirectCallFilter(InvokerFilterChain.java:196)
sw360         | 	at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.doFilter(InvokerFilterChain.java:99)
sw360         | 	at org.tuckey.web.filters.urlrewrite.RuleChain.handleRewrite(RuleChain.java:176)
sw360         | 	at org.tuckey.web.filters.urlrewrite.RuleChain.doRules(RuleChain.java:145)
sw360         | 	at org.tuckey.web.filters.urlrewrite.UrlRewriter.processRequest(UrlRewriter.java:92)
sw360         | 	at org.tuckey.web.filters.urlrewrite.UrlRewriteFilter.doFilter(UrlRewriteFilter.java:389)
sw360         | 	at com.liferay.portal.servlet.filters.urlrewrite.UrlRewriteFilter.processFilter(UrlRewriteFilter.java:65)
sw360         | 	at com.liferay.portal.kernel.servlet.BaseFilter.doFilter(BaseFilter.java:49)
sw360         | 	at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.processDoFilter(InvokerFilterChain.java:215)
sw360         | 	at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.doFilter(InvokerFilterChain.java:116)
sw360         | 	at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.processDirectCallFilter(InvokerFilterChain.java:175)
sw360         | 	at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.doFilter(InvokerFilterChain.java:99)
sw360         | 	at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.processDirectCallFilter(InvokerFilterChain.java:175)
sw360         | 	at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.doFilter(InvokerFilterChain.java:99)
sw360         | 	at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.processDirectCallFilter(InvokerFilterChain.java:196)
sw360         | 	at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.doFilter(InvokerFilterChain.java:99)
sw360         | 	at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilter.doFilter(InvokerFilter.java:104)
sw360         | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
sw360         | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
sw360         | 	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
sw360         | 	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
sw360         | 	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541)
sw360         | 	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
sw360         | 	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
sw360         | 	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
sw360         | 	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
sw360         | 	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:373)
sw360         | 	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
sw360         | 	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
sw360         | 	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1594)
sw360         | 	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
sw360         | 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
sw360         | 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
sw360         | 	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
sw360         | 	at java.base/java.lang.Thread.run(Thread.java:829)
sw360         | Caused by: java.io.UncheckedIOException: java.util.zip.ZipException: zip END header not found
sw360         | 	at com.liferay.portal.zip.ZipReaderImpl.getEntryAsInputStream(ZipReaderImpl.java:147)
sw360         | 	at com.liferay.portal.zip.ZipReaderImpl.getEntryAsByteArray(ZipReaderImpl.java:97)
sw360         | 	at com.liferay.portal.zip.ZipReaderImpl.getEntryAsString(ZipReaderImpl.java:157)
sw360         | 	at com.liferay.exportimport.internal.controller.LayoutImportController.validateFile(LayoutImportController.java:1039)
sw360         | 	at com.liferay.exportimport.internal.controller.LayoutImportController.validateFile(LayoutImportController.java:274)
sw360         | 	at com.liferay.portlet.exportimport.service.impl.ExportImportLocalServiceImpl.validateImportLayoutsFile(ExportImportLocalServiceImpl.java:594)
sw360         | 	... 199 more
sw360         | Caused by: java.util.zip.ZipException: zip END header not found
sw360         | 	at java.base/java.util.zip.ZipFile$Source.zerror(ZipFile.java:1607)
sw360         | 	at java.base/java.util.zip.ZipFile$Source.findEND(ZipFile.java:1497)
sw360         | 	at java.base/java.util.zip.ZipFile$Source.initCEN(ZipFile.java:1504)
sw360         | 	at java.base/java.util.zip.ZipFile$Source.<init>(ZipFile.java:1308)
sw360         | 	at java.base/java.util.zip.ZipFile$Source.get(ZipFile.java:1271)
sw360         | 	at java.base/java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:733)
sw360         | 	at java.base/java.util.zip.ZipFile$CleanableResource.get(ZipFile.java:850)
sw360         | 	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:248)
sw360         | 	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:177)
sw360         | 	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:191)
sw360         | 	at com.liferay.portal.zip.ZipReaderImpl.getEntryAsInputStream(ZipReaderImpl.java:117)
sw360         | 	... 204 more

**Comment by KoukiHama** [comment]
Yes, this is the bug. Please use this one temporarily. 

https://github.com/sw360/sw360vagrant/files/6058097/Private_Pages-7_3_4_GA5.lar.zip

**Comment by yyosioka** [comment]
Thanks for providing the file.
We have confirmed that Private_Pages_7_3_3_GA4.lar can be loaded.
Please provide the file Public_Pages_7_3_GA4.lar as the same event occurs.

**Comment by KoukiHama** [comment]
@yyosioka 
Please try these. I hope one of these works fine.

https://github.com/sw360/sw360vagrant/files/6058095/Public_Pages-7_3_4_GA5.lar.zip

[Public_Pages_7_3_3_GA4.zip](https://github.com/eclipse/sw360/files/8448115/Public_Pages_7_3_3_GA4.zip)

**Comment by yyosioka** [comment]
Thank you for providing the file.
[Public_Pages_7_3_3_GA4.zip](https://github.com/eclipse/sw360/files/8448115/Public_Pages_7_3_3_GA4.zip)
could be loaded.

**Comment by KoukiHama** [comment]
Re-open. If latest code belong to correct lar, this issue would be close.

**Comment by KoukiHama** [comment]
from [chores(upgrade): Upgrade Liferay to 7.4.3.18 GA18](https://github.com/eclipse/sw360/pull/1508/files#top)
#1508

We can import latest lar files now,

**Comment by Sa2shi** [comment]
Hi, I'm trying to import the latest lar files, but the same error is happening. Could you check them?
Thanks.
![image](https://github.com/eclipse-sw360/sw360/assets/28839065/c5d01f29-ffdb-4ee8-8588-d1afa1b2cf42)

I'm following to the instructions below:
https://eclipse.dev/sw360/docs/deployment/legacy/nativeinstall/native-install-sw360-version-17.0.0/#setup-sw360-for-liferay-import-lar-files

**Comment by KoukiHama** [comment]
Hello
Could you tell me how to build sw360 and your sw360 version and  commit id?

**Comment by KoukiHama** [comment]
You follow version17 guide, so if you use latest lar file for sw360 v18 with 17 environment, you may get error. @Sa2shi

**Comment by Sa2shi** [comment]
Hello, @KoukiHama , thank you so much for checking. I built sw360 with the following instructions.
https://github.com/eclipse-sw360/sw360/blob/main/README_DOCKER.md

The sw360 version is sw360-17.0.0-M1, and the commit id is ae997be2.
![image](https://github.com/eclipse-sw360/sw360/assets/28839065/9ace9dd3-eda7-4f59-bd18-5fbf282d5cc1)

I tried the following lar files, and I coud import them at this time, but there is a message "This portlet could not be found. Please redeploy it or remove it from the page.", so I'm wondering why it happens.
https://github.com/eclipse-sw360/sw360/tree/sw360-17.0.0-M1/frontend/configuration

![image](https://github.com/eclipse-sw360/sw360/assets/28839065/6f897e76-6c67-4a28-848a-9c52178871d9)

Thanks and regards,

**Comment by KoukiHama** [comment]
thank you for the info.
I will check it with the commit id.

**Comment by KoukiHama** [comment]
According to your screenshot, you may fail to sw360 due to some reason. I am not sure the reason now, but I will be able to share which commit works fine.

**Comment by Sa2shi** [comment]
@KoukiHama 
Thank you. I tried cleaning up all containers and docker volumes, and built again, then, I could import the lar files, correctly. I appreciate your supports.
