### ISSUE TITLE
Unable to get REST-API token

### ISSUE THREAD

**Issue by yyosioka** [eclipse/sw360#1514]
### Description

When retrieving REST-API token, authentication fails with error 401.
I think I need to define clientId and client-secret somewhere because the log is outputting the following, where and how should I define them?

Log output contents
sw360 | 2022-04-21 04:43:36 WARN CouchDbRepositorySupport:75 - No clients found for clientId <trusted-sw360-client>.

#### How to reproduce

No1 The environment was constructed with reference to the following page.
https://github.com/eclipse/sw360/blob/master/README_DOCKER.md

No2 SW360 is up and running.
docker-compose up

No3 The following command was entered from a Linux terminal.
curl -X POST --user 'trusted-sw360-client:sw360-secret' -d 'grant_type=password&username=admin@sw360.org&password=12345' http://localhost:8080/authorization/oauth/token -k

[response]
{
  "timestamp" : "2022-04-21T04:16:25.714+00:00",
  "status" : 401,
  "error" : "Unauthorized",
  "message" : "Unauthorized",
  "path" : "/authorization/oauth/token"
}.

### Versions
2022/4/7 latest acquisition

#### SW360 logs
couchdb_1     | [notice] 2022-04-21T04:43:36.168285Z nonode@nohost <0.7556.25> 2e339b0760 couchdb:5984 172.18.0.4 admin GET /sw360oauthclients/_design/OAuthClientEntity/_view/byClientId?key=%22trusted-sw360-client%22 200 ok 1
sw360         | 2022-04-21 04:43:36 WARN  CouchDbRepositorySupport:75 - No clients found for clientId <trusted-sw360-client>.

**Comment by KoukiHama** [comment]
How about making token from GUI?
You can get them from Admin ouath client pages.

**Comment by yyosioka** [comment]
![2022-04-21 173240](https://user-images.githubusercontent.com/62535924/164416454-eb241403-9321-45f3-99e5-c2a23aae08b1.png)
This is the screen, right?

I can get the tocken string from the GUI, but it fails when I make other REST-API calls using tockn.

The following is the result of the API call.
xxxxxxxxxxxxxxxxxxx: tocken string from the GUI

curl 'http://localhost:8080/resource/api/vulnerabilities' -i -X GET -H 'Authorization: Bearer xxxxxxxxxxxxxxxxxxx' -H 'Accept: application/hal+json'
HTTP/1.1 401
Cache-Control: no-store
Pragma: no-cache
WWW-Authenticate: Bearer realm="sw360-REST-API", error="invalid_token", error_description="Cannot convert access token to JSON"
X-Content-Type-Options: nosniff
X-XSS-Protection: 1; mode=block
X-Frame-Options: DENY
Content-Type: application/hal+json;charset=UTF-8
Transfer-Encoding: chunked
Date: Thu, 21 Apr 2022 08:35:51 GMT
{"error":"invalid_token","error_description":"Cannot convert access token to JSON"}

**Comment by KoukiHama** [comment]
Could you try "curl" commands with option "-vvv" and show the results ?

**Comment by yyosioka** [comment]
The following is the result of running the "curl" command with the "-vvv" option.

curl -vvv 'http://localhost:8080/resource/api/vulnerabiliti
es' -i -X GET -H 'Authorization: Bearer 3lJAewGhKVWO7kPXtBr4' -H 'Accept: applic
ation/hal+json'
Note: Unnecessary use of -X or --request, GET is already inferred.
*   Trying 127.0.0.1:8080...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 8080 (#0)
> GET /resource/api/vulnerabilities HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/7.68.0
> Authorization: Bearer 3lJAewGhKVWO7kPXtBr4
> Accept: application/hal+json
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 401
HTTP/1.1 401
< Cache-Control: no-store
Cache-Control: no-store
< Pragma: no-cache
Pragma: no-cache
< WWW-Authenticate: Bearer realm="sw360-REST-API", error="invalid_token", error_description="Cannot convert access token to JSON"
WWW-Authenticate: Bearer realm="sw360-REST-API", error="invalid_token", error_description="Cannot convert access token to JSON"
< X-Content-Type-Options: nosniff
X-Content-Type-Options: nosniff
< X-XSS-Protection: 1; mode=block
X-XSS-Protection: 1; mode=block
< X-Frame-Options: DENY
X-Frame-Options: DENY
< Content-Type: application/hal+json;charset=UTF-8
Content-Type: application/hal+json;charset=UTF-8
< Transfer-Encoding: chunked
Transfer-Encoding: chunked
< Date: Thu, 28 Apr 2022 02:21:25 GMT
Date: Thu, 28 Apr 2022 02:21:25 GMT

<
* Connection #0 to host localhost left intact
{"error":"invalid_token","error_description":"Cannot convert access token to JSON"}

**Comment by KoukiHama** [comment]
oh...

looks like no problem. 

I think it is not related to your issue directly, 
but you can try to change the option in /etc/sw360/authroziation/application.yml

Default is false.   if this option become true, your api server may works fine.

https://github.com/eclipse/sw360/blob/e6fd4a55a15781e2a7e4d9020a5cea9f22802390/scripts/docker-config/etc_sw360/authorization/application.yml#L47

**Comment by yyosioka** [comment]
In docker, it is placed as follows.
I modified the relevant settings and restarted docker.
:/app/sw360/tomcat-9.0.33/webapps/authorization/WEB-INF/classe/application.yml

I then tried to access rest-api, but the result is the same.

curl -vvv 'http://localhost:8080/resource/api/vulnerabilities' -i -X GET -H 'Authorization: Bearer HK3x5SgdvbpoTfPtq1Ez' -H 'Accept: application/hal+json'

--------------------------------------------------------------------------------
Note: Unnecessary use of -X or --request, GET is already inferred.
*   Trying 127.0.0.1:8080...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 8080 (#0)
> GET /resource/api/vulnerabilities HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/7.68.0
> Authorization: Bearer HK3x5SgdvbpoTfPtq1Ez
> Accept: application/hal+json
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 401
HTTP/1.1 401
< Cache-Control: no-store
Cache-Control: no-store
< Pragma: no-cache
Pragma: no-cache
< WWW-Authenticate: Bearer realm="sw360-REST-API", error="invalid_token", error_description="Cannot convert access token to JSON"
WWW-Authenticate: Bearer realm="sw360-REST-API", error="invalid_token", error_description="Cannot convert access token to JSON"
< X-Content-Type-Options: nosniff
X-Content-Type-Options: nosniff
< X-XSS-Protection: 1; mode=block
X-XSS-Protection: 1; mode=block
< X-Frame-Options: DENY
X-Frame-Options: DENY
< Content-Type: application/hal+json;charset=UTF-8
Content-Type: application/hal+json;charset=UTF-8
< Transfer-Encoding: chunked
Transfer-Encoding: chunked
< Date: Thu, 28 Apr 2022 07:54:11 GMT
Date: Thu, 28 Apr 2022 07:54:11 GMT

<
* Connection #0 to host localhost left intact
{"error":"invalid_token","error_description":"Cannot convert access token to JSON"}
--------------------------------------------------------------------------------------

**Comment by heliocastro** [comment]
Can  you try this in the console ( you need export SW360_USER and SW360_PW and SW360_HOST:
This are functions, so you can add on your shell

Step1 :

```bash
create_sw360_client_token() {
   SW360_API="${API_ID:-My Read Test}"

   curl -k -s -S \
      --user "${SW360_USER}:${SW360_PW}" \
      --header "Content-Type: application/json" \
      --header "Accept: application/json" \
      -X POST "${SW360_HOST}"/authorization/client-management \
      -d @- <<EOF
{
"description" : "${API_ID}",
"authorities" : [ "BASIC" ],
"scope" : [ "READ" ],
"access_token_validity" : 3600,
"refresh_token_validity" : 3600
}
EOF
}
```

Step 2: (Get SW360_CLIENTID and SW360_SECRET from the step 1)
```bash
sw360_get_token() {
   curl --user "${SW360_CLIENTID}:${SW360_SECRET}" \
      -d 'grant_type=password&username=${SW360_USER}&password=${SW360_PW}' \
      "${SW360_HOST}"/authorization/oauth/token -k
}
```

And step 3: ( get API TOKEN from previous step ):

```bash
sw360_get_data() {

   local apicall
   apicall="${1:-users}"

   curl "${SW360_HOST}/resource/api/$apicall" -k -i -X GET -H "Authorization: Bearer $API_TOKEN" -H 'Accept: 
      application/hal+json'
}
```

So in the end you will need to call **sw360_get_data vulnerabilities**

**Comment by yyosioka** [comment]
Thanks for contacting me. I tried to execute it.
Fails at step2. I would like to know how to solve this problem.

Step 1 was OK.

The following response was returned and client_id and client_secret were obtained.
{
  "description" : "",
  "client_id" : "558ff7ceef3fc79d0f0b4ea5a5001a07",
  "client_secret" : "f315adaa-7be2-412c-baa3-11bd7dd8aaf4",
  "authorities" : [ "BASIC" ],
  "scope" : [ "READ" ],
  "access_token_validity" : 3600,
  "refresh_token_validity" : 3600
}


Executing step2 returns the following error.
{
  "error" : "server_error",
  "error_description" : "Internal Server Error"
}

SW360 log
sw360         | 2022-05-09 18:13:06 ERROR TokenEndpoint:169 - Handling error: IllegalArgumentException, Not enough variable values available to expand 'SW360_USER'
sw360         | java.lang.IllegalArgumentException: Not enough variable values available to expand 'SW360_USER'
sw360         |         at org.springframework.web.util.UriComponents$VarArgsTemplateVariables.getValue(UriComponents.java:367) ~[spring-web-5.1.18.RELEASE.jar:5.1.18.RELEASE]
sw360         |         at org.springframework.web.util.HierarchicalUriComponents$QueryUriTemplateVariables.getValue(HierarchicalUriComponents.java:1066) ~[spring-web-5.1.18.RELEASE.jar:5.1.18.RELEASE]
sw360         |         at org.springframework.web.util.UriComponents.expandUriComponent(UriComponents.java:262) ~[spring-web-5.1.18.RELEASE.jar:5.1.18.RELEASE]
sw360         |         at org.springframework.web.util.HierarchicalUriComponents.lambda$expandQueryParams$5(HierarchicalUriComponents.java:454) ~[spring-web-5.1.18.RELEASE.jar:5.1.18.RELEASE]
sw360         |         at java.util.Map.forEach(Map.java:661) ~[?:?]
sw360         |         at org.springframework.web.util.HierarchicalUriComponents.expandQueryParams(HierarchicalUriComponents.java:450) ~[spring-web-5.1.18.RELEASE.jar:5.1.18.RELEASE]
sw360         |         at org.springframework.web.util.HierarchicalUriComponents.expandInternal(HierarchicalUriComponents.java:440) ~[spring-web-5.1.18.RELEASE.jar:5.1.18.RELEASE]
sw360         |         at org.springframework.web.util.HierarchicalUriComponents.expandInternal(HierarchicalUriComponents.java:51) ~[spring-web-5.1.18.RELEASE.jar:5.1.18.RELEASE]
sw360         |         at org.springframework.web.util.UriComponents.expand(UriComponents.java:172) ~[spring-web-5.1.18.RELEASE.jar:5.1.18.RELEASE]
sw360         |         at org.springframework.web.util.DefaultUriBuilderFactory$DefaultUriBuilder.build(DefaultUriBuilderFactory.java:386) ~[spring-web-5.1.18.RELEASE.jar:5.1.18.RELEASE]
sw360         |         at org.springframework.web.util.DefaultUriBuilderFactory.expand(DefaultUriBuilderFactory.java:155) ~[spring-web-5.1.18.RELEASE.jar:5.1.18.RELEASE]
sw360         |         at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:667) ~[spring-web-5.1.18.RELEASE.jar:5.1.18.RELEASE]
sw360         |         at org.springframework.web.client.RestTemplate.postForEntity(RestTemplate.java:443) ~[spring-web-5.1.18.RELEASE.jar:5.1.18.RELEASE]
sw360         |         at org.eclipse.sw360.rest.authserver.security.basicauth.Sw360LiferayAuthenticationProvider.liferayAuthCheckRequest(Sw360LiferayAuthenticationProvider.java:127) ~[classes/:?]
sw360         |         at org.eclipse.sw360.rest.authserver.security.basicauth.Sw360LiferayAuthenticationProvider.isAuthorized(Sw360LiferayAuthenticationProvider.java:106) ~[classes/:?]
sw360         |         at org.eclipse.sw360.rest.authserver.security.basicauth.Sw360LiferayAuthenticationProvider.authenticate(Sw360LiferayAuthenticationProvider.java:87) ~[classes/:?]
sw360         |         at org.springframework.security.authentication.ProviderManager.authenticate(ProviderManager.java:175) ~[spring-security-core-5.1.12.RELEASE.jar:5.1.12.RELEASE]
sw360         |         at org.springframework.security.authentication.ProviderManager.authenticate(ProviderManager.java:200) ~[spring-security-core-5.1.12.RELEASE.jar:5.1.12.RELEASE]
sw360         |         at org.springframework.security.config.annotation.web.configuration.WebSecurityConfigurerAdapter$AuthenticationManagerDelegator.authenticate(WebSecurityConfigurerAdapter.java:514) ~[spring-security-config-5.1.12.RELEASE.jar:5.1.12.RELEASE]
sw360         |         at org.springframework.security.oauth2.provider.password.ResourceOwnerPasswordTokenGranter.getOAuth2Authentication(ResourceOwnerPasswordTokenGranter.java:71) ~[spring-security-oauth2-2.3.8.RELEASE.jar:?]
sw360         |         at org.springframework.security.oauth2.provider.token.AbstractTokenGranter.getAccessToken(AbstractTokenGranter.java:72) ~[spring-security-oauth2-2.3.8.RELEASE.jar:?]
sw360         |         at org.springframework.security.oauth2.provider.token.AbstractTokenGranter.grant(AbstractTokenGranter.java:67) ~[spring-security-oauth2-2.3.8.RELEASE.jar:?]
sw360         |         at org.springframework.security.oauth2.provider.CompositeTokenGranter.grant(CompositeTokenGranter.java:38) ~[spring-security-oauth2-2.3.8.RELEASE.jar:?]
sw360         |         at org.springframework.security.oauth2.config.annotation.web.configurers.AuthorizationServerEndpointsConfigurer$4.grant(AuthorizationServerEndpointsConfigurer.java:583) ~[spring-security-oauth2-2.3.8.RELEASE.jar:?]
sw360         |         at org.springframework.security.oauth2.provider.endpoint.TokenEndpoint.postAccessToken(TokenEndpoint.java:132) ~[spring-security-oauth2-2.3.8.RELEASE.jar:?]
sw360         |         at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
sw360         |         at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
sw360         |         at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
sw360         |         at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
sw360         |         at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:190) ~[spring-web-5.1.18.RELEASE.jar:5.1.18.RELEASE]
sw360         |         at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138) ~[spring-web-5.1.18.RELEASE.jar:5.1.18.RELEASE]
sw360         |         at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:105) ~[spring-webmvc-5.1.18.RELEASE.jar:5.1.18.RELEASE]
sw360         |         at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:892) ~[spring-webmvc-5.1.18.RELEASE.jar:5.1.18.RELEASE]
sw360         |         at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:797) ~[spring-webmvc-5.1.18.RELEASE.jar:5.1.18.RELEASE]
sw360         |         at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87) ~[spring-webmvc-5.1.18.RELEASE.jar:5.1.18.RELEASE]
sw360         |         at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1040) [spring-webmvc-5.1.18.RELEASE.jar:5.1.18.RELEASE]
sw360         |         at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:943) [spring-webmvc-5.1.18.RELEASE.jar:5.1.18.RELEASE]
sw360         |         at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006) [spring-webmvc-5.1.18.RELEASE.jar:5.1.18.RELEASE]
sw360         |         at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:909) [spring-webmvc-5.1.18.RELEASE.jar:5.1.18.RELEASE]
sw360         |         at javax.servlet.http.HttpServlet.service(HttpServlet.java:660) [servlet-api.jar:?]
sw360         |         at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883) [spring-webmvc-5.1.18.RELEASE.jar:5.1.18.RELEASE]
sw360         |         at javax.servlet.http.HttpServlet.service(HttpServlet.java:741) [servlet-api.jar:?]
sw360         |         at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231) [catalina.jar:9.0.33]
sw360         |         at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [catalina.jar:9.0.33]
sw360         |         at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53) [tomcat-websocket.jar:9.0.33]
sw360         |         at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [catalina.jar:9.0.33]
sw360         |         at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [catalina.jar:9.0.33]
sw360         |         at org.eclipse.sw360.rest.authserver.security.customheaderauth.Sw360CustomHeaderAuthenticationFilter.doFilter(Sw360CustomHeaderAuthenticationFilter.java:146) [classes/:?]
sw360         |         at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [catalina.jar:9.0.33]
sw360         |         at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [catalina.jar:9.0.33]
sw360         |         at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:320) [spring-security-web-5.1.12.RELEASE.jar:5.1.12.RELEASE]
sw360         |         at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:127) [spring-security-web-5.1.12.RELEASE.jar:5.1.12.RELEASE]
sw360         |         at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:91) [spring-security-web-5.1.12.RELEASE.jar:5.1.12.RELEASE]
sw360         |         at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334) [spring-security-web-5.1.12.RELEASE.jar:5.1.12.RELEASE]
sw360         |         at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:119) [spring-security-web-5.1.12.RELEASE.jar:5.1.12.RELEASE]
sw360         |         at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334) [spring-security-web-5.1.12.RELEASE.jar:5.1.12.RELEASE]
sw360         |         at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:137) [spring-security-web-5.1.12.RELEASE.jar:5.1.12.RELEASE]
sw360         |         at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334) [spring-security-web-5.1.12.RELEASE.jar:5.1.12.RELEASE]
sw360         |         at org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:111) [spring-security-web-5.1.12.RELEASE.jar:5.1.12.RELEASE]
sw360         |         at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334) [spring-security-web-5.1.12.RELEASE.jar:5.1.12.RELEASE]
sw360         |         at org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:170) [spring-security-web-5.1.12.RELEASE.jar:5.1.12.RELEASE]
sw360         |         at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334) [spring-security-web-5.1.12.RELEASE.jar:5.1.12.RELEASE]
sw360         |         at org.springframework.security.web.savedrequest.RequestCacheAwareFilter.doFilter(RequestCacheAwareFilter.java:63) [spring-security-web-5.1.12.RELEASE.jar:5.1.12.RELEASE]
sw360         |         at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334) [spring-security-web-5.1.12.RELEASE.jar:5.1.12.RELEASE]
sw360         |         at org.springframework.security.web.authentication.www.BasicAuthenticationFilter.doFilterInternal(BasicAuthenticationFilter.java:215) [spring-security-web-5.1.12.RELEASE.jar:5.1.12.RELEASE]
sw360         |         at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) [spring-web-5.1.18.RELEASE.jar:5.1.18.RELEASE]
sw360         |         at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334) [spring-security-web-5.1.12.RELEASE.jar:5.1.12.RELEASE]
sw360         |         at org.eclipse.sw360.rest.authserver.security.customheaderauth.Sw360CustomHeaderAuthenticationFilter.doFilter(Sw360CustomHeaderAuthenticationFilter.java:146) [classes/:?]
sw360         |         at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334) [spring-security-web-5.1.12.RELEASE.jar:5.1.12.RELEASE]
sw360         |         at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:116) [spring-security-web-5.1.12.RELEASE.jar:5.1.12.RELEASE]
sw360         |         at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334) [spring-security-web-5.1.12.RELEASE.jar:5.1.12.RELEASE]
sw360         |         at org.springframework.security.web.header.HeaderWriterFilter.doFilterInternal(HeaderWriterFilter.java:74) [spring-security-web-5.1.12.RELEASE.jar:5.1.12.RELEASE]
sw360         |         at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) [spring-web-5.1.18.RELEASE.jar:5.1.18.RELEASE]
sw360         |         at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334) [spring-security-web-5.1.12.RELEASE.jar:5.1.12.RELEASE]
sw360         |         at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:105) [spring-security-web-5.1.12.RELEASE.jar:5.1.12.RELEASE]
sw360         |         at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334) [spring-security-web-5.1.12.RELEASE.jar:5.1.12.RELEASE]
sw360         |         at org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:56) [spring-security-web-5.1.12.RELEASE.jar:5.1.12.RELEASE]
sw360         |         at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) [spring-web-5.1.18.RELEASE.jar:5.1.18.RELEASE]
sw360         |         at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334) [spring-security-web-5.1.12.RELEASE.jar:5.1.12.RELEASE]
sw360         |         at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:215) [spring-security-web-5.1.12.RELEASE.jar:5.1.12.RELEASE]
sw360         |         at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:178) [spring-security-web-5.1.12.RELEASE.jar:5.1.12.RELEASE]
sw360         |         at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:358) [spring-web-5.1.18.RELEASE.jar:5.1.18.RELEASE]
sw360         |         at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:271) [spring-web-5.1.18.RELEASE.jar:5.1.18.RELEASE]
sw360         |         at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [catalina.jar:9.0.33]
sw360         |         at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [catalina.jar:9.0.33]
sw360         |         at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100) [spring-web-5.1.18.RELEASE.jar:5.1.18.RELEASE]
sw360         |         at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) [spring-web-5.1.18.RELEASE.jar:5.1.18.RELEASE]
sw360         |         at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [catalina.jar:9.0.33]
sw360         |         at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [catalina.jar:9.0.33]
sw360         |         at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93) [spring-web-5.1.18.RELEASE.jar:5.1.18.RELEASE]
sw360         |         at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) [spring-web-5.1.18.RELEASE.jar:5.1.18.RELEASE]
sw360         |         at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [catalina.jar:9.0.33]
sw360         |         at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [catalina.jar:9.0.33]
sw360         |         at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:94) [spring-web-5.1.18.RELEASE.jar:5.1.18.RELEASE]
sw360         |         at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) [spring-web-5.1.18.RELEASE.jar:5.1.18.RELEASE]
sw360         |         at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [catalina.jar:9.0.33]
sw360         |         at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [catalina.jar:9.0.33]
sw360         |         at org.springframework.boot.web.servlet.support.ErrorPageFilter.doFilter(ErrorPageFilter.java:128) [spring-boot-2.1.17.RELEASE.jar:2.1.17.RELEASE]
sw360         |         at org.springframework.boot.web.servlet.support.ErrorPageFilter.access$000(ErrorPageFilter.java:66) [spring-boot-2.1.17.RELEASE.jar:2.1.17.RELEASE]
sw360         |         at org.springframework.boot.web.servlet.support.ErrorPageFilter$1.doFilterInternal(ErrorPageFilter.java:103) [spring-boot-2.1.17.RELEASE.jar:2.1.17.RELEASE]
sw360         |         at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) [spring-web-5.1.18.RELEASE.jar:5.1.18.RELEASE]
sw360         |         at org.springframework.boot.web.servlet.support.ErrorPageFilter.doFilter(ErrorPageFilter.java:121) [spring-boot-2.1.17.RELEASE.jar:2.1.17.RELEASE]
sw360         |         at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [catalina.jar:9.0.33]
sw360         |         at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [catalina.jar:9.0.33]
sw360         |         at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201) [spring-web-5.1.18.RELEASE.jar:5.1.18.RELEASE]
sw360         |         at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) [spring-web-5.1.18.RELEASE.jar:5.1.18.RELEASE]
sw360         |         at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [catalina.jar:9.0.33]
sw360         |         at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [catalina.jar:9.0.33]
sw360         |         at org.eclipse.sw360.rest.common.Sw360CORSFilter.doFilter(Sw360CORSFilter.java:56) [rest-common-15.1.0-SNAPSHOT.jar:?]
sw360         |         at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [catalina.jar:9.0.33]
sw360         |         at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [catalina.jar:9.0.33]
sw360         |         at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202) [catalina.jar:9.0.33]
sw360         |         at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96) [catalina.jar:9.0.33]
sw360         |         at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541) [catalina.jar:9.0.33]
sw360         |         at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139) [catalina.jar:9.0.33]
sw360         |         at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92) [catalina.jar:9.0.33]
sw360         |         at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74) [catalina.jar:9.0.33]
sw360         |         at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343) [catalina.jar:9.0.33]
sw360         |         at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:373) [tomcat-coyote.jar:9.0.33]
sw360         |         at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65) [tomcat-coyote.jar:9.0.33]
sw360         |         at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868) [tomcat-coyote.jar:9.0.33]
sw360         |         at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1594) [tomcat-coyote.jar:9.0.33]
sw360         |         at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat-coyote.jar:9.0.33]
sw360         |         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
sw360         |         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
sw360         |         at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-util.jar:9.0.33]
sw360         |         at java.lang.Thread.run(Thread.java:829) [?:?]

**Comment by yyosioka** [comment]
There seems to be a minor error in the description of sw360_get_token().
The shell variable should be enclosed in " instead of ' because it needs to be expanded.

sw360_get_token() {
   curl --user "${SW360_CLIENTID}:${SW360_SECRET}" \
      -d 'grant_type=password&username=${SW360_USER}&password=${SW360_PW}' \
      "${SW360_HOST}"/authorization/oauth/token -k
}

・After correction
sw360_get_token() {
   curl --user "${SW360_CLIENTID}:${SW360_SECRET}" \
      -d "grant_type=password&username=${SW360_USER}&password=${SW360_PW}" \
      "${SW360_HOST}"/authorization/oauth/token -k
}

**Comment by yyosioka** [comment]
Fixed sw360_get_token().
By modifying it, step3 could also be executed, so this case is closed.

**Comment by heliocastro** [comment]
I'm really happy that i could help.
Thanks for point out the error.
