### ISSUE TITLE
Allow license selection to be saved for the project

### ISSUE THREAD

**Issue by maierthomas** [eclipse/sw360#152]
<a href="https://github.com/lepokle"><img src="https://avatars1.githubusercontent.com/u/499823?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [lepokle](https://github.com/lepokle)**
_Monday Oct 02, 2017 at 08:18 GMT_
_Originally opened as https://github.com/sw360/sw360portal/issues/604_

----

Split from #581 

 - At clearing status there is an additional button next to fossology
- This shall bring a pop up which display the files available (and the file from an uploaded of the same org preselected as it is already)
- Then once one or more files are selected, the resulting licence set can be adjusted only for releases directly bound to the project, for releases of a subproject, editing the referring subproject is necessary. (in the generation UI, this could be overwritten one time / temporary anyway)

**Comment by mcjaeger** [comment]
is already in.
