### ISSUE TITLE
Unable to export clearing status spreadsheet when there are many releases

### ISSUE THREAD

**Issue by maierthomas** [eclipse/sw360#155]
<a href="https://github.com/tngraf"><img src="https://avatars1.githubusercontent.com/u/1225388?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [tngraf](https://github.com/tngraf)**
_Thursday Oct 05, 2017 at 07:11 GMT_
_Originally opened as https://github.com/sw360/sw360portal/issues/609_

----

When there are many releases in a project (more than 100, see project 'Siv* Vie*'), then the "Export Spreadsheet" is overwritten by the page selectors (Previous, 1,2,3..., Next) and can't get pressed.
See attached screenshot:

**Comment by mcjaeger** [comment]
Tested with a project 190 releases now ..
