### ISSUE TITLE
Creation date for project release relation

### ISSUE THREAD

**Issue by maierthomas** [eclipse/sw360#158]
<a href="https://github.com/mcjaeger"><img src="https://avatars1.githubusercontent.com/u/3418977?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [mcjaeger](https://github.com/mcjaeger)**
_Thursday Oct 05, 2017 at 12:54 GMT_
_Originally opened as https://github.com/sw360/sw360portal/issues/612_

----

Actually, there is the process need to capture changes in the project clearing status. More in detail, it is when the project clearing state is set to closed.

Maybe it could be captured when the overall versioning / change history is added.

**Comment by nutanv1contr** [comment]
(After discussion) we should display modified by and modified at(date only).

**Comment by mcjaeger** [comment]
there is change log and it covers the project release relation
