### ISSUE TITLE
New UI to edit attachments till needs some improvement

### ISSUE THREAD

**Issue by maierthomas** [eclipse/sw360#159]
<a href="https://github.com/tngraf"><img src="https://avatars1.githubusercontent.com/u/1225388?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [tngraf](https://github.com/tngraf)**
_Friday Oct 06, 2017 at 06:30 GMT_
_Originally opened as https://github.com/sw360/sw360portal/issues/614_

----

I now that you've changed the UI to edit attachments to give user a better overview.
Unfortunately this display of the user name is a little bit strange, see attached screenshot.
Maybe you could place name and date in a row ABOVE type and comment...
![2017-10-06 08_16_18-components - sw360](https://user-images.githubusercontent.com/1225388/31265728-936df686-aa70-11e7-840d-38c3d1667fad.jpg)

**Comment by maierthomas** [comment]
<a href="https://github.com/mcjaeger"><img src="https://avatars1.githubusercontent.com/u/3418977?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [mcjaeger](https://github.com/mcjaeger)**
_Tuesday Oct 10, 2017 at 15:36 GMT_

----

@tngraf could you please have a look at this ticket and see if this solves your issue?

https://github.com/sw360/sw360portal/issues/569

**Comment by maierthomas** [comment]
<a href="https://github.com/tngraf"><img src="https://avatars1.githubusercontent.com/u/1225388?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [tngraf](https://github.com/tngraf)**
_Wednesday Oct 11, 2017 at 09:33 GMT_

----

No it does not, sorry.
I understand that if get problems when we have a table row with too many columns. In order not to scroll you have line breaks. 
When I clear the cache (!) there are no mor eline breaks, but even with a brwose wdth of 1400px I can only see the first 4 characters of the name.
Again, clearly separating the information into two lines might solve the issue.

**Comment by mcjaeger** [comment]
It seems to be solved now 

![image](https://user-images.githubusercontent.com/3418977/42158349-7490c51e-7df0-11e8-9b81-1ce085ac1c0e.png)
