### ISSUE TITLE
Add a banner for broadcast messages

### ISSUE THREAD

**Issue by rudra-superrr** [eclipse/sw360#1595]
### Description

It will be nice to have a banner on SW360.
It can be used to put broadcast messages, like planned maintenance of the server.

**Comment by KoukiHama** [comment]
#1559 is same?

**Comment by rudra-superrr** [comment]
yes, it's same.
Right now it is basically for planned maintenance date and time. In future we can use for other things also.
Will push the code by tomorrow.

**Comment by KoukiHama** [comment]
Revert "feat(ui): Add banner to broadcast messages" #1618
