### ISSUE TITLE
Prevent name clashes when importing from bdp

### ISSUE THREAD

**Issue by maierthomas** [eclipse/sw360#160]
<a href="https://github.com/bs-jokri"><img src="https://avatars2.githubusercontent.com/u/13886571?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [bs-jokri](https://github.com/bs-jokri)**
_Monday Oct 09, 2017 at 10:49 GMT_
_Originally opened as https://github.com/sw360/sw360portal/issues/615_

----

_From @maxhbr on December 16, 2015 8:31_

# Problem:

try to import a license from bdp which **"looks like"** a license in SW360. **Should they be merged?** This problem also appears with other elements, like projects, releases, components.

**"looks like"** might mean:
- the shortnames are identical
- the fullnames match

but
- the strings, which represent the license texts are not identical
# Possible solutions:
- use a prefix (like `bdp:`) to mark imported fields (like shortname, fullname,...)
- add a field `bdpId` (to `License`, `Release`, `Project`,...) to track which components are imported by bdp and use only that data for comparing (partially done in PRs #48 and #39)
  - Problem: which `bdpId` should one use for a component in SW360?

_Copied from original issue: bsinno/sw360#50_

**Comment by maierthomas** [comment]
<a href="https://github.com/bs-jokri"><img src="https://avatars2.githubusercontent.com/u/13886571?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [bs-jokri](https://github.com/bs-jokri)**
_Monday Oct 09, 2017 at 10:49 GMT_

----

Any response required from my side?

**Comment by maierthomas** [comment]
<a href="https://github.com/bs-jokri"><img src="https://avatars2.githubusercontent.com/u/13886571?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [bs-jokri](https://github.com/bs-jokri)**
_Monday Oct 09, 2017 at 10:49 GMT_

----

_From @maxhbr on December 16, 2015 13:50_

@bs-jokri: I don't think that a response is required at the moment. But in the near future we have to discuss, under which conditions
- a **bdp** project is the same as a existing **SW360** project (same name?)
- a **bdp** license is the same as a existing **SW360** license (fullname and shortname are not enougth. Suggested policy: remember  bdpId` and match on that)
- ...

**There is also the problem, that** matching Components will not be easy, since from protex we get a name of the form

```
name = "$Vendor $ComponenenName"
```

but for the SW360 world we would need

```
vendor = "$Vendor"
name = $ComponentName
```

**Comment by maierthomas** [comment]
<a href="https://github.com/bs-jokri"><img src="https://avatars2.githubusercontent.com/u/13886571?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [bs-jokri](https://github.com/bs-jokri)**
_Monday Oct 09, 2017 at 10:49 GMT_

----

@maximilianhuber @heydenreich What should we do about that. At the moment we have circumvent this problem by just creating new projects, components, licenses. Maybe we have to tackle this again, when we start working on the merge feature.

**Comment by maierthomas** [comment]
<a href="https://github.com/bs-jokri"><img src="https://avatars2.githubusercontent.com/u/13886571?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [bs-jokri](https://github.com/bs-jokri)**
_Monday Oct 09, 2017 at 10:49 GMT_

----

_From @maxhbr on April 28, 2017 6:0_

the mentioned merge feature is #265

**Comment by maierthomas** [comment]
<a href="https://github.com/bs-jokri"><img src="https://avatars2.githubusercontent.com/u/13886571?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [bs-jokri](https://github.com/bs-jokri)**
_Monday Oct 09, 2017 at 10:49 GMT_

----

epic #426

**Comment by blaumeiser-at-bosch** [comment]
Obsolete
