### ISSUE TITLE
Request to improve the function of API to delete vulnerability information

### ISSUE THREAD

**Issue by chanrai** [eclipse/sw360#1606]
[//]: # (Copyright Siemens AG, 2021. Part of the SW360 Portal Project)
[//]: # (This program and the accompanying materials are made)
[//]: # (available under the terms of the Eclipse Public License 2.0)
[//]: # (which is available at https://www.eclipse.org/legal/epl-2.0/)
[//]: # (SPDX-License-Identifier: EPL-2.0)

### Description

No return value when deleting vulnerability information via API.

```
HTTP/1.1 200
X-Content-Type-Options: nosniff
X-XSS-Protection: 1; mode=block
Cache-Control: no-cache, no-store, max-age=0, must-revalidate
Pragma: no-cache
Expires: 0
X-Frame-Options: DENY
Transfer-Encoding: chunked
Date: Wed, 13 Apr 2022 05:34:35 GMT
```
#### Steps followed and expected result

In the case of successful deletion of the component/Release, 200 was returned as shown below, so I hope to correct it to the same specification.

```
[ {  
　　　"resourceId" : "d3cbcf1eb3855529d1287e87f90e01ff", 
　　　 "status" : 200
} ]
```

**Comment by tienlee** [comment]
I will check and improve this API
