### ISSUE TITLE
The plugin `ldapOrganizationMappingExt` is currently not able to work with mutliple organizations of an user

### ISSUE THREAD

**Issue by maierthomas** [eclipse/sw360#161]
<a href="https://github.com/bs-jokri"><img src="https://avatars2.githubusercontent.com/u/13886571?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [bs-jokri](https://github.com/bs-jokri)**
_Monday Oct 09, 2017 at 10:51 GMT_
_Originally opened as https://github.com/sw360/sw360portal/issues/617_

----

_From @maxhbr on December 15, 2016 10:41_

The plugin currently removes currently all but one organizations of an user.

_Copied from original issue: bsinno/sw360#377_

**Comment by maierthomas** [comment]
<a href="https://github.com/bs-jokri"><img src="https://avatars2.githubusercontent.com/u/13886571?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [bs-jokri](https://github.com/bs-jokri)**
_Monday Oct 09, 2017 at 10:51 GMT_

----

@bodet what should we do with this?

**Comment by maierthomas** [comment]
<a href="https://github.com/mcjaeger"><img src="https://avatars1.githubusercontent.com/u/3418977?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [mcjaeger](https://github.com/mcjaeger)**
_Wednesday Nov 22, 2017 at 11:56 GMT_

----

Maybe consider this being also an issue for this project or for:
https://github.com/sw360/ldapOrganizationMappingExt

... also I think entire sw360 does not support multiple groups per user. As such, maybe we would need to fix this in sw360 first (I was also not finding an issue for this)

**Comment by blaumeiser-at-bosch** [comment]
Obsolete
