### ISSUE TITLE
The REST API for a component name that contains +, but it does not appear in the search results.

### ISSUE THREAD

**Issue by yyosioka** [eclipse/sw360#1612]
### Description

I searched the REST API for a component name that contains +, but it does not appear in the search results.

#### How to reproduce

(e.g.) If a component name such as libstdc6++ contains +, the corresponding component cannot be searched for in Listing by name.

### Versions
Version:15.1.0

**Comment by tienlee** [comment]
I will fix this issue. Please assign it to me.

**Comment by yyosioka** [comment]
Thank you for your response, I will close this case.
