### ISSUE TITLE
The REST API for a release name that contains +, but it does not appear in the search results.

### ISSUE THREAD

**Issue by yyosioka** [eclipse/sw360#1613]
### Description
I searched the REST API for a release name that contains +, but it does not appear in the search results.

#### How to reproduce

If a release name such as libstdc6++ contains +, the corresponding release cannot be searched for in Listing releases by name.

**Comment by tienlee** [comment]
I will fix this issue. Please assign it to me.

**Comment by hoangnt2** [comment]
Hi @yyosioka, To search with special character in parameter like (#, ?, &, +, ...) you must encode your url.
You can replace these character follow below table. In your case '+' must be replace with '%2B'.
![image](https://user-images.githubusercontent.com/94659621/186857738-5212d8f5-fbd1-4ca5-9220-89f240475439.png)

You can find these encode character from this link: https://en.wikipedia.org/wiki/Percent-encoding#Types_of_URI_characters

**Comment by yyosioka** [comment]
Thanks for the comment, I'll check it out.

**Comment by yyosioka** [comment]
Thank you for your response, I will close this case.
