### ISSUE TITLE
SW360 REST-API "Upload attachment to project" does not allow file upload

### ISSUE THREAD

**Issue by yyosioka** [eclipse/sw360#1616]
### Description
SW360 REST-API "Upload attachment to project" does not allow file upload.
Please let me know if I may have made a mistake in the REST-API arguments.

I would like to know how to specify the following arguments.

file :File path of the attachment
If I want to specify "test.txt" in the current folder, is the following correct?
'file=@./test.txt'
Please let me know if there are any restrictions on files or folders that store attachments.

attachmentContentId:Id of attachment info
What ID should I specify for this?
Do I need to pre-number it somewhere?

### Versions
Version:15.1.0

**Comment by tienlee** [comment]
I will fix this issue. Please assign it to me.

**Comment by hoangnt2** [comment]
Hi @yyosioka, your file path is correct, attachmentContentId is auto generated, you can remove it in request.
I tested and could upload file normally. Can you give me your response message and git commit id you are using.

**Comment by yyosioka** [comment]
Thank you for your comment attachmentContentId will be removed.
It is not working yet.
I am using a docker environment following these steps.
https://github.com/eclipse/sw360/blob/main/README_DOCKER.md
git commit ID:c4486690 4ac0471 6aaeb 823a0 c7a5d7cad64b64a

response 
----------------------------------------------------------
HTTP1.1 500
X-Content-Type-Options: nosniff
X-XSS-Protection: 1: mode=block
Cache-Control: no-cache, no-store, max-age=0, must-revalidate
Pragma: no-cache
Expires: 0
Strict-Transport-Security: max-age=31536000  ; includeSubDomains
X-Frame-Options: DENY
Content-type: application/json:charaset=UTF-8
Transfer-Encoding: chunked
Date: Fri, 26 Aug 2022 08:57:48 GMT
Connetion: Close

{"timestamp":"2022-08-26T08:57:48.613736Z","status":500,"error":"Internal Server Error","message"null}

**Comment by hoangnt2** [comment]
@yyosioka, I think your project are having an attachment file with same name

**Comment by yyosioka** [comment]
@hoangnt2  I have changed the name of the file to be attached but the same error is returned.

**Comment by hoangnt2** [comment]
@yyosioka Can you give me your http request and log file of sw360.

**Comment by yyosioka** [comment]
Thank you for your response.
I have updated to sw360-16.0.0-M1 and confirmed that the attachment is stored in the project.
I will close this case.

**Comment by yyosioka** [comment]
Close.
