### ISSUE TITLE
Prevent Collision from Existing and to be Imported Projects when importing from BDP

### ISSUE THREAD

**Issue by maierthomas** [eclipse/sw360#162]
<a href="https://github.com/bs-jokri"><img src="https://avatars2.githubusercontent.com/u/13886571?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [bs-jokri](https://github.com/bs-jokri)**
_Monday Oct 09, 2017 at 10:51 GMT_
_Originally opened as https://github.com/sw360/sw360portal/issues/619_

----

_From @bs-jokri on December 17, 2015 14:26_

As a user I want to be informed if a project I have selected for import is already present in sw360 and will not be imported again. I expect to
1. Be informed before actually starting an import that a project is already available
2. Get the possibility to perform a reimport of a project

At a reimport I want that the old project is deleted and a new project with the content of the BDP project will be created. However, existing components and component releases must not be deleted in sw360 but reused for the new project. Only if components and releases are missing they need to be reimported from protex. If component releases are not linked to the project anymore they must not be deleted and remain in the sw360 database (to not lose clearing status and added meta data).

_Copied from original issue: bsinno/sw360#60_

**Comment by maierthomas** [comment]
<a href="https://github.com/bs-jokri"><img src="https://avatars2.githubusercontent.com/u/13886571?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [bs-jokri](https://github.com/bs-jokri)**
_Monday Oct 09, 2017 at 10:51 GMT_

----

@heydenreich isn't it that the import just stops and says why it is not importing so that the user can delete already existing projects and then do a re-import again. If so, I think we have this behavior implemented and can close this issue.

**Comment by maierthomas** [comment]
<a href="https://github.com/bs-jokri"><img src="https://avatars2.githubusercontent.com/u/13886571?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [bs-jokri](https://github.com/bs-jokri)**
_Monday Oct 09, 2017 at 10:51 GMT_

----

_From @heydenreich on June 28, 2016 12:22_

The import says that it has failed for a specific project. The user could indeed delete this project and reimport. But this issue says that before the import the user should be informed and can decide to overwrite the existing project or not. So, SW360 does not behave yet as the issue describes...

**Comment by maierthomas** [comment]
<a href="https://github.com/bs-jokri"><img src="https://avatars2.githubusercontent.com/u/13886571?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [bs-jokri](https://github.com/bs-jokri)**
_Monday Oct 09, 2017 at 10:51 GMT_

----

_From @maxhbr on April 28, 2017 10:12_

text from duplicate #102:

> When I import a Project from BDP and this project (same project ID) is already present in the sw360 db I would expect that the old project is overwritten with the newly imported. Overwritten means
> 1. already created entries for Component releases will stay present
> 2. component releases not already present will be created
> 3. when importing a project links from the project to component releases will be adjusted to the newly imported project
> 4. Data already added to the project entry in the sw360 database will not be droped

**Comment by maierthomas** [comment]
<a href="https://github.com/bs-jokri"><img src="https://avatars2.githubusercontent.com/u/13886571?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [bs-jokri](https://github.com/bs-jokri)**
_Monday Oct 09, 2017 at 10:51 GMT_

----

#426

**Comment by blaumeiser-at-bosch** [comment]
Obsolete
