### ISSUE TITLE
`NullPointerException` while downloading report

### ISSUE THREAD

**Issue by smrutis1** [eclipse/sw360#1625]
[//]: # (Copyright Siemens AG, 2021. Part of the SW360 Portal Project)
[//]: # (This program and the accompanying materials are made)
[//]: # (available under the terms of the Eclipse Public License 2.0)
[//]: # (which is available at https://www.eclipse.org/legal/epl-2.0/)
[//]: # (SPDX-License-Identifier: EPL-2.0)

### Description

Null pointer exception while downloading the product clearing report. Logs attached.

### Logs

Any logs (if any) generated in

[NullpointerDownloadingReport.txt](https://github.com/eclipse/sw360/files/9443291/NullpointerDownloadingReport.txt)

**Comment by KoukiHama** [comment]
fixed by #1626
