### ISSUE TITLE
Projects / Attachment Usages Filter not working for Attachments of Type SRS (Self-Source)

### ISSUE THREAD

**Issue by akapti** [eclipse/sw360#1628]
[//]: # (Copyright Siemens AG, 2021. Part of the SW360 Portal Project)
[//]: # (This program and the accompanying materials are made)
[//]: # (available under the terms of the Eclipse Public License 2.0)
[//]: # (which is available at https://www.eclipse.org/legal/epl-2.0/)
[//]: # (SPDX-License-Identifier: EPL-2.0)

### Description
Below mentioned project when filtered with 'Without source Attachment' the components with sources also appearing in the filter.

#### How to reproduce

Add attachment of type `SRS` -> `Source file (Self-made)` in release, link that release to project `p1` and use the filter in Attachments Usages tab of project `p1` to filter the releases without source attachments. the release with `SRS` is part of the filter result (which is incorrect).

#### Screenshots
![image](https://user-images.githubusercontent.com/50870174/187366134-d5e96bc4-a325-4035-9637-5f1b9fb58812.png)

**Comment by rudra-superrr** [comment]
Testing was successful.
