### ISSUE TITLE
CveSearch: speed up (if necessary)

### ISSUE THREAD

**Issue by maierthomas** [eclipse/sw360#164]
<a href="https://github.com/bs-jokri"><img src="https://avatars2.githubusercontent.com/u/13886571?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [bs-jokri](https://github.com/bs-jokri)**
_Monday Oct 09, 2017 at 10:53 GMT_
_Originally opened as https://github.com/sw360/sw360portal/issues/621_

----

_From @maxhbr on May 31, 2016 12:6_

There are multiple ways in which one could improve the speed of the cve-search requests, for example
1. Replace REST requests with an (python-) thrift-client running on the cve-search machine
2. Access the MongoDB directly (just give it a regex on the CPEs)
3. Add request to the REST Api, which only looks in the recent changes

_Copied from original issue: bsinno/sw360#166_

**Comment by maierthomas** [comment]
<a href="https://github.com/bs-jokri"><img src="https://avatars2.githubusercontent.com/u/13886571?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [bs-jokri](https://github.com/bs-jokri)**
_Monday Oct 09, 2017 at 10:53 GMT_

----

_From @maxhbr on June 1, 2016 7:2_

Further information about variant **3.** given by @heydenreich in issue #164:

> If CVE-search encounters performance problems, a possibility to improve the performance is to implement thrift-services as e.g.:
> ImportStatus fullUpdateLastMonth();
> ImportStatus fullUpdateLastWeek();
> ImportStatus fullUpdateLastDay();
> which only import the new CVEs from the last period. It's different from the services implemented so far, since the current cve-search services start with a release and search for corresponding vulnerabilities, whereas the above suggested services would have to do the opposite.

**Comment by blaumeiser-at-bosch** [comment]
Obsolete
