### ISSUE TITLE
Add support for enriching vulnerability information with a more detailed request

### ISSUE THREAD

**Issue by maierthomas** [eclipse/sw360#165]
<a href="https://github.com/bs-jokri"><img src="https://avatars2.githubusercontent.com/u/13886571?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [bs-jokri](https://github.com/bs-jokri)**
_Monday Oct 09, 2017 at 10:53 GMT_
_Originally opened as https://github.com/sw360/sw360portal/issues/623_

----

_From @maxhbr on July 5, 2016 7:46_

The cve-search api request `api/cve/:cve` returns a vulnerability with more information, i.e.
- a title,
- clear names for the products in the vulnerable configuration and
- the CAPEC data, which describes ways to use weaknesses and countermeasures.

The backend implementation of this should be easy.

This could be done
- automatically (and asynchronous) when a vulnerability detail page is visited
- automatically in batches 
- on demand, i.e. when a button is pressed

_Copied from original issue: bsinno/sw360#225_

**Comment by maierthomas** [comment]
<a href="https://github.com/bs-jokri"><img src="https://avatars2.githubusercontent.com/u/13886571?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [bs-jokri](https://github.com/bs-jokri)**
_Monday Oct 09, 2017 at 10:53 GMT_

----

_From @maxhbr on April 28, 2017 11:51_

The issue https://github.com/bsinno/sw360/issues/209 is included here.

Text from #209 is:
> At the moment, the CVE ID is used as external id _and_ as title for the vulnerabilities that have been found by CVE search.
>
> Another possibility would be to use titles that are contained in the vulnerability property cveFurtherMetaDataPerSource, which is usually filled for vulnerabilities found by CVE search. Here, meta data of different sources is stored. Some sources also provide a title as part of this meta data. 
>
> The suggestion is to determine a ranking of the sources of the meta data and use the title of the highest ranked source providing a title.

**Comment by blaumeiser-at-bosch** [comment]
Obsolete
