### ISSUE TITLE
Component type is not being set when components are created by importing SBOM

### ISSUE THREAD

**Issue by akapti** [eclipse/sw360#1658]
[//]: # (Copyright Siemens AG, 2021. Part of the SW360 Portal Project)
[//]: # (This program and the accompanying materials are made)
[//]: # (available under the terms of the Eclipse Public License 2.0)
[//]: # (which is available at https://www.eclipse.org/legal/epl-2.0/)
[//]: # (SPDX-License-Identifier: EPL-2.0)

### Description

The existing ( and old SBOM ) import functionality does not set the `Component Type` field in components whenever we import projects / components from SBOM into SW360.

Since Component type is mandatory field in `UI` and `REST` API while creating the component. We should set component type field while importing the component type. maybe the default value can be set as `OSS`.

**Comment by KoukiHama** [comment]
I will do it with tien-san

**Comment by KoukiHama** [comment]
fixed by #1655
