### ISSUE TITLE
License import broken if todos added via GUI are present

### ISSUE THREAD

**Issue by maierthomas** [eclipse/sw360#166]
<a href="https://github.com/bs-jokri"><img src="https://avatars2.githubusercontent.com/u/13886571?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [bs-jokri](https://github.com/bs-jokri)**
_Monday Oct 09, 2017 at 10:54 GMT_
_Originally opened as https://github.com/sw360/sw360portal/issues/625_

----

_From @heydenreich on July 8, 2016 14:48_

Problem:
When manually adding todos via the UI, the todo gets assigned todoId=0. If more than one todo with the same todoId=0 are present in the system, the lics-import of a new license archive crashes.

This problem has been discussed with Siemens, but is not fixed yet. There were several suggestions how to deal with it. The most promising seems to be using the couchdbId as reference in the .lics file and add the todoId "only" as extra property. Then there would be no need to check for uniqueness of todoIds any more.

_Copied from original issue: bsinno/sw360#236_

**Comment by maierthomas** [comment]
<a href="https://github.com/bs-jokri"><img src="https://avatars2.githubusercontent.com/u/13886571?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [bs-jokri](https://github.com/bs-jokri)**
_Monday Oct 09, 2017 at 10:54 GMT_

----

_From @heydenreich on July 8, 2016 14:59_

Other scenarios work fine:
1. _Importing the same lics-archive twice:_ works and nothing changes.
2. _Import a lics archive and then import a lics-archive which contains a license with a shortname/id that is already in the system:_ license is _not_ imported again. Existing license in the database is _not_ modified.
3. _Import a lics archive and then import a lics-archive which contains a new license not in the system as well as licenses that are already in the system:_ new license _is_ imported (with todos, obligations, license type if these are new, too). Modified licenses are _not_ importet.

**Comment by maierthomas** [comment]
<a href="https://github.com/bs-jokri"><img src="https://avatars2.githubusercontent.com/u/13886571?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [bs-jokri](https://github.com/bs-jokri)**
_Monday Oct 09, 2017 at 10:54 GMT_

----

_From @maxhbr on April 28, 2017 11:59_

related to #139

**Comment by blaumeiser-at-bosch** [comment]
Obsolete
