### ISSUE TITLE
Possiblity to import todos for all departments

### ISSUE THREAD

**Issue by maierthomas** [eclipse/sw360#167]
<a href="https://github.com/bs-jokri"><img src="https://avatars2.githubusercontent.com/u/13886571?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [bs-jokri](https://github.com/bs-jokri)**
_Monday Oct 09, 2017 at 10:54 GMT_
_Originally opened as https://github.com/sw360/sw360portal/issues/626_

----

_From @heydenreich on July 15, 2016 9:20_

When importing licenses via the csv-import, the imported todos get an empty whitelist and are at first not visible for any user. The admin has to edit the whitelist in order to make a todo visible to users of his department. 
This is especially annoying if all license information in SW360 is deleted before importing a new version of the license master list.

Suggestion:
For the import, provide the option to add todos to whitelists of all departments (= "add all departments to all todo's whitelists" in SW360). 

_Copied from original issue: bsinno/sw360#243_

**Comment by blaumeiser-at-bosch** [comment]
Obsolete
