### ISSUE TITLE
Error when editing obligations in a project

### ISSUE THREAD

**Issue by tienlee** [eclipse/sw360#1677]
[//]: # (Copyright Siemens AG, 2021. Part of the SW360 Portal Project)
[//]: # (This program and the accompanying materials are made)
[//]: # (available under the terms of the Eclipse Public License 2.0)
[//]: # (which is available at https://www.eclipse.org/legal/epl-2.0/)
[//]: # (SPDX-License-Identifier: EPL-2.0)

### Description

- When editing obligations in a project, the License Obligation column will display obligation text instead of obligation title.
- Update an obligation in the project. A new obligation with title is html format will be added.

#### How to reproduce

1. Edit a project, select the Obligations tab. Choose the License Obligation tab. Click Add Obligations from License Database button.

![Obligation001](https://user-images.githubusercontent.com/15809618/196397146-caa98593-3ce8-41b1-a4ce-cacf31eb3d3b.png)

2. Select 2 license obligation and click add.

![Obligation002](https://user-images.githubusercontent.com/15809618/196397156-a7bf2eef-1fdb-4ce2-a430-fe85154b17b5.png)

3. Click update project and click edit project again. Select Obligations tab.

![Obligation003](https://user-images.githubusercontent.com/15809618/196397168-7c4a3d96-525b-44e5-bd82-9c6edf40aa7b.png)

- Expected: The License Obligation column will display obligation title as step 2nd.
- Actual: The License Obligation column will display obligation text instead of obligation title as step 2nd.

4. Change the status column of one obligation to another status (example: from Open to Acknowledged or Fulfilled), then click update the project.

![Obligation004](https://user-images.githubusercontent.com/15809618/196397179-5cf35d42-1a10-4ba5-bf87-c8953479d9b9.png)

5. Click edit project and select the obligation tab again.

![Obligation005](https://user-images.githubusercontent.com/15809618/196397191-ed1b9937-ffd5-4f05-bfc1-efdec7883604.png)
- Expected: There are 2 license obligations
- Actual: There are 4 license obligations. 2 license obligations with title is html format will be added.

### Versions

* Last commit id on master:
* Operating System (lsb_release -a):

### Logs

Any logs (if any) generated in

#### SW360 logs

Logs generated under /var/log/sw360/sw360.log

#### Tomcat logs

Logs generated under /var/log/tomcat/error.log

**Comment by KoukiHama** [comment]
> project.obligations.enabled=true
