### ISSUE TITLE
Generalize project import backend

### ISSUE THREAD

**Issue by maierthomas** [eclipse/sw360#168]
<a href="https://github.com/bs-jokri"><img src="https://avatars2.githubusercontent.com/u/13886571?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [bs-jokri](https://github.com/bs-jokri)**
_Monday Oct 09, 2017 at 10:55 GMT_
_Originally opened as https://github.com/sw360/sw360portal/issues/629_

----

_From @heydenreich on August 1, 2016 9:11_

At the moment, the project import frontend is prepared to select between different data sources in the backend, whereas the bdp-import - the only option in the backend so far has a "hard-wired" connection with the thrift interface.

Suggestion: make the backend more flexible with the possibility to deploy a new service/new data source for the project import more easily. 

_Copied from original issue: bsinno/sw360#272_

**Comment by mcjaeger** [comment]
@maxhbr @maierthomas is it maybe that considering the refactorings done with the Whitesource import that this is solved?

**Comment by mcjaeger** [comment]
closing it because there were refactorings implemented by the white source import PR https://github.com/eclipse/sw360/pull/270
