### ISSUE TITLE
Use Data imported from BDP in Disclosure Document generation

### ISSUE THREAD

**Issue by maierthomas** [eclipse/sw360#169]
<a href="https://github.com/bs-jokri"><img src="https://avatars2.githubusercontent.com/u/13886571?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [bs-jokri](https://github.com/bs-jokri)**
_Monday Oct 09, 2017 at 10:56 GMT_
_Originally opened as https://github.com/sw360/sw360portal/issues/630_

----

_From @bs-jokri on August 3, 2016 7:55_

Currently, only attachments to components are used as data source for disclosure document generation. It is required that also the imported information from BDP can be used for that.

It should work like the following:
1. use license information from the linked licenses of all releases of a project to print the license text
2. Import the comment field from BDP that contains information about copyrights of a component and store that at a release (e.g. as additional attachment)
3. Use both types of information to generate a disclosure document

_Copied from original issue: bsinno/sw360#274_

**Comment by maierthomas** [comment]
<a href="https://github.com/bs-jokri"><img src="https://avatars2.githubusercontent.com/u/13886571?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [bs-jokri](https://github.com/bs-jokri)**
_Monday Oct 09, 2017 at 10:56 GMT_

----

_From @maxhbr on May 22, 2017 11:53_

This was also recently requested by Ute Gappa

**Comment by maierthomas** [comment]
<a href="https://github.com/bs-jokri"><img src="https://avatars2.githubusercontent.com/u/13886571?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [bs-jokri](https://github.com/bs-jokri)**
_Monday Oct 09, 2017 at 10:56 GMT_

----

~~Epic: #409~~

**Comment by blaumeiser-at-bosch** [comment]
Obsolete
