### ISSUE TITLE
Can't import SPDX licenses with new SPDX library (tools-java 1.0.4)

### ISSUE THREAD

**Issue by tienlee** [eclipse/sw360#1699]
[//]: # (Copyright Siemens AG, 2021. Part of the SW360 Portal Project)
[//]: # (This program and the accompanying materials are made)
[//]: # (available under the terms of the Eclipse Public License 2.0)
[//]: # (which is available at https://www.eclipse.org/legal/epl-2.0/)
[//]: # (SPDX-License-Identifier: EPL-2.0)

### Description

The license import function does not works well. I can not import SPDX licenses to the database.
I think we should remove the old SPDX library (spdx-tools 2.2.3) and use tools-java 1.0.4

I will check and fix this issue. Please assign it to me.

#### How to reproduce

Step 1: Go to Admin > Licenses
Step 2: Click "Import SPDX information" button

Expected:

![SPDXLicenses03](https://user-images.githubusercontent.com/15809618/199377969-2a167827-3c42-4ab9-938e-69d500a1dd74.png)

Actual:

![SPDXLicenses01](https://user-images.githubusercontent.com/15809618/199144049-e48c2958-d59e-4168-90dc-a97d8a4eea6e.png)

### Versions

* Last commit id on master:
* Operating System (lsb_release -a):

### Logs

Any logs (if any) generated in

#### SW360 logs

Logs generated under /var/log/sw360/sw360.log

#### Tomcat logs

Logs generated under /var/log/tomcat/error.log

**Comment by KoukiHama** [comment]
Latter image shows obligation import results.

I guess if you import spdx license without problem, you can get obligation info.

@tienlee
