### ISSUE TITLE
Add version check to BDP

### ISSUE THREAD

**Issue by maierthomas** [eclipse/sw360#170]
<a href="https://github.com/bs-jokri"><img src="https://avatars2.githubusercontent.com/u/13886571?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [bs-jokri](https://github.com/bs-jokri)**
_Monday Oct 09, 2017 at 10:56 GMT_
_Originally opened as https://github.com/sw360/sw360portal/issues/632_

----

_From @bs-jokri on June 28, 2017 7:50_

to prevent issues with the data model we need a version check. 

_Copied from original issue: bsinno/sw360#449_

**Comment by maierthomas** [comment]
<a href="https://github.com/bs-jokri"><img src="https://avatars2.githubusercontent.com/u/13886571?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [bs-jokri](https://github.com/bs-jokri)**
_Monday Oct 09, 2017 at 10:56 GMT_

----

Thrift API changes have to be considered as well

**Comment by blaumeiser-at-bosch** [comment]
Obsolete
