### ISSUE TITLE
Implement Export Mechanism for Project Data based on thrift json transport output

### ISSUE THREAD

**Issue by maierthomas** [eclipse/sw360#171]
<a href="https://github.com/bs-jokri"><img src="https://avatars2.githubusercontent.com/u/13886571?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [bs-jokri](https://github.com/bs-jokri)**
_Monday Oct 09, 2017 at 10:56 GMT_
_Originally opened as https://github.com/sw360/sw360portal/issues/633_

----

_From @bs-jokri on September 27, 2016 16:55_

For backup reasons it is required that project and component data can be exported. It has to be checked if that works.

For projects we also need to export the list of linked releases/projects

_Copied from original issue: bsinno/sw360#303_

**Comment by maierthomas** [comment]
<a href="https://github.com/bs-jokri"><img src="https://avatars2.githubusercontent.com/u/13886571?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [bs-jokri](https://github.com/bs-jokri)**
_Monday Oct 09, 2017 at 10:56 GMT_

----

_From @heydenreich on September 28, 2016 7:45_

For components, there are two possibilities: csv-export via admin menu and excel export. For projects, there is only the excel-export in the project portlet.

We have recently extended the excel exports (see upstream master): all properties (that make sense to export) for a project (cq. a component) are exported and there is the possibility to export also the release information of the linked releases of a project or the releases of a component.

@bs-jokri : You could check if this is already sufficient and possibly report here what is missing.

**Comment by maierthomas** [comment]
<a href="https://github.com/bs-jokri"><img src="https://avatars2.githubusercontent.com/u/13886571?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [bs-jokri](https://github.com/bs-jokri)**
_Monday Oct 09, 2017 at 10:56 GMT_

----

@heydenreich Do you have an example export available so that I can have a look. 
Basically, what we need is that the information that was entered into the system can be exported, backed up and imported again, if neccessary. This would be not only the project metadata (name version etc) but also the references to the linked releases and projects. Of course those can be exported separately.

**Comment by maierthomas** [comment]
<a href="https://github.com/bs-jokri"><img src="https://avatars2.githubusercontent.com/u/13886571?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [bs-jokri](https://github.com/bs-jokri)**
_Monday Oct 09, 2017 at 10:56 GMT_

----

_From @heydenreich on September 28, 2016 9:29_

@bs-jokri  Well, the excel-export cannot be imported again. Therefore, you need the csv-export. For projects, we do not have a csv export yet.

**Comment by maierthomas** [comment]
<a href="https://github.com/bs-jokri"><img src="https://avatars2.githubusercontent.com/u/13886571?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [bs-jokri](https://github.com/bs-jokri)**
_Monday Oct 09, 2017 at 10:56 GMT_

----

@heydenreich would it be possible to save the excel project export as csv and import that csv file? Otherwise we need some means to import the exported project data again.

**Comment by maierthomas** [comment]
<a href="https://github.com/bs-jokri"><img src="https://avatars2.githubusercontent.com/u/13886571?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [bs-jokri](https://github.com/bs-jokri)**
_Monday Oct 09, 2017 at 10:56 GMT_

----

_From @heydenreich on September 28, 2016 9:43_

@bs-jokri there is no csv import implemented for projects yet. We could implement it, of course, would be an L-ticket, I guess.

**Comment by maierthomas** [comment]
<a href="https://github.com/bs-jokri"><img src="https://avatars2.githubusercontent.com/u/13886571?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [bs-jokri](https://github.com/bs-jokri)**
_Monday Oct 09, 2017 at 10:56 GMT_

----

@heydenreich  What would we need to drop to put that into the sprint? could you mark the stories from bottom to top

**Comment by maierthomas** [comment]
<a href="https://github.com/bs-jokri"><img src="https://avatars2.githubusercontent.com/u/13886571?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [bs-jokri](https://github.com/bs-jokri)**
_Monday Oct 09, 2017 at 10:57 GMT_

----

_From @heydenreich on September 28, 2016 12:2_

After our discussion:
- enable each user to download an archive for the projects visible to that user  containing a csv-file per project with all project information (including couchdb-ids of linked releases, projects and so on)
- possibility for each user to upload a single csv -file and add the project to the db
- questions:
- user x  from department y should not be able to add a project with 'created by' different than x and department other than y - ok?
- if couchdb-id of project already present in system - error and do not import
- link projects and releases via couchdb-id in import

**Comment by maierthomas** [comment]
<a href="https://github.com/bs-jokri"><img src="https://avatars2.githubusercontent.com/u/13886571?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [bs-jokri](https://github.com/bs-jokri)**
_Monday Oct 09, 2017 at 10:57 GMT_

----

_From @maxhbr on October 6, 2016 14:11_

To serialize an Thrift object `object_name` to JSON one can use:

```
TSerializer serializer = new TSerializer(new TSimpleJSONProtocol.Factory());
String json = serializer.toString(object_name);
```

**Comment by maierthomas** [comment]
<a href="https://github.com/bs-jokri"><img src="https://avatars2.githubusercontent.com/u/13886571?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [bs-jokri](https://github.com/bs-jokri)**
_Monday Oct 09, 2017 at 10:57 GMT_

----

_From @heydenreich on October 6, 2016 14:58_

After today's discussion, the ticket becomes:
- GUI: project-details-view: button `backup` to backup a single project
- backup should include:
  - project with all project properties
  - linked releases with all release properties
  - components of those releases with all component properties
  - properties include the couchdb-id
  - all attachments of project, releases, components
  - everything should be packed as a.zip-archive

Such an archive must be imported again. If a project, release or component with the same id already exists, refuse to import that document.

We do not export license data, since licenses usually have the spdx-id as id and therefore can be traced.

Intermediate result can be found on https://github.com/bsinno/sw360/tree/dev/backupProjects

**Comment by maierthomas** [comment]
<a href="https://github.com/bs-jokri"><img src="https://avatars2.githubusercontent.com/u/13886571?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [bs-jokri](https://github.com/bs-jokri)**
_Monday Oct 09, 2017 at 10:57 GMT_

----

_From @maxhbr on October 11, 2016 8:53_

This issue was moved to optional on behalf of @dndimi

**Comment by maierthomas** [comment]
<a href="https://github.com/bs-jokri"><img src="https://avatars2.githubusercontent.com/u/13886571?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [bs-jokri](https://github.com/bs-jokri)**
_Monday Oct 09, 2017 at 10:57 GMT_

----

as a first step without exporting attachments.

**Comment by maierthomas** [comment]
<a href="https://github.com/bs-jokri"><img src="https://avatars2.githubusercontent.com/u/13886571?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [bs-jokri](https://github.com/bs-jokri)**
_Monday Oct 09, 2017 at 10:57 GMT_

----

_From @heydenreich on December 2, 2016 11:1_

Should be followed up by #360 and #361

**Comment by mcjaeger** [comment]
Is it maybe that such kind of archive could achieved with the REST API?

**Comment by mcjaeger** [comment]
if the REST APi serves the javascript client, it is maybe also good enough to serve as project export import. @bs-jokri, please clarify, if the CSV-based approach shall be implemented or the REST API is enough

**Comment by bs-jokri** [comment]
Rest api should be enough
