### ISSUE TITLE
Implement configurable permissions

### ISSUE THREAD

**Issue by maierthomas** [eclipse/sw360#172]
<a href="https://github.com/bs-jokri"><img src="https://avatars2.githubusercontent.com/u/13886571?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [bs-jokri](https://github.com/bs-jokri)**
_Monday Oct 09, 2017 at 10:57 GMT_
_Originally opened as https://github.com/sw360/sw360portal/issues/634_

----

_From @heydenreich on November 18, 2016 14:45_

* shiro continued for projects, components, vendors, licenses, releases, vulnerabilities
* adjust tests
* make adding new roles per configuration possible
* documentation
* remove old SW360 Permission code

_Copied from original issue: bsinno/sw360#348_

**Comment by mcjaeger** [comment]
@bs-jokri are you pursuing the Shiro based approach or is it abandoned?

**Comment by bs-jokri** [comment]
Shiro is just to slow so we stopped that effort. I will close
