### ISSUE TITLE
Add explicit permission checks 

### ISSUE THREAD

**Issue by maierthomas** [eclipse/sw360#173]
<a href="https://github.com/bs-jokri"><img src="https://avatars2.githubusercontent.com/u/13886571?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [bs-jokri](https://github.com/bs-jokri)**
_Monday Oct 09, 2017 at 10:57 GMT_
_Originally opened as https://github.com/sw360/sw360portal/issues/635_

----

_From @heydenreich on November 23, 2016 10:45_

When implementing permissions with shiro, only the "old" checks where replaced by new ones.
But with shiro, you are able to specify new restrictions, e.g. restricted visibility for components. Those would not be respected in the current version of SW360. Therefore we need to add more explicit permission checks. Some places that I came across:
* visibility of components, releases, licenses, vendors, vulnerabilities when listing the overview table
* attachment actions are usually not requested separately, but allowed when editing the document is allowed, check whether attachment deletion is even allowed with reading permission of the document?
* the USERS-action is not used: discuss whether it should be used to add moderators etc to documents
* Check generation of moderation requests: currently users are added as moderators to a moderation request based on their role (clearing admin, admin), should this be not based on explicit permissions to write the document? NB: At the moment, not all users who are allowed to edit the document are used as moderators as well.

_Copied from original issue: bsinno/sw360#350_

**Comment by mcjaeger** [comment]
same question as with https://github.com/eclipse/sw360/issues/172

**Comment by bs-jokri** [comment]
Will close this as well
