### ISSUE TITLE
shiro.ini to /etc

### ISSUE THREAD

**Issue by maierthomas** [eclipse/sw360#174]
<a href="https://github.com/bs-jokri"><img src="https://avatars2.githubusercontent.com/u/13886571?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [bs-jokri](https://github.com/bs-jokri)**
_Monday Oct 09, 2017 at 10:57 GMT_
_Originally opened as https://github.com/sw360/sw360portal/issues/636_

----

_From @heydenreich on November 28, 2016 11:28_

make permissions centrally configurable by moving the shiro.ini to /etc

_Copied from original issue: bsinno/sw360#355_

**Comment by mcjaeger** [comment]
@maxhbr @bs-jokri do you guys have shiro in place?

**Comment by maxhbr** [comment]
I think this issue can be closed
