### ISSUE TITLE
Doucumentation about migration is not correct 

### ISSUE THREAD

**Issue by KoukiHama** [eclipse/sw360#1746]
[//]: # (Copyright Siemens AG, 2021. Part of the SW360 Portal Project)
[//]: # (This program and the accompanying materials are made)
[//]: # (available under the terms of the Eclipse Public License 2.0)
[//]: # (which is available at https://www.eclipse.org/legal/epl-2.0/)
[//]: # (SPDX-License-Identifier: EPL-2.0)

### Description

[Please describe your issue in few words here.]

(https://github.com/eclipse/sw360/tree/main/scripts/migrations#1340---1400)

lack of note about this script
https://github.com/eclipse/sw360/blob/main/scripts/migrations/048_add_component_businessunit.py

![image](https://user-images.githubusercontent.com/39894802/204759702-7db1c78f-e730-4393-90c8-21c8fe7a2699.png)

#### How to reproduce

Describe the bug and list the steps you used when the issue occurred.

### Versions

* Last commit id on master:
* Operating System (lsb_release -a):

### Logs

Any logs (if any) generated in

#### SW360 logs

Logs generated under /var/log/sw360/sw360.log

#### Tomcat logs

Logs generated under /var/log/tomcat/error.log

**Comment by dineshr93** [comment]
Hi @KoukiHama  048 script is not there in https://github.com/eclipse/sw360/tree/sw360-15.0.0-M1/scripts/migrations

**Comment by KoukiHama** [comment]
wow I will check history migration script.

**Comment by tuannn2** [comment]
Hi @KoukiHama 048 script is  the migration file from version 15 to 16.
ID commit: 681eb0c4  with content commit  "fix(ui): Restrict visibility of each component/release like Project "
link refer: https://github.com/eclipse/sw360/releases/tag/sw360-16.0.0-M1:

**Comment by dineshr93** [comment]
> Hi @KoukiHama 048 script is the migration file from version 15 to 16. ID commit: [681eb0c](https://github.com/eclipse/sw360/commit/681eb0c408d24998a38ca14195695d287e99ad92) with content commit "fix(ui): Restrict visibility of each component/release like Project " link refer: https://github.com/eclipse/sw360/releases/tag/sw360-16.0.0-M1:

Hi @tuannn2 I am getting error in release [sw360-15.0.0-M1](https://github.com/eclipse/sw360/releases/tag/sw360-15.0.0-M1) without the 048 script. The error is resolved only when 048 script is run. I just tested it

**Comment by KoukiHama** [comment]
updated doc
