### ISSUE TITLE
backup projects: backup attachments

### ISSUE THREAD

**Issue by maierthomas** [eclipse/sw360#175]
<a href="https://github.com/bs-jokri"><img src="https://avatars2.githubusercontent.com/u/13886571?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [bs-jokri](https://github.com/bs-jokri)**
_Monday Oct 09, 2017 at 10:58 GMT_
_Originally opened as https://github.com/sw360/sw360portal/issues/637_

----

_From @heydenreich on December 2, 2016 11:0_

Currently the backup download of a project contains only related projects, releases, components, vendors.
The attachments of those should be included as well. 

_Copied from original issue: bsinno/sw360#360_

**Comment by mcjaeger** [comment]
requires clarification if the REST API download attachments is just Ok fir this.

**Comment by blaumeiser-at-bosch** [comment]
Obsolete
