### ISSUE TITLE
The language support for Chinese

### ISSUE THREAD

**Issue by shi9qiu** [eclipse/sw360#1751]
[//]: # (Copyright Siemens AG, 2021. Part of the SW360 Portal Project)
[//]: # (This program and the accompanying materials are made)
[//]: # (available under the terms of the Eclipse Public License 2.0)
[//]: # (which is available at https://www.eclipse.org/legal/epl-2.0/)
[//]: # (SPDX-License-Identifier: EPL-2.0)

### Description

We will add the language support for Chinese for SW360. With this support, we want to attract more users and contributors to join our community. We will also try to find somewhere to introduce SW360 to the OSS community in China.

We have implemented this and will release it soon after the final test.

**Comment by KoukiHama** [comment]
@shi9qiu  could you attach chinese property file here?

**Comment by shi9qiu** [comment]
Yes. Here is the property file.
[Language_cn.txt](https://github.com/eclipse/sw360/files/10139496/Language_cn.txt)
(.properties file is not allowed, so I upload a .txt file.)
