### ISSUE TITLE
backup projects: report warning if not everything could be written to backup

### ISSUE THREAD

**Issue by maierthomas** [eclipse/sw360#176]
<a href="https://github.com/bs-jokri"><img src="https://avatars2.githubusercontent.com/u/13886571?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [bs-jokri](https://github.com/bs-jokri)**
_Monday Oct 09, 2017 at 10:58 GMT_
_Originally opened as https://github.com/sw360/sw360portal/issues/638_

----

_From @heydenreich on December 2, 2016 11:36_

When downloading a project backup archive, not all linked documents might be exported because of limited visibility-permissions of the user. The user should see a warning about that. 

Challenge: return a possibly large .zip-file (including attachments!) in combination with metadata (e.g. RequestSummary including RequestStatus, number of totally  treated docs and number of successfully treated docs). The limit is 500MB when doing this via Javascript in Firefox. Therefore, we have to find a different solution, e.g. presenting the metadata and a download link to the user and storing the zip-archive somewhere for later access via the download link.  

_Copied from original issue: bsinno/sw360#361_

**Comment by blaumeiser-at-bosch** [comment]
Obsolete
