### ISSUE TITLE
Store attachments in external repository

### ISSUE THREAD

**Issue by maierthomas** [eclipse/sw360#177]
<a href="https://github.com/bs-jokri"><img src="https://avatars2.githubusercontent.com/u/13886571?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [bs-jokri](https://github.com/bs-jokri)**
_Monday Oct 09, 2017 at 10:58 GMT_
_Originally opened as https://github.com/sw360/sw360portal/issues/639_

----

_From @bs-jokri on December 12, 2016 10:3_

Instead of manually uploading the source code attachments into sw360, one wants to have the option to use an external repository for data-keeping.
For this one might have to add an UI element, which allows on-demand adding of credentials.

_Copied from original issue: bsinno/sw360#364_

**Comment by mcjaeger** [comment]
@bs-jokri OK to move this to general improvements "milestone"?

**Comment by bs-jokri** [comment]
Ok with me

**Comment by blaumeiser-at-bosch** [comment]
Obsolete
