### ISSUE TITLE
Change Expand All to Expand Next Level in Project License Clearing

### ISSUE THREAD

**Issue by afsahsyeda** [eclipse/sw360#1783]
[//]: # (Copyright Siemens AG, 2021. Part of the SW360 Portal Project)
[//]: # (This program and the accompanying materials are made)
[//]: # (available under the terms of the Eclipse Public License 2.0)
[//]: # (which is available at https://www.eclipse.org/legal/epl-2.0/)
[//]: # (SPDX-License-Identifier: EPL-2.0)

### Description

If one hits at Tab "License Clearing" button "Expand All" for the first time, it expands level 1 only. To expand level 2 the button has to be pushed again.
In contrast "Collapse All" works as expected.
If you repeat these steps "Expand All" works as expected.

![image](https://user-images.githubusercontent.com/115608771/208835919-b3ca1cdb-a31b-46e1-96e9-fa2baf21d215.png)

**Comment by hoangnt2** [comment]
I think this is a feature, not a bug. With large data, it will take long time to expand all level. So in source code, someone is setting expand all expands next level only instead of all level.

**Comment by RalphBallhorn** [comment]
I disagree to above assumption. The functionality should follow user expectations derived from intuitive UI design.  
Example for an unexpected result one might face: If one does "Expand All" and tries browser search for a certain release it may still be hidden, if it is contained in a level not yet expanded.  

If above statement would really be correct and should remain, I still suggest to:
- rename the link from "Expand All" to "Expand Next Level"
- notify whether that last level has been expanded, such as to hide or gray out the link

**Comment by akapti** [comment]
It would be really good if the same changes are done for `Attachment Usage` table as well.
![image](https://user-images.githubusercontent.com/50870174/214002960-02b42770-3a33-4a50-b8b5-de325df569fe.png)
