### ISSUE TITLE
Failed to build docker-compose 

### ISSUE THREAD

**Issue by KoukiHama** [eclipse/sw360#1785]
[//]: # (Copyright Siemens AG, 2021. Part of the SW360 Portal Project)
[//]: # (This program and the accompanying materials are made)
[//]: # (available under the terms of the Eclipse Public License 2.0)
[//]: # (which is available at https://www.eclipse.org/legal/epl-2.0/)
[//]: # (SPDX-License-Identifier: EPL-2.0)

### Description

Please describe your issue in few words here.

#### How to reproduce

git clone
docker_build.sh
docker-compose up -d

Can not open some sw360 conotets after import lar files

L.723 Error  OAuthClientRepository
[teraterm1221-10g.log](https://github.com/eclipse/sw360/files/10276113/teraterm1221-10g.log)

### Versions

* Last commit id on master:
* Operating System (lsb_release -a): https://github.com/eclipse/sw360/commit/35ea249bb8cf604a5840e9730779214e692f3756

### Logs

Any logs (if any) generated in

#### SW360 logs

Logs generated under /var/log/sw360/sw360.log

#### Tomcat logs

Logs generated under /var/log/tomcat/error.log
[teraterm1221-10g.log](https://github.com/eclipse/sw360/files/10276113/teraterm1221-10g.log)

**Comment by KoukiHama** [comment]
I will retry and close now,

**Comment by KoukiHama** [comment]
https://github.com/eclipse/sw360/blob/920d128145fcf4da4755311fa9cf2856254842fb/docker-compose.yml#L38

5438 should be change 5432?

**Comment by heliocastro** [comment]
This was intentional to avoid clash with host possible installed Postgres and made it visible to use tools like pgadmin.
Is only related to host, not affect the sw360 internal docker network.

**Comment by KoukiHama** [comment]
I see, thank you. I got the meaning of the number.

We still fail to show portlets about sw360 by docker-compose. Later, a Toshiba colleague will share the log here.

![image](https://user-images.githubusercontent.com/39894802/210724741-66fa95b6-ccdc-4193-9276-f8c9ad9dcda9.png)

**Comment by heliocastro** [comment]
@KoukiHama Remember that this will work only when you add a user. setup@ user doesn't have an Department ID, so need to create an user after import the .lar files

**Comment by KoukiHama** [comment]
Thank you very much.  You are right.
I became a bit of a fool Over the winter break. ((+_+))

**Comment by heliocastro** [comment]
Actually, i think you found a bug in documentation.
I think when we made the transition to docker docs this were left behind.
