### ISSUE TITLE
Realize Officer Role in SW360

### ISSUE THREAD

**Issue by maierthomas** [eclipse/sw360#179]
<a href="https://github.com/bs-jokri"><img src="https://avatars2.githubusercontent.com/u/13886571?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [bs-jokri](https://github.com/bs-jokri)**
_Monday Oct 09, 2017 at 10:59 GMT_
_Originally opened as https://github.com/sw360/sw360portal/issues/643_

----

_From @bs-jokri on December 15, 2016 10:50_

## Approach
Users can be assigned to multiple groups
Officer user is assigned to all goups of his or her Business Unit

## Things to be considered
- https://github.com/sw360/sw360portal/issues/617 
- When project is created user has to select the organization the project will be belong to
- User sees all projects of all organizations he or she belongs to
- ToDo view must allow to select the organization the whitelist will be valid for

_Copied from original issue: bsinno/sw360#378_

**Comment by blaumeiser-at-bosch** [comment]
Obsolete
