### ISSUE TITLE
Integration of SW360 and IBM Rational Team Concert (ALM)

### ISSUE THREAD

**Issue by maierthomas** [eclipse/sw360#180]
<a href="https://github.com/bs-jokri"><img src="https://avatars2.githubusercontent.com/u/13886571?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [bs-jokri](https://github.com/bs-jokri)**
_Monday Oct 09, 2017 at 10:59 GMT_
_Originally opened as https://github.com/sw360/sw360portal/issues/644_

----

_From @bs-jokri on December 19, 2016 16:47_

Several stakeholders have requested an integration of sw360 with RTC. This ticket collects all information that is found to realize such an integration.

### Links
https://jazz.net/downloads/rational-team-concert/releases/6.0.3
https://rsjazz.wordpress.com/2013/03/14/what-apis-are-available-for-rtc-and-what-can-you-extend/
https://rsjazz.wordpress.com/2013/02/28/setting-up-rational-team-concert-for-api-development/
https://jazz.net/library/article/1000

_Copied from original issue: bsinno/sw360#379_

**Comment by blaumeiser-at-bosch** [comment]
Obsolete
