### ISSUE TITLE
Improve remote attachment capabilities

### ISSUE THREAD

**Issue by maierthomas** [eclipse/sw360#181]
<a href="https://github.com/bs-jokri"><img src="https://avatars2.githubusercontent.com/u/13886571?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [bs-jokri](https://github.com/bs-jokri)**
_Monday Oct 09, 2017 at 11:00 GMT_
_Originally opened as https://github.com/sw360/sw360portal/issues/645_

----

_From @maxhbr on February 17, 2017 12:40_

- [ ] auth on demand
- [ ] button: "make to non remote attachment"

This is a continuation of https://github.com/sw360/sw360portal/issues/639

_Copied from original issue: bsinno/sw360#393_

**Comment by blaumeiser-at-bosch** [comment]
Obsolete
