### ISSUE TITLE
Improve License handling: implement new datamodel

### ISSUE THREAD

**Issue by maierthomas** [eclipse/sw360#182]
<a href="https://github.com/bs-jokri"><img src="https://avatars2.githubusercontent.com/u/13886571?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [bs-jokri](https://github.com/bs-jokri)**
_Monday Oct 09, 2017 at 11:00 GMT_
_Originally opened as https://github.com/sw360/sw360portal/issues/646_

----

_From @maxhbr on April 13, 2017 11:48_

_Copied from original issue: bsinno/sw360#403_

**Comment by maxhbr** [comment]
Technical issue
