### ISSUE TITLE
Improve License Importer to Use REST-API

### ISSUE THREAD

**Issue by maierthomas** [eclipse/sw360#183]
<a href="https://github.com/bs-jokri"><img src="https://avatars2.githubusercontent.com/u/13886571?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [bs-jokri](https://github.com/bs-jokri)**
_Monday Oct 09, 2017 at 11:01 GMT_
_Originally opened as https://github.com/sw360/sw360portal/issues/650_

----

_From @bs-jokri on June 12, 2017 7:58_

- Evaluate what the current REST API can with respect to Licenses
   - Create Todos?
   - Create Risks
   - ....
Create follow up tickets for REST functionality that is missing

Must be able to handle LML 1.4

The current version of the LML is here: https://products.bosch-si.com/stash/projects/OSMI/repos/sw360-license-master-list-archive-creator/browse

_Copied from original issue: bsinno/sw360#441_

**Comment by mcjaeger** [comment]
@bs-jokri if that was part of a thesis in Autumn 2017, please update if that is still current

**Comment by bs-jokri** [comment]
There is currently no active work on that anymore. So will close for now
