### ISSUE TITLE
In LicenseInfo Generation: Use Name of License Entry in SPDX file

### ISSUE THREAD

**Issue by maierthomas** [eclipse/sw360#184]
<a href="https://github.com/bs-jokri"><img src="https://avatars2.githubusercontent.com/u/13886571?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [bs-jokri](https://github.com/bs-jokri)**
_Wednesday Oct 11, 2017 at 08:35 GMT_
_Originally opened as https://github.com/sw360/sw360portal/issues/651_

----

_From @bs-jokri on September 18, 2017 14:22_

Currently, the license ref ID is used as license name from sPDX files. However, in Protex SPDX reports you also have a name field. It would be good, if this field is used, if present.

Should work for DOCX, Text, HTML

_Copied from original issue: bsinno/sw360#486_

**Comment by mcjaeger** [comment]
maybe at some time, we need extrnal Ids also for license entries in the DB

**Comment by blaumeiser-at-bosch** [comment]
Obsolete
