### ISSUE TITLE
Proper error messages for BDP import

### ISSUE THREAD

**Issue by maierthomas** [eclipse/sw360#185]
<a href="https://github.com/bs-jokri"><img src="https://avatars2.githubusercontent.com/u/13886571?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [bs-jokri](https://github.com/bs-jokri)**
_Wednesday Oct 11, 2017 at 08:46 GMT_
_Originally opened as https://github.com/sw360/sw360portal/issues/654_

----

_From @bs-jokri on September 7, 2017 14:38_

If user cannot import project due to license import problems error message "cannot import project" is not helpful. Should say why it is not possible (no permissions to import licenses)

_Copied from original issue: bsinno/sw360#483_

**Comment by blaumeiser-at-bosch** [comment]
Obsolete
