### ISSUE TITLE
Whitelist for releases on group level

### ISSUE THREAD

**Issue by maierthomas** [eclipse/sw360#186]
<a href="https://github.com/bs-jokri"><img src="https://avatars2.githubusercontent.com/u/13886571?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [bs-jokri](https://github.com/bs-jokri)**
_Thursday Oct 12, 2017 at 19:49 GMT_
_Originally opened as https://github.com/sw360/sw360portal/issues/655_

----

it should be possible to create a white list of releases for a group. 

Rationale: Usage of releases might be allowed on a whitelist basis. It would be good if SW360 can support this.

THis might be realised with a filter on the component search window, with not allowed releases greyed out.  Analogous to the moderation request it should be possible to request the usage of certain releases in a specific group.

Problems:
group as in SW360 is to fine grained. Needs to be on the level of a whole business unit

**Comment by blaumeiser-at-bosch** [comment]
Obsolete
