### ISSUE TITLE
Move sw360 CSS files to sw360-theme

### ISSUE THREAD

**Issue by maierthomas** [eclipse/sw360#187]
<a href="https://github.com/maierthomas"><img src="https://avatars1.githubusercontent.com/u/29916928?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [maierthomas](https://github.com/maierthomas)**
_Thursday Oct 19, 2017 at 09:50 GMT_
_Originally opened as https://github.com/sw360/sw360portal/issues/665_

----

We should import css files (which we need for all pages) over the sw360-theme

Extract imported css files from:
- code
- liferay-portlet.xml

Closes #408

**Comment by mcjaeger** [comment]
(from discussion)
* problem is a little that css split will always be there because of placement vs. colour

**Comment by lepokle** [comment]
@mcjaeger 
Can be closed from my point of view.

**Comment by mcjaeger** [comment]
some parts needs to stay in the sw360-portlet project in oder to work properly without the sw360-theme. It should be OK as it is now.
