### ISSUE TITLE
Improve error message when generating License Info from broken file and invalid settings

### ISSUE THREAD

**Issue by maierthomas** [eclipse/sw360#189]
<a href="https://github.com/bodetc"><img src="https://avatars2.githubusercontent.com/u/22469333?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [bodetc](https://github.com/bodetc)**
_Tuesday Nov 07, 2017 at 13:38 GMT_
_Originally opened as https://github.com/sw360/sw360portal/issues/675_

----

When using the "Generate License Information" feature with broken attachments (i.e. files with errors that cannot be parsed), the request to the server dies with an Error 500. It would be preferable to show a proper error message.

<img width="415" alt="screen shot 2017-11-07 at 14 35 52" src="https://user-images.githubusercontent.com/22469333/32496350-404381fc-c3c9-11e7-84b5-ced816c2ff63.png">

In addition, the checkbox selection can also crash the effort which also returns a 500. Son at this point, the application shall actually prevent the user from wrong inputs. One wrong input is having particular licenses selected from XML license information, without having selected the checkbox of the file. Then, when clicking the button, the application crashes. The bast way to cope here would be to disallow checking invalid check boxes choices right away:

* select licenses from XML file without selecting XML itself
* select XML file but have unset all licenses from that file
* or unset check box of the file, but check boxes from licenses are not deactivated

**Comment by mcjaeger** [comment]
there is a warning message printed for the component entry now.
