### ISSUE TITLE
SPDX merge for Project

### ISSUE THREAD

**Issue by maierthomas** [eclipse/sw360#193]
<a href="https://github.com/bs-jokri"><img src="https://avatars2.githubusercontent.com/u/13886571?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [bs-jokri](https://github.com/bs-jokri)**
_Thursday Dec 07, 2017 at 11:50 GMT_
_Originally opened as https://github.com/sw360/sw360portal/issues/694_

----

Sometimes one needs to deliver one spdx report for the complete set of dependencies of a project. Since we have spdx reports for all used releases it would be good to directly merge them into one spdx report.
Result is one spdx report for all referenced releases of a project. 

The spdx-tools should already have a feature that allows to merge spdx reports

for this feature only clearing reports in spdx format are considered

![sw360-spdx generator](https://user-images.githubusercontent.com/22469333/34153229-952aa70a-e4b1-11e7-8b15-9fc05a290f25.png)

**Comment by blaumeiser-at-bosch** [comment]
Obsolete
