### ISSUE TITLE
Component Field softwarePlatforms is unused

### ISSUE THREAD

**Issue by maierthomas** [eclipse/sw360#194]
<a href="https://github.com/alexbrdn"><img src="https://avatars0.githubusercontent.com/u/16780167?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [alexbrdn](https://github.com/alexbrdn)**
_Thursday Dec 07, 2017 at 12:55 GMT_
_Originally opened as https://github.com/sw360/sw360portal/issues/695_

----

Components have a field `softwarePlatforms`, which is supposed to be an aggregate field of releases' software platforms, but Release does not have a corresponding field. Consequently, the field in component is displayed, but there is no way to edit it. Nor is it used anywhere else.

I believe it should be removed.

**Comment by muitimon** [comment]
Hi @maierthomas .
I would like to fix this bug. But I have two questions. So if you know, could you tell me my questions.
- Do you know when or how sw360users use ```softwarePlatforms```?
- Do you have any plan about using ```softwarePlatforms```?

**Comment by alexbrdn** [comment]
As it says in the issue, apparently, this field is never used and seems like no one really needs it.

**Comment by muitimon** [comment]
Thunk you, comments. I would like to fix it.

**Comment by akapti** [comment]
Hi @alexbrdn 
Though  `softwarePlatforms` field is not displayed while adding or editing component. But while testing I found that field is mapped to some of the components. and I am able to do component search based on Software Platforms, and same is present in exported spreadsheet.
Let me know if this field should be completely removed or only from component search and spreadsheet?

**Comment by mcjaeger** [comment]
maybe not important anymore to have this issue ...
