### ISSUE TITLE
In generating License Info: Do not use found license if concluded not available 

### ISSUE THREAD

**Issue by maierthomas** [eclipse/sw360#195]
<a href="https://github.com/bs-jokri"><img src="https://avatars2.githubusercontent.com/u/13886571?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [bs-jokri](https://github.com/bs-jokri)**
_Monday Dec 11, 2017 at 13:41 GMT_
_Originally opened as https://github.com/sw360/sw360portal/issues/698_

----

When a license info file is generated with spdx reports, it should be possible to disable found licenses if concluded licenses are available.

**Comment by maierthomas** [comment]
<a href="https://github.com/mcjaeger"><img src="https://avatars1.githubusercontent.com/u/3418977?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [mcjaeger](https://github.com/mcjaeger)**
_Wednesday Jan 24, 2018 at 16:04 GMT_

----

Actually, how about letting the user choose what to generate? because I feel like many spdx document just have the found licenses and then concluded licenses are not well cared for.

**Comment by maierthomas** [comment]
<a href="https://github.com/truongtv-tsdv"><img src="https://avatars0.githubusercontent.com/u/24468175?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [truongtv-tsdv](https://github.com/truongtv-tsdv)**
_Friday Jan 26, 2018 at 09:44 GMT_

----

Hi,
I am also considering this issue
As I know. Currently, the code for "disabling license info in file" is already preset, the corresponding flag is hard coded to true.
I wonder why the useLicenseInfoFromFiles flag is not controllable now.
(Just not implemented, or other reasons?)
I think we should make the flag controllable from sw360 interface
Do you think about this?

**Comment by mcjaeger** [comment]
finally there:

<img width="1475" alt="Screenshot 2021-03-24 at 23 16 57" src="https://user-images.githubusercontent.com/3418977/112390778-190c9d80-8cf7-11eb-814a-2e810367f6f0.png">
