### ISSUE TITLE
Make external ids editable for projects too

### ISSUE THREAD

**Issue by maierthomas** [eclipse/sw360#196]
<a href="https://github.com/mcjaeger"><img src="https://avatars1.githubusercontent.com/u/3418977?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [mcjaeger](https://github.com/mcjaeger)**
_Tuesday Dec 12, 2017 at 12:30 GMT_
_Originally opened as https://github.com/sw360/sw360portal/issues/699_

----

So, we have this at release and we have the roles editable for projects, but it would be good to have the external ids also editable for projects.

Note that there is also required to have moderation requests covered for a project if a non-allowed-for-writing-user edits this.

**Comment by mcjaeger** [comment]
done
