### ISSUE TITLE
Adapt style of buttons in DataTables

### ISSUE THREAD

**Issue by maierthomas** [eclipse/sw360#197]
<a href="https://github.com/bodetc"><img src="https://avatars2.githubusercontent.com/u/22469333?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [bodetc](https://github.com/bodetc)**
_Wednesday Dec 13, 2017 at 09:28 GMT_
_Originally opened as https://github.com/sw360/sw360portal/issues/700_

----

* Adapt the style of the buttons in our Datatables to fit the SW360 styling (see screenshots).
* Use the style of the `addButton` class.
* Focus on the vulnerability tables (`vulnerabilities.jspf`).
* Rename `dataTable_Siemens.css` and `dataTable_SiemensHomepage.css` to vendor agnostic names.
* Make the buttons grey and use a consistent width

Current situation:
<img width="350" alt="screen shot 2017-12-11 at 14 09 04" src="https://user-images.githubusercontent.com/22469333/33931373-14dd423a-dff0-11e7-8fcf-a7a38411b29d.png">
<img width="532" alt="screen shot 2017-12-13 at 10 27 04" src="https://user-images.githubusercontent.com/22469333/33931416-31d527ae-dff0-11e7-9039-a1243ba0af6f.png">

**Comment by mcjaeger** [comment]
@alexbrdn is this maybe done now?

**Comment by lepokle** [comment]
@mcjaeger 
Can be closed from my point of view.

**Comment by mcjaeger** [comment]
agree
