### ISSUE TITLE
Change/Update "reference platform" in README

### ISSUE THREAD

**Issue by maierthomas** [eclipse/sw360#198]
<a href="https://github.com/maxhbr"><img src="https://avatars3.githubusercontent.com/u/1187050?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [maxhbr](https://github.com/maxhbr)**
_Thursday Dec 14, 2017 at 16:01 GMT_
_Originally opened as https://github.com/sw360/sw360portal/issues/702_

----

The README currently states:
> The reference platform is the Ubuntu server 14.04 (which is a LTS version).

due to docker that is no longer completely true. I would suggest to change that and not to mention that outdated OS.

**Comment by ljmanz** [comment]
As far as i see, this was corrected to "16.04" by mcjaeger@31deb6f9fbe8c5ba225e06202976dd310ed9af93

**Comment by blaumeiser-at-bosch** [comment]
Obsolete
