### ISSUE TITLE
Merge Components Improvements

### ISSUE THREAD

**Issue by maierthomas** [eclipse/sw360#199]
<a href="https://github.com/mcjaeger"><img src="https://avatars1.githubusercontent.com/u/3418977?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [mcjaeger](https://github.com/mcjaeger)**
_Monday Jan 08, 2018 at 09:10 GMT_
_Originally opened as https://github.com/sw360/sw360portal/issues/708_

----

When merging components in productive use, it turn actually out that quite some releases are duplicate. Then the merge of release becomes apparent ... next improvement for this functionality

Second improvement apparently needed, is that one of the creators is lost, with the effect that this person cannot write to the merged record anymore. The creator kicked out should be added to the moderators of the resulting record then.

Third thing is that if releases have (sometimes really) different release names, then it is not nice to have then entries with different release names as the resulting merged component data set. It seems to occur, when the new name is merged into the data set: then, the new resulting names does not seem to be applied to the releases of the component from which the merge assistant was triggered from.

**Comment by lepokle** [comment]
Third thing is fixed with PR #663 since all releases are renamed there with the possibly new name of the target component.
