### ISSUE TITLE
Merging components looses moderators

### ISSUE THREAD

**Issue by maierthomas** [eclipse/sw360#200]
When merging components, the list of moderators is lost in the resulting merged dataset - even shown in merged view for control before actual merge.

**Comment by lepokle** [comment]
I cannot reproduce this issue. I've tested:
- both components have moderators: delete one, add one. Worked.
- only dest components has moderators: delete them. Worked.
- only source component has moderators: add them. Worked.
- both components have moderators: do nothing. Worked.

Maybe this error was related to #208. The exception from this issue prevented all updates to the dest component.
