### ISSUE TITLE
Provide Report about open and fixed Vulnerabilities of a Project

### ISSUE THREAD

**Issue by maierthomas** [eclipse/sw360#205]
<a href="https://github.com/bs-jokri"><img src="https://avatars2.githubusercontent.com/u/13886571?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [bs-jokri](https://github.com/bs-jokri)**
_Tuesday Jan 16, 2018 at 15:51 GMT_
_Originally opened as https://github.com/sw360/sw360portal/issues/716_

----

As a project responsible I want to have a quick overview about the vulnerabilities that are still open and fixed of my project. I would expect to have a report functionality that allows me to filter vulnerabilities according to their status.

**Comment by mcjaeger** [comment]
it is there AFAIK?
