### ISSUE TITLE
Extension to other tools than fossology (palamida, blackduck ...)

### ISSUE THREAD

**Issue by maierthomas** [eclipse/sw360#210]
<a href="https://github.com/TristanFAURE"><img src="https://avatars0.githubusercontent.com/u/4500754?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [TristanFAURE](https://github.com/TristanFAURE)**
_Friday Jan 26, 2018 at 13:32 GMT_
_Originally opened as https://github.com/sw360/sw360portal/issues/732_

----

Hello, 
2 questions :
- Considering the current architecture of the tool is it possible to extends sw360 to other license analysis tool like Palamida or Black Duck ?
- Is it planned ?

Thank you in advance !

**Comment by maierthomas** [comment]
<a href="https://github.com/mcjaeger"><img src="https://avatars1.githubusercontent.com/u/3418977?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [mcjaeger](https://github.com/mcjaeger)**
_Monday Jan 29, 2018 at 12:52 GMT_

----

for black duck protex pls have a look here:
https://github.com/sw360/sw360bdpImportService

**Comment by maierthomas** [comment]
<a href="https://github.com/mcjaeger"><img src="https://avatars1.githubusercontent.com/u/3418977?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [mcjaeger](https://github.com/mcjaeger)**
_Monday Jan 29, 2018 at 13:11 GMT_

----

To answer your question for Palamida directly: I am not aware of this at the moment.

generally, SW360 can read and process SPDX ... what would be the use case that you have in mind?

**Comment by mcjaeger** [comment]
closing because no further update found
