### ISSUE TITLE
REST API: Add endpoints for the attachments itself

### ISSUE THREAD

**Issue by maierthomas** [eclipse/sw360#215]
<a href="https://github.com/mcjaeger"><img src="https://avatars1.githubusercontent.com/u/3418977?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [mcjaeger](https://github.com/mcjaeger)**
_Tuesday Feb 06, 2018 at 09:43 GMT_
_Originally opened as https://github.com/sw360/sw360portal/issues/741_

----

Apparently, there is a "GET Attachment", but this refers to its metadata. Users would need also a handle for downloading the actual attachment (and also the ability to put it before). Maybe one way could be to provide a download link from the attachment response.

Needs clarification how this is actually displayed in the REST API, currently at:

https://sw360server:port/resource/docs/api-guide.html#resources-attachment-get

**Comment by mcjaeger** [comment]
it is in the documentation for attachment info (a download URL is part of the response) but there is no separate endpoint section in the documentation
