### ISSUE TITLE
Make Owner fields for Inner Source Components mandatory

### ISSUE THREAD

**Issue by maierthomas** [eclipse/sw360#217]
<a href="https://github.com/mcjaeger"><img src="https://avatars1.githubusercontent.com/u/3418977?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [mcjaeger](https://github.com/mcjaeger)**
_Tuesday Feb 06, 2018 at 14:45 GMT_
_Originally opened as https://github.com/sw360/sw360portal/issues/743_

----

In the project view, the following fields should be mandatory for users to fill in when they enter a component of the type "Inner Source":

Project owner:
Owner accounting unit:
Owner billing group:

This information needs to be present for Inner Source components, but not for other types of components.

**Comment by mcjaeger** [comment]
not having heard about it since two years
