### ISSUE TITLE
Add component type "code snippet"

### ISSUE THREAD

**Issue by maierthomas** [eclipse/sw360#218]
<a href="https://github.com/mcjaeger"><img src="https://avatars1.githubusercontent.com/u/3418977?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [mcjaeger](https://github.com/mcjaeger)**
_Tuesday Feb 06, 2018 at 14:53 GMT_
_Originally opened as https://github.com/sw360/sw360portal/issues/744_

----

_(was repoted to me)_ Besides the existing component types like "service", Inner Source, etc. a new type shall be available which is something like "code_snippet" because these kind of things add also to the BOM espcially after having done a source code scanner scan.

In regard to the naming convention for "code_snippet" I suggest Functionality-Version-Author-Source are there any better ideas?

Download link shall be where source is the place were it was downloaded from like codeguru or stackoverflow.

**Comment by mcjaeger** [comment]
(from discussion) should be changes in the thrift and UI, naming convention is not relevant for solving this issue

**Comment by mcjaeger** [comment]
https://github.com/eclipse/sw360/pull/755
