### ISSUE TITLE
Reengineering of Release Links Edit View for Projects

### ISSUE THREAD

**Issue by maierthomas** [eclipse/sw360#222]
<a href="https://github.com/mcjaeger"><img src="https://avatars1.githubusercontent.com/u/3418977?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [mcjaeger](https://github.com/mcjaeger)**
_Wednesday Feb 07, 2018 at 16:39 GMT_
_Originally opened as https://github.com/sw360/sw360portal/issues/748_

----

Currenly, the view for linking releases of a project is plain HTML, could be also "data-tablelized" because for allowing sorting and also having good mouse over for running over the text field content.

Currently, if the release name is too long, and maybe the list contains two entries ending with different few characters, it is not obvious how to see this information in the edit view.

Also having title above every cell is not a good practise neither.

**Comment by mcjaeger** [comment]
still not "sortable": 
<img width="877" alt="Screenshot 2020-03-05 at 01 58 00" src="https://user-images.githubusercontent.com/3418977/75937292-c7dc0280-5e84-11ea-8867-c5936ff7c2ce.png">

**Comment by mcjaeger** [comment]
done now:

<img width="1013" alt="Screenshot 2021-03-25 at 22 02 59" src="https://user-images.githubusercontent.com/3418977/112543331-e4abe680-8db5-11eb-899e-e5c729545c82.png">
