### ISSUE TITLE
Add missing Put functionallity to REST

### ISSUE THREAD

**Issue by maierthomas** [eclipse/sw360#226]
<a href="https://github.com/maxhbr"><img src="https://avatars3.githubusercontent.com/u/1187050?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [maxhbr](https://github.com/maxhbr)**
_Wednesday Feb 28, 2018 at 13:28 GMT_
_Originally opened as https://github.com/sw360/sw360portal/issues/762_

----

We should provied the functionallity to modify Releases / Components / Attachments via rest.

This implies two kinds of problems:
- which fields to update?
  not all fields are handled completly by REST
- how to prevent race conditions?

### Which fields to update?
We should be able to update all fields which are readable via REST. Thus we request the user to send all data which he does not want to change, unchanged back to us.

### How to prevent race conditions?
We should send the couchdb rev via REST. Once we get it back we can use it to either prevent updates on missmatch or use couchdb to resolve conflicts.

**Comment by mcjaeger** [comment]
there is already some writing of data

**Comment by gernot-h** [comment]
I think most expected functionality is available, so this can be closed, no?
