### ISSUE TITLE
License documentation for releases linked with internal use: what to do?

### ISSUE THREAD

**Issue by maierthomas** [eclipse/sw360#227]
<a href="https://github.com/mcjaeger"><img src="https://avatars1.githubusercontent.com/u/3418977?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [mcjaeger](https://github.com/mcjaeger)**
_Monday Mar 05, 2018 at 15:32 GMT_
_Originally opened as https://github.com/sw360/sw360portal/issues/768_

----

When generating license info: what to do with project relations for internal use. the problem is that internal use is not for delivery, thus it is a question whether this shall be taken into the license documentation or not.

But clarification is required, because just omitting some relations silently is also not optimal.

**Comment by mcjaeger** [comment]
now you can check for the relation to be considered:

<img width="604" alt="Screenshot 2021-03-25 at 22 04 59" src="https://user-images.githubusercontent.com/3418977/112543556-37859e00-8db6-11eb-856e-e1582f750e38.png">
