### ISSUE TITLE
If a component has only one release, it is listed twice in the release search.

### ISSUE THREAD

**Issue by maierthomas** [eclipse/sw360#229]
<a href="https://github.com/mcjaeger"><img src="https://avatars1.githubusercontent.com/u/3418977?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [mcjaeger](https://github.com/mcjaeger)**
_Wednesday Mar 07, 2018 at 14:01 GMT_
_Originally opened as https://github.com/sw360/sw360portal/issues/772_

----

When adding a release to a project, a double option is suggested, just as if there was a duplicate. It seems to be pretty much the case that this In fact though, when searching for the release itself, no duplicate was found.

**Comment by mcjaeger** [comment]
not seen again and likely went out when refactoring search
