### ISSUE TITLE
Releases can be link to itself at Linked Releases

### ISSUE THREAD

**Issue by maierthomas** [eclipse/sw360#230]
<a href="https://github.com/LinusschTU"><img src="https://avatars2.githubusercontent.com/u/35561003?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [LinusschTU](https://github.com/LinusschTU)**
_Monday Mar 12, 2018 at 12:20 GMT_
_Originally opened as https://github.com/sw360/sw360portal/issues/774_

----

Users can link a release to itself at Linked Releases. Users should not be able to link a release to itself otherwise it could lead to problems.

**Comment by mcjaeger** [comment]
I think it can be selected, but it is not stored, maybe closing this issue

**Comment by mcjaeger** [comment]
now there is a warning:

<img width="786" alt="Screenshot 2021-03-25 at 22 07 19" src="https://user-images.githubusercontent.com/3418977/112543765-7e739380-8db6-11eb-9bd2-8a4ec9f82358.png">
