### ISSUE TITLE
Review REST unit tests for all served fields

### ISSUE THREAD

**Issue by maierthomas** [eclipse/sw360#232]
<a href="https://github.com/mcjaeger"><img src="https://avatars1.githubusercontent.com/u/3418977?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [mcjaeger](https://github.com/mcjaeger)**
_Wednesday Mar 14, 2018 at 13:04 GMT_
_Originally opened as https://github.com/sw360/sw360portal/issues/776_

----

For generating the documentation we would need to have the fields in the unit tests. Maybe some fields are accidentally not in the unit tests. It should be just checked if all served fields (=attributes) are also in the unit tests for the generation of documentation.

**Comment by mcjaeger** [comment]
also attachments links and `checkedby` fields seem to be not working properly.

**Comment by mcjaeger** [comment]
attachments checked by seems to be OK:
https://localhost:8443/resource/docs/api-guide.html#resources-attachment-information-get

attachments are also there:
https://localhost:8443/resource/docs/api-guide.html#resources-release-attachment-info-get

maybe we close this and check on an individual demand basis.
