### ISSUE TITLE
Generated License Information: Name and Version in filename and text.

### ISSUE THREAD

**Issue by maierthomas** [eclipse/sw360#234]
<a href="https://github.com/mcjaeger"><img src="https://avatars1.githubusercontent.com/u/3418977?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [mcjaeger](https://github.com/mcjaeger)**
_Thursday Mar 15, 2018 at 08:20 GMT_
_Originally opened as https://github.com/sw360/sw360portal/issues/778_

----

This covers the license info generation for a project and the alignment of the output.

For the text and xhtml output: there should be project name and version also in the generated text and in the file title. Currently there is only project name in the file title missing the version. In the ideal case, the file name including project name, project version, and generation date and time is all the same for the three formats. Just the file type suffix is different.

**Comment by smrutis1** [comment]
I will be looking into it.
