### ISSUE TITLE
Release vendor is not selected and also cannot be unset

### ISSUE THREAD

**Issue by maierthomas** [eclipse/sw360#237]
<a href="https://github.com/adrian-evo"><img src="https://avatars0.githubusercontent.com/u/19324942?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [adrian-evo](https://github.com/adrian-evo)**
_Thursday Mar 15, 2018 at 10:21 GMT_
_Originally opened as https://github.com/sw360/sw360portal/issues/781_

----

When a release vendor is set and the user call Search Vendor dialog, the current vendor is not selected. Also it is not possible to unset the vendor to none.

![ven](https://user-images.githubusercontent.com/19324942/37457625-358f329c-284b-11e8-93ad-820f11527052.png)

**Comment by mcjaeger** [comment]
Deletion icon is now there and works
