### ISSUE TITLE
Wrong HTTP status code

### ISSUE THREAD

**Issue by maierthomas** [eclipse/sw360#240]
<a href="https://github.com/deveaud-m"><img src="https://avatars3.githubusercontent.com/u/11165188?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [deveaud-m](https://github.com/deveaud-m)**
_Wednesday Mar 21, 2018 at 14:57 GMT_
_Originally opened as https://github.com/sw360/sw360portal/issues/791_

----

While trying to access a private resource via the API, I get following error message:
```
{
    "status": 500,
    "error": "Internal Server Error",
    "message": "Internal error processing getProjectById",
    "timestamp": "2018-03-21T14:55:36.684Z"
}
```

Using the return code 401 might be more appropriate.

**Comment by maierthomas** [comment]
<a href="https://github.com/tngraf"><img src="https://avatars1.githubusercontent.com/u/1225388?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [tngraf](https://github.com/tngraf)**
_Thursday Mar 22, 2018 at 13:07 GMT_

----

I agree to Marion. I only see one error code: 500.
I would appreciate:
* 500 => internal (fatal) error
* 401/403 => private resources
* 404 => id of project/component/release was not found

**Comment by mcjaeger** [comment]
should be solved now: https://github.com/eclipse/sw360/pull/747/files
