### ISSUE TITLE
Allow For Changing User Email Address

### ISSUE THREAD

**Issue by maierthomas** [eclipse/sw360#242]
<a href="https://github.com/alexbrdn"><img src="https://avatars0.githubusercontent.com/u/16780167?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [alexbrdn](https://github.com/alexbrdn)**
_Friday Mar 23, 2018 at 09:30 GMT_
_Originally opened as https://github.com/sw360/sw360portal/issues/795_

----

sw360 should recognize when an email address of a user has changed and preserve the identity.

Criteria for email address change is that the Liferay user with the same externalId (field openId) has a different email address than the sw360 user with the same externalId.
Email change in Liferay is performed by LDAP importer or SSOAutoLogin action.

- when email changes, user's email should be updated and the old email moved into the list of previous email addresses of the user
- migration script necessary to replace all users' ids with generic ids instead of emails
- couchdb indexes should be built by field email address and by previous email addresses
- user search by email address should try searching by email address and fall back to searching by previous email address field

**Comment by maierthomas** [comment]
<a href="https://github.com/maxhbr"><img src="https://avatars3.githubusercontent.com/u/1187050?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [maxhbr](https://github.com/maxhbr)**
_Friday Mar 23, 2018 at 16:01 GMT_

----

The same approach could maybe be used for licenses

**Comment by alexbrdn** [comment]
@maierthomas, how would the switch to guids as user ids affect REST API?

/cc @maxhbr
