### ISSUE TITLE
Handling of get sub projects without having access to it

### ISSUE THREAD

**Issue by maierthomas** [eclipse/sw360#244]
<a href="https://github.com/maierthomas"><img src="https://avatars1.githubusercontent.com/u/29916928?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [maierthomas](https://github.com/maierthomas)**
_Monday Mar 26, 2018 at 09:50 GMT_
_Originally opened as https://github.com/sw360/sw360portal/issues/797_

----

In sw360 portal users can link projects to the selected project as kind of a sub project.
The user can see this relation in the following menus:
- linked releases and projects (Projects)
- is used by the following projects (Components)

For each project users can set individual project visibilities (group, moderators, everyone, private).
Therefore it can be possible that some projects are linked to projects with visibility group or private..
This will result that projects are linked, but the user does not have access to them.

In the current implementation sw360portal (`ProjectDatabaseHandler, getProjectById`) throws a generic sw360exception in case of getting information about the linked project. 

- add additional exception, e.g. 403 forbidden
- usages of this method should be modified, individually decision of exception handling

**Comment by mcjaeger** [comment]
related https://github.com/eclipse/sw360/issues/207

**Comment by mcjaeger** [comment]
there is a warning (as liferay portal message in the top of the page message capsule) now, for this case. if that happens it is telling the user not having sufficient rights.
