### ISSUE TITLE
Correct the numerous FOSSology Portlet Exceptions

### ISSUE THREAD

**Issue by maierthomas** [eclipse/sw360#246]
<a href="https://github.com/mcjaeger"><img src="https://avatars1.githubusercontent.com/u/3418977?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [mcjaeger](https://github.com/mcjaeger)**
_Thursday Mar 29, 2018 at 13:12 GMT_
_Originally opened as https://github.com/sw360/sw360portal/issues/801_

----

In the log, there is too much output like:

```
2018-03-28 12:28:53,913 ERROR FossologyAwarePortlet:168 - Could not get release from request
 2018-03-28 12:28:53,914 ERROR FossologyAwarePortlet:136 - no response from backend!
```

This is apparently, if the request does not have a release id: then, this log message rises. Maybe this is coming from the project portlet which doe snot hold releases and then the logic pulled in from the FOSSology portlet via the inheritance hierarchy is triggered with this error.

**Comment by maierthomas** [comment]
<a href="https://github.com/alexbrdn"><img src="https://avatars0.githubusercontent.com/u/16780167?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [alexbrdn](https://github.com/alexbrdn)**
_Tuesday Apr 03, 2018 at 07:43 GMT_

----

If I am not mistaken, this is caused by JS function `utils/includes/fossologyClearing.initialize()`, which is invoked when a page has just been loaded, but no release has been selected yet.

**Comment by mcjaeger** [comment]
just tested and also did not see this for a while: solved.
