### ISSUE TITLE
Multiple attachment upload is not supported

### ISSUE THREAD

**Issue by maierthomas** [eclipse/sw360#249]
<a href="https://github.com/maierthomas"><img src="https://avatars1.githubusercontent.com/u/29916928?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [maierthomas](https://github.com/maierthomas)**
_Tuesday Apr 17, 2018 at 09:41 GMT_
_Originally opened as https://github.com/sw360/sw360portal/issues/817_

----

Currently users cant upload multiple attachments at the same time.
This behavior is reproducible for
- drag and drop
- select attachment(s) 

In the 'Select Attachment' view users can select several attachments 
thus multiple upload should be supported.

**Comment by smrutis1** [comment]
As per my observation, currently multiple attachment upload is supported, but due to some concurrency fault, sometimes the upload gets stalled in between. I have fixed this issue by applying synchronization mechanism. Now, we could select multiple files and upload the same.
