### ISSUE TITLE
Change links, descriptions because of the eclipse repository change

### ISSUE THREAD

**Issue by maierthomas** [eclipse/sw360#251]
<a href="https://github.com/mcjaeger"><img src="https://avatars1.githubusercontent.com/u/3418977?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [mcjaeger](https://github.com/mcjaeger)**
_Monday Apr 23, 2018 at 11:37 GMT_
_Originally opened as https://github.com/sw360/sw360portal/issues/821_

----

_From @maierthomas on April 23, 2018 8:28_

Change links, descriptions.... regarding the repository change
- REST API Documentation welcome page (issues, link)
- REST API Documentation users (link)
- sw360Portal footer (liferay, link to issue tracker)
- travis results (readme)
...

_Copied from original issue: eclipse/sw360#3_

**Comment by ljmanz** [comment]
I took a look at https://github.com/eclipse/sw360 and https://github.com/eclipse/sw360/wiki and there are only references on https://github.com/sw360/sw360chores and https://github.com/sw360/sw360vagrant, which are, as far as i know, still not migrated to the eclipse repository. 

So this should cover the listed key points. If i missed something, thanks in advance for any advice.
