### ISSUE TITLE
Trim sw360 object names (project name, release name, component name)

### ISSUE THREAD

**Issue by maierthomas** [eclipse/sw360#266]
The user can accidental enter sw360 object names with a beginning "space".
This behavior can lead to confusing in tables which are sorted/searched by the object name.
Entries with beginning spaces cant be found by user search or are sorted at the beginning of each column sort.

Please trim these values to avoid problems.

**Comment by smrutis1** [comment]
I would like to work on it.

**Comment by mcjaeger** [comment]
PR is here https://github.com/eclipse/sw360/pull/725

**Comment by mcjaeger** [comment]
... and has been merged
