### ISSUE TITLE
Default vendor at component level

### ISSUE THREAD

**Issue by mcjaeger** [eclipse/sw360#267]
It is good to have individually set vendors at release levels, but for creating datasets on component level it makes to have a vendor at component level that:

* serves as default vendor for new releases
* user can overwrite the default vendor with another one if the default vendor doe not apply.

In the majority of the cases it is that a vendor on the component level is enough and then filling out a vendor every single release is cumbersome.

**Comment by mcjaeger** [comment]
(from discussion) idea is to be able to store a value in a component and this will be taken once at creating of a release.

**Comment by mcjaeger** [comment]
For component list view, vendor column: deduplicated conjuction of default vendor and vendors found in releases.

**Comment by imaykay** [comment]
Please see PR for last questions and testing.
