### ISSUE TITLE
Action Buttons should be directly under the navgation bar (edit)

### ISSUE THREAD

**Issue by maierthomas** [eclipse/sw360#269]
The action buttons (e.g. Project Update, Cancel) should be directly (sticky) below the navigation menu.

![image](https://user-images.githubusercontent.com/29916928/39816808-9da84e5a-539c-11e8-829c-c56fa42ba6b2.png)

**Comment by mcjaeger** [comment]
I am not sure, maybe both, but in general if a user scrolls down then the users needs to scroll up again to click the buttons.

**Comment by mcjaeger** [comment]
has been changed now to be always at the top
