### ISSUE TITLE
ECC autoset does not properly work with a https URL

### ISSUE THREAD

**Issue by tngraf** [eclipse/sw360#272]
Example: https://www.newtonsoft.com/json

**Comment by tngraf** [comment]
In addition to this also ensure that the autoset function is not activated for COTS components

**Comment by mcjaeger** [comment]
... or any other component types except from OSS, such as service or inner source.

**Comment by maierthomas** [comment]
Tested successfully with the following download URL:

`https://www.newtonsoft.com/json`
I am not able to reproduce this behavior.
