### ISSUE TITLE
Vulnerabilities import from whitesource

### ISSUE THREAD

**Issue by kallesoranko** [eclipse/sw360#274]
Vulnerabilities should also be imported and linked to correct releases (components)

**Comment by mcjaeger** [comment]
please consider that these should be updated on a regular basis?

**Comment by kallesoranko** [comment]
Yes, that should be considered too and I also noticed that vulnerabilities are implemented in sw360 in quite different way that other components, so this one needs more planning before implementation

**Comment by mcjaeger** [comment]
issues turns three years soon and there are no signs for being picked up
