### ISSUE TITLE
Component Tab is not displayed

### ISSUE THREAD

**Issue by OST-SWC** [eclipse/sw360#284]
I tried to use SW360 by these steps.However, I can not use some function of SW360.
My procedure is below.

1. Install liferay-portal-tomcat-6.2-ce-ga5-20151119152357409.zip and thrift 0.9.3
 
2. git clone https://github.com/eclipse/sw360.git and mvn install

3. liferay-portal-6.2-ce-ga5/tomcat-7.0.62/bin/catalina.sh start

4. Then I set liferay by https://github.com/eclipse/sw360/wiki/Deploy-Liferay
  (use Hbase)

5. I went to componet tab. Then I found my componet page did not desplayed.
    I do not know how to solve this issue.
   (Home tab looks like no problem. I confirmed some sw360 data are inserted to CouchDB 1.6.1  )

<img width="960" alt="sw360_home" src="https://user-images.githubusercontent.com/39894802/40906949-4a106f94-681d-11e8-84fe-acc7aa0459d1.png">
<img width="959" alt="component_error" src="https://user-images.githubusercontent.com/39894802/40906950-4a436868-681d-11e8-9464-757ae2a3ea2a.png">

**Comment by alexbrdn** [comment]
Try looking for errors in the tomcat log first. You'll probably find some hints.

**Comment by OST-SWC** [comment]
Thank you very much for reply.

When I cliked componets tab, tomcat log showed these.
(attached all logs)
```
(Part of logs)
2018-06-05 05:44:26,307 ERROR UserCacheHolder:74 - Unable to fetch user...
2018-06-05 05:44:26,349 ERROR ComponentPortlet:1000 - Could not search components in backend 
2018-06-05 05:44:26,354 ERROR ComponentPortlet:956 - Problem retrieving all the Vendor names
05:44:26,696 ERROR [http-bio-8180-exec-9][PortletRequestDispatcherImpl:115] org.apache.jasper.JasperException: An exception occurred processing JSP page /html/components/view.jsp at line 40__37: <jsp:useBean id="mainLicenseIds" class="java.lang.String" scope="request"/>_38: <jsp:useBean id="name" class="java.lang.String" scope="request"/>_39: <jsp:useBean id="viewSize" type="java.lang.Integer" scope="request"/>_40: <jsp:useBean id="totalRows" type="java.lang.Integer" scope="request"/>_41: 42: <core_rt:set var="programmingLanguages" value=''/>_43: <core_rt:set var="operatingSystemsAutoC" value=''/>Stacktrace: [Sanitized]
05:44:26,699 ERROR [http-bio-8180-exec-9][PortletServlet:116] javax.portlet.PortletException: org.apache.jasper.JasperException: An exception occurred processing JSP page /html/components/view.jsp at line 40__37: <jsp:useBean id="mainLicenseIds" class="java.lang.String" scope="request"/>_38: <jsp:useBean id="name" class="java.lang.String" scope="request"/>_39: <jsp:useBean id="viewSize" type="java.lang.Integer" scope="request"/>_40: <jsp:useBean id="totalRows" type="java.lang.Integer" scope="request"/>_41: _42: <core_rt:set var="programmingLanguages" value=''/>_43: <core_rt:set var="operatingSystemsAutoC" value=''/>_Stacktrace: [Sanitized]
05:44:26,703 ERROR [http-bio-8180-exec-9][render_portlet_jsp:132] null
SEVERE: Servlet.service() for servlet jsp threw exception
SEVERE: Servlet.service() for servlet components Servlet threw exception
```
Console(firefox)
<img width="849" alt="component_firefox" src="https://user-images.githubusercontent.com/39894802/40961938-0e17e5e0-68df-11e8-95e9-f8b2e6e9acad.png">

and all log
[ERROR_ALL_TOMCAT.txt](https://github.com/eclipse/sw360/files/2071275/ERROR_ALL_TOMCAT.txt)

**Comment by maierthomas** [comment]
Hello, 

can you please send a screenshot of the tab `Preferences`
Also can you show me the last commit id of your master branch?

thanks!

**Comment by OST-SWC** [comment]
>can you please send a screenshot of the tab Preferences

Of course. 
<img width="851" alt="preferences" src="https://user-images.githubusercontent.com/39894802/41072348-301edb94-6a38-11e8-919b-c6b4435ef241.png">
![screenshot-2018-6-7-preferences-liferay](https://user-images.githubusercontent.com/39894802/41072379-559e5df4-6a38-11e8-88cc-aa0b801ec3a5.png)

>Also can you show me the last commit id of your master branch?

e10d8521177199494cabf1087884e0ac03621bb3

Thank you for comment.

**Comment by alexbrdn** [comment]
By the looks of your Preferences tab, it looks like you've been affected by #277. But you say you're at e10d852, which is the latest commit and already includes the fix. I'm confused a little. Maybe @maierthomas will give some insight. Meanwhile, can you check whether you can find the error messages from #277 in your tomcat log when you login?

**Comment by alexbrdn** [comment]
You can also check if your user is created in the couchdb.

**Comment by alexbrdn** [comment]
@maierthomas gave me the hint that your ERROR_ALL_TOMCAT.txt indicates that the portlet couldn't connect to backend at all:
>2018-06-05 05:44:26,307 ERROR UserCacheHolder:74 - Unable to fetch user...
 java.util.concurrent.ExecutionException: org.apache.thrift.transport.TTransportException: java.net.ConnectException: Connection refused (Connection refused)

check that the backend services are up and running by, for example, going to `http://<backend-host>:8080/users`

**Comment by OST-SWC** [comment]
Thank you for good comment.

> @maierthomas` gave me the hint that your ERROR_ALL_TOMCAT.txt indicates that the portlet couldn't connect to backend at all:

> check that the backend services are up and running by, for example, going to http://<backend-host>:8080/users

I check  : 8180/user  
( Because I changed  port 8080 to 8180 by change  tomcat's setting file) 
<img width="855" alt="users_service" src="https://user-images.githubusercontent.com/39894802/41213592-3e07c922-6d81-11e8-96ea-8a754edc6077.png">

Moreover I checked  8180/componet 
<img width="854" alt="components_service" src="https://user-images.githubusercontent.com/39894802/41213624-6ccd4f98-6d81-11e8-8274-8bb0cbdc2367.png">

I found some errors in tomcat log. (in catalina_02_liferay_login.txt)
[catalina_01_tomcat_start.txt](https://github.com/eclipse/sw360/files/2088756/catalina_01_tomcat_start.txt)
[catalina_02_liferay_login.txt](https://github.com/eclipse/sw360/files/2088757/catalina_02_liferay_login.txt)
[catalina_03_open_component_tab.txt](https://github.com/eclipse/sw360/files/2088787/catalina_03_open_component_tab.txt)


```
     16 2018-06-11 04:23:46,835 INFO  UserUtils:79 - Creating new user.
     17  2018-06-11 04:23:46,842 ERROR UserUtils:92 - Thrift exception when saving the user
     18  org.apache.thrift.transport.TTransportException: java.net.ConnectException: Connection refused (Connection refused)
     19         at org.apache.thrift.transport.THttpClient.flush(THttpClient.java:356)
     20         at org.apache.thrift.TServiceClient.sendBase(TServiceClient.java:73)
     21         at org.apache.thrift.TServiceClient.sendBase(TServiceClient.java:62)
     22         at org.eclipse.sw360.datahandler.thrift.users.UserService$Client.send_addUser(UserService.java:283)
     23         at org.eclipse.sw360.datahandler.thrift.users.UserService$Client.addUser(UserService.java:275)
     24         at org.eclipse.sw360.portal.users.UserUtils.synchronizeUserWithDatabase(UserUtils.java:82)
     25         at org.eclipse.sw360.portal.users.UserUtils.synchronizeUserWithDatabase(UserUtils.java:177)
     26         at org.eclipse.sw360.portal.users.LoginAction.run(LoginAction.java:37)
     27         at com.liferay.portal.kernel.events.InvokerAction.run(InvokerAction.java:41)
```

> You can also check if your user is created in the couchdb.

I also found my user name is not saved  in couchdb. (even if some databases are created)
<img width="631" alt="couchdb_databases" src="https://user-images.githubusercontent.com/39894802/41214038-0d403e2a-6d84-11e8-9523-507af261b526.png">


cf. master branch are not cheanged. e10d852

**Comment by OST-SWC** [comment]
Thank you for some comments. I could solve my problem. I could not find what is problem, however I could  solve this by  "ip addr flush dev docker" and restarting network .

**Comment by alexbrdn** [comment]
We'll write this up as another unsolved mistery.

**Comment by simpl0r** [comment]
Same issue here. "Components is temporarily unavailable" appears after a vanilla installation of sw360 on a ubuntu 18.04.02 using liferay-portal-tomcat-6.2-ce-ga5-20151119152357409, thrift 0.9.3, couchdb 2.3.1. Moreover, creating a new project throws "Request could not be processed". Creating new licenses works but accessing them throws " Error fetching license from backend". My backend.url=https://127.0.0.1:8080. Couchdb access was verified and seems to be ok. Catalina.out does not show any errors during startup.
