### ISSUE TITLE
Missing given name and last name for user search dialog (projects)

### ISSUE THREAD

**Issue by maierthomas** [eclipse/sw360#285]
The given and last name of **preselected** users are not visible
e.g. moderators or architects in the edit view of projects

![user-name-missing](https://user-images.githubusercontent.com/29916928/41034773-f5e64154-698a-11e8-8221-a132491d71d1.png)

**Comment by maierthomas** [comment]
check `searchUsers.js`

```
        function renderUserInputToFullData(entry) {
            return " , ," + entry + ", ," + entry;
        }
```

**Comment by mcjaeger** [comment]
is solved by now
