### ISSUE TITLE
License import should work incremental

### ISSUE THREAD

**Issue by blaumeiser-at-bosch** [eclipse/sw360#310]
As an open source officer, I want to import license information, e.g. from a company local database into the license db of SW360. This should be done in a way that this can be done several times without removing licenses not in the imported set,  but overwriting the previous information if the license has been imported in an older import run. This allows an organization to incrementally introduce SW360 in an already existing process with external artifacts maintained for OSM reasons., like a License List in Excel.

**Comment by maxhbr** [comment]
For this one would use the `externalIds`, which a license have, to remember the primary key from import. For that one would add either
- a new collumn to the license table in the lics file or
- a new table containing the mapping: shortname -> externalID

**Comment by maxhbr** [comment]
the first suggestion is already implemented: https://github.com/eclipse/sw360/blob/cfd7d7224102e0592bcffbe40ce8bd40dbaa1a87/libraries/commonIO/src/main/java/org/eclipse/sw360/commonIO/ConvertRecord.java#L406-L411
