### ISSUE TITLE
Admin entry in menu style is inconsistently, sometimes it is off-center

### ISSUE THREAD

**Issue by maxhbr** [eclipse/sw360#313]
If some pages are opened it looks normal:
![2018-07-09_10 20 07](https://user-images.githubusercontent.com/1187050/42447471-434847fe-837a-11e8-9380-a8a22b6cf99c.png)

but sometimes the admin menu entry is off-center:
![2018-07-09_10 20 20](https://user-images.githubusercontent.com/1187050/42447479-4da94086-837a-11e8-976a-fbc4de4b4295.png)

##

This happens in Chromium and Firefox

**Comment by mcjaeger** [comment]
I have seen this always being off center (also the Projects Menu with import item activated)

**Comment by mcjaeger** [comment]
with new design it is very clean

<img width="1016" alt="Screenshot 2021-03-25 at 22 37 39" src="https://user-images.githubusercontent.com/3418977/112547198-bc72b680-8dba-11eb-8497-50b1abb3b4d1.png">
