### ISSUE TITLE
Month and year selection for date fields is not available

### ISSUE THREAD

**Issue by aratib** [eclipse/sw360#320]
Month and year selection would help to edit date easily

**Comment by mcjaeger** [comment]
(from discussion) actually the issue cause some discussion what this is about, it is about that at the following place a user can directly select a month and year (imagine you would to go back to 1999 etc)

![image](https://user-images.githubusercontent.com/3418977/45029453-fcc98800-b048-11e8-9393-fd33670d26c1.png)

**Comment by aratib** [comment]
A pull request added on https://github.com/siemens/sw360/pulls
