### ISSUE TITLE
Data Lost Through Form Resubmission

### ISSUE THREAD

**Issue by alexbrdn** [eclipse/sw360#338]
When a user updates a project, then closes the browser tab and reopens it, the edit form gets resubmitted, but not with all the data, as one would expect. The portlet then performs an update of the project and _deletes_ all linked releases, linked projects, unchecked attachments, etc.

Testing with Chrome, revealed these lists of parameters submitted to portlet:
Normal update: javax.portlet.action, projectid, OWNER_ACCOUNTING_UNIT, PREEVALUATION_DEADLINE, SECURITY_RESPONSIBLES, CLEARING_TEAM, ATTACHMENTSFILENAME, STATE, ATTACHMENTSCHECK_STATUS, PROJECT_RESPONSIBLE, OWNER_GROUP, DESCRIPTION, PHASE_OUT_SINCE, RELEASE_ID_TO_USAGERELEASE_RELATION, WIKI, SYSTEM_TEST_START, HOMEPAGE, CONTRIBUTORS, ATTACHMENTSCREATED_COMMENT, SYSTEM_TEST_END, CLEARING_STATE, CREATED_BY, PROJECT_TYPE, ATTACHMENTSCHECKED_COMMENT, VISBILITY, RELEASE_ID_TO_USAGEMAINLINE_STATE, BUSINESS_UNIT, OWNER_COUNTRY, NAME, MODERATORS, ATTACHMENTSATTACHMENT_CONTENT_ID, VERSION, RELEASE_ID_TO_USAGEID, moderation_request_comment, DELIVERY_START, TAG, LEAD_ARCHITECT, PROJECT_OWNER, ATTACHMENTSATTACHMENT_TYPE

Form resubmittion: javax.portlet.action, projectid

Note, that we implemented [this workaround](https://github.com/sw360/sw360portal/pull/562) previously, when we didn't know what caused the data loss. 

Similar effect may be caused by resubmitting the component, release and other editing forms.

**Comment by alexbrdn** [comment]
The perfect solution is probably to prevent form resubmission at all

**Comment by mcjaeger** [comment]
was also discussed this week and solved.
