### ISSUE TITLE
Show object identifier (id) in REST resources

### ISSUE THREAD

**Issue by maierthomas** [eclipse/sw360#340]
Currently in the SW360 REST API all identifiers (ids) are ignored by jackson customization.
The id should be visible in the embedded object or at least in the detail information 'GET' request of a sw360 resource.

**Comment by mcjaeger** [comment]
actually, there is also the idea of showing the object identifier in the Web UI.

**Comment by mcjaeger** [comment]
and that has also been covered by now, for example:

<img width="842" alt="Screenshot 2021-03-25 at 22 29 10" src="https://user-images.githubusercontent.com/3418977/112546315-9698e200-8db9-11eb-857b-1cd7f6f013f1.png">
