### ISSUE TITLE
Prevent overriding of portal.properties (sw360-portlet)

### ISSUE THREAD

**Issue by maierthomas** [eclipse/sw360#344]
Each deployment overrides the configuration settings of portal.properties in sw360-portlet.
It should be possible to configure these settings also in e.g. sw360.properties (etc/sw360)

**Comment by mcjaeger** [comment]
(from discussion) one way could be to have a look if Liferay support a similar place for portal.properties like putting them into /etc/liferay or similar.

**Comment by lepokle** [comment]
@mcjaeger 
Can be closed from my point of view.

**Comment by mcjaeger** [comment]
agree.
