### ISSUE TITLE
Allow editing of "My Projects" list

### ISSUE THREAD

**Issue by tngraf** [eclipse/sw360#359]
The project list ('My Projects') shows only project that have been created by this user.
It would be great to have a possiblity to add or remove entries in this list.

**Comment by alexbrdn** [comment]
Just to second this: at least some users would like to see the projects where they are Project Responsible in this list

**Comment by mcjaeger** [comment]
so we shall have also the subscription for projects (which is there for releases, but apparently not used.

**Comment by mcjaeger** [comment]
multiple options now there:

<img width="604" alt="Screenshot 2021-03-25 at 22 24 58" src="https://user-images.githubusercontent.com/3418977/112545836-f642bd80-8db8-11eb-81a7-2e1715df42c4.png">
