### ISSUE TITLE
REST API extension: support more queries by externalIds, rename ressource path

### ISSUE THREAD

**Issue by innerjoin** [eclipse/sw360#361]
Extracted comment from #353 

@maierthomas and colleagues: I was just looking for this kind of query capability for SW360 right now, so good to see that you are already into that. I have one use case which I'm not sure you cover yet and one change request:
- Is it possible to query for the existence of an external ID? e.g. `api/projects/searchByExternalIds?project-ext` or `api/projects/searchByExternalIds?project-ext=*` would return all projects that have an external ID called `project-ext`, no matter what value is set for it. This would allow me to get rid of requesting all projects and filtering them on my side. Is this possible with the current implementation and if not, could you enhance the implementation to cover that?
- I would suggest to rename the endpoint from `searchByExternalIds` to `externalIds`. This would allow for future enhancements of the endpoint for scenarios like: _"Update all projects that have the external ID `X` with the value`Y` and change it's value to `Z`_".

**Comment by mcjaeger** [comment]
@innerjoin I think `Feedback for #353` makes it hard for persons reviewing the issue list because even myself, I have a hard time of remembering issue numbers.

**Comment by maierthomas** [comment]
@innerjoin we add the `seachByExternalIds` endpoint to `releases` and `components`.
See pull request #388 

I like your suggestion to search only by external id keys.
I will create a pull request which supports this feature by using a wildcard (*) as external id value.

**Comment by innerjoin** [comment]
@maierthomas I just tried the changes from #353 and it works very well, thank you. Unfortunately, I still have to do dozens of requests because I want to find all projects that have a certain external id as a **key**, not matter what it's value is. When can I expect the before mentioned pull request introducing wildcard support to be ready?

**Comment by innerjoin** [comment]
This is really important for both sides in terms of performance. While working with our internal staging server, which has 2833 projects, I observed the following stats:

Today: Without wildcard support for values:
- Nr. of Requests: 2834
- Time needed: ~20 min.

With wildcard support:
- Nr. of Requests: 1
- Time needed: 2 seconds*

_* assumption based on the existing api: `api/projects/searchByExternalIds?my.id=my-value`_

**Comment by maierthomas** [comment]
@innerjoin update
