### ISSUE TITLE
REST API: Creating project without linkedReleases causes problems on the web UI

### ISSUE THREAD

**Issue by bs-ondem** [eclipse/sw360#363]
When a user creates a project via the REST API and does not specify the field `linkedReleases` in the request, the project is not viewable on the web UI. 
The following error appears on the UI:
![projects_error](https://user-images.githubusercontent.com/20922706/45676275-a886d380-bb31-11e8-8c53-57bfa1d5ab92.png)

**Comment by gernot-h** [comment]
I think this is fixed, at least I never saw this in my tests. Perhaps fixed together with #434?

**Comment by mcjaeger** [comment]
I guess also
