### ISSUE TITLE
Display Name 'Uploaded By' and 'Relation' in  Attachment Usages 

### ISSUE THREAD

**Issue by Mukthi** [eclipse/sw360#370]
In SW360,  **Projects -> ProjectsName(Version) -> Attachment Usages** 

Two additional columns 'Uploaded By' and 'Relaton' should be displayed.

**Reason** :
- Reduce Manual effort for comparison
- When there are more than one reports(XML) is available for single component 'uploaded By' Info help us to to make selection easier. 
- 'Relation' column to help us to know whether the component is part of distribution.

**Comment by mcjaeger** [comment]
good point, actually uploader name and group would be helpful, questions:

* there is still space left
* have it two row
* mouse over
