### ISSUE TITLE
Skip components with relation 'Internal Use' in Generate License Info

### ISSUE THREAD

**Issue by Mukthi** [eclipse/sw360#371]
In SW360,
Projects -> ProjectName(Version) -> Linked Releases And Projects -> Generate License Info

- Skip the components with Relation 'Internal Use' 
-Display additional column  'Relation' in the list

**Reason :** 

- To  Reduce manual efforts for comparison 
- Internal components are not distributed to the customers hence information about these components  is not required in License information file

**Comment by mcjaeger** [comment]
I would prefer to have it being able to switch skipping on or off rather than just skipping component or relation types be default to avoid confusion to the users.

**Comment by mcjaeger** [comment]
it is there now, it can be selected which relations to skip and which not.
