### ISSUE TITLE
Going back and forth with browser buttons misses last viewed detail view section 

### ISSUE THREAD

**Issue by mcjaeger** [eclipse/sw360#373]
When navigating detail views and going forward and backwards between data sets, then the detail view jumps always back at the first detail view pane(mostly summary), which is annoying. It should remember the actual detail view shown.

Example: When jumping to a release data set from a project listing of releases by clicking the link, then going back to the project data set using the browser buttons, then, the summary (first) detail view is shown. Then, the user needs to do an additional click to jump to the actual last visited view.

**Comment by imaykay** [comment]
I am working on this issue (no assignment possible at the moment).

**Comment by imaykay** [comment]
Please review and test (s. https://github.com/eclipse/sw360/pull/443)
