### ISSUE TITLE
Reporting: Make separate template document for License Report

### ISSUE THREAD

**Issue by mcjaeger** [eclipse/sw360#376]
Currently, the license report (see screenshot) is a modified form of the License Disclosure Document:

![image](https://user-images.githubusercontent.com/3418977/46344918-fc6dde00-c642-11e8-8cdd-e8429a9034e0.png)

It should be a separate template document, copied from the existing template, allowing to have both documents in parallel.

This document should have - as with the current template documents - its premier location (overriding all other locations) in /etc/sw360. Otherwise, it shall be in the resources folder of the license info service so it is part of the *.war file.

**Comment by mcjaeger** [comment]
to be clarfied: contents in the footer.

**Comment by dreh23** [comment]
This can be closed

**Comment by mcjaeger** [comment]
right.
