### ISSUE TITLE
Delete Vendor of Releases

### ISSUE THREAD

**Issue by maierthomas** [eclipse/sw360#393]
If you delete vendors which are already mapped to releases,
the link `vendorId` in the release document will not be removed.
This will lead to some problems if you load the release or show linked releases in a project.

**Solution:**
In case of vendor deletion all links of this vendor (`vendorId in releases`) should be removed.
Maybe add python cleanup script for invalid vendorIds.

**Comment by mcjaeger** [comment]
just tested with deleting all vendors on the test system: all OK after that, views seem to work.
