### ISSUE TITLE
SW360 shall Display a warning that IE is not supported.

### ISSUE THREAD

**Issue by maierthomas** [eclipse/sw360#396]
Original title was "Update of responsibles like "Project Owner" "Project Manager" does not work in IE" because there is no warning that IE is not supported which should have been added a long time ago.

**Comment by mcjaeger** [comment]
is in:
![image](https://user-images.githubusercontent.com/3418977/49733622-49dd7b80-fc82-11e8-9e39-a7cdf8aaaa2f.png)
