### ISSUE TITLE
Update to Liferay 7.2 GA1

### ISSUE THREAD

**Issue by maxhbr** [eclipse/sw360#398]
There is an exmaple on how a portlet maven module should look like:
- https://github.com/liferay/liferay-blade-samples/blob/7.1/maven/apps/jsp-portlet/pom.xml

The corresponding generated archetype `mvn archetype:generate -Dfilter=liferay` looks broken and depends on `portal-service:7.0.0-m2`, which can not be found.

The following repository might have to be added:
```xml
	<repositories>
		<repository>
			<id>liferay-public</id>
			<url>https://repository-cdn.liferay.com/nexus/content/groups/public/</url>
		</repository>
	</repositories>
```

**Comment by maxhbr** [comment]
This also implies:
- regeneration of the lar files
- adoptions in chores / vagrant

**Comment by imaykay** [comment]
What needs to be done:
* Code changes: check https://dev.liferay.com/develop/tutorials/-/knowledge_base/7-0/whats-changed-and-what-hasnt and https://dev.liferay.com/de/develop/reference/-/knowledge_base/7-0/breaking-changes and see if something needs to be changed in the code
* Build changes: upgrade Maven build, see https://dev.liferay.com/de/develop/tutorials/-/knowledge_base/7-0/upgrading-the-liferay-maven-build
  * liferay-maven-plugin exists no longer and has to be replaced with smaller plugins as needed
  * liferay dependencies have been renamed and need to be changed
* System changes - for new installations: Upgrade liferay in vagrant and docker setup
* System changes - for existing installations: Do we provide our own update guide? Or do we just refer to the original upgrade guide https://dev.liferay.com/de/discover/deployment/-/knowledge_base/7-0/upgrading-to-liferay-7 ? There are pros and cons for both ways...

**Comment by lepokle** [comment]
needed functionality:
- core
- user managementhhg

**Comment by mcjaeger** [comment]
(from discussion) existing installation need to care for their own upgrade:
https://github.com/fossology/fossology/pull/1283

Also for migration to anew liferay instance: the could be migration of database only and then use the user export and import feature (for migrating the database entries of user management from one instance (6.2) to another (7.1).

**Comment by imaykay** [comment]
@mcjaeger the reference to the fossology issue was not intended, was it? If so, why?

**Comment by mcjaeger** [comment]
@imaykay no was not intended
