### ISSUE TITLE
Improve SW360 Deployment based on experience in Bosch setup

### ISSUE THREAD

**Issue by blaumeiser-at-bosch** [eclipse/sw360#407]
Bosch is currently building up its SW360 service for internal use. Experiences made during this deployment will be played back into the e.g. the chores repo

**Comment by mcjaeger** [comment]
also for this one it might be also good to have an issue opened at the chores repo - or in other words, this is does not seem to be describe how a task can improve / modify sw360 to get this issue covered.

**Comment by blaumeiser-at-bosch** [comment]
You are right, I wasn't aware that we collect the issue for chores there. Shall I close this and create another one in chores? Or can you move it, there is a feature in Github lately to do so, but I am not allowed due to missing rights.

**Comment by mcjaeger** [comment]
Move it to sw360chores? it is fine like that. maybe it would help to express that this is a "kind of story of stories issue" in the description.

**Comment by blaumeiser-at-bosch** [comment]
Obsolete
