### ISSUE TITLE
Use SW360 data within SW360antenna workflow

### ISSUE THREAD

**Issue by blaumeiser-at-bosch** [eclipse/sw360#408]
As a project using open source, I want to run Antenna within the continuous integration mechanism to run open source management, so that I only have to get involved, if concrete actions are needed.

Use Case in detail:
Prerequisite:
A project has a list of dependencies used within the project. Manually maintained or detected by an external mechanism. The list is e.g. provided as an antenna config file.

Expected Reaction (from SW360 perspective):
- Antenna run retrieves the component (release) metadata from SW360.
- Antenna updates the Project information in SW360

**Comment by mcjaeger** [comment]
The use case is indeed interesting, but could you pls point out to what regard this is a sw360 issue (and not in [sw360antenna](https://github.com/eclipse/antenna/issues) - or maybe help for better understanding the issue w.r.t. what needs to be done in sw360 in order to cover this use case?

**Comment by blaumeiser-at-bosch** [comment]
You are right, this is mainly an Antenna issue, but we expect also minor changes in SW360. That is why I opened up this issue. From my past experience it helps to document the greater scope of a change by giving the different changes required to implement a use case a common aggregation that expresses the linkage.

**Comment by blaumeiser-at-bosch** [comment]
Obsolete
