### ISSUE TITLE
Self links should be forbidden at all

### ISSUE THREAD

**Issue by mcjaeger** [eclipse/sw360#410]
generally, the self links in the UI are almost extinct, however, in the "linked releases hierarchy" view in the project details, you can open endlessly the hierarchy. Also the same for the releases side:

![image](https://user-images.githubusercontent.com/3418977/49930269-84365b00-fec4-11e8-93a7-f4ebbd81f6b6.png)

Maybe the self-link should be forbidden at creation of the reference.

**Comment by mcjaeger** [comment]
I think it would be good to stop users from creating self link for this first.

**Comment by nutan1st** [comment]
I would like to look into this issue

**Comment by mcjaeger** [comment]
actually, it seems to be there for linked projects too. https://github.com/eclipse/sw360/pull/469

**Comment by nutanv1contr** [comment]
Now self link link is forbidden for both release and project.However cyclic link still exists for project.I have created a separate issue for the #546

**Comment by mcjaeger** [comment]
second part was here: https://github.com/eclipse/sw360/pull/709
