### ISSUE TITLE
Dependencies update of web jars or java script dependencies

### ISSUE THREAD

**Issue by mcjaeger** [eclipse/sw360#412]
Generally, all maven declared dependencies should be drawn up to latest stable. However, some of the might require testing. In particular we would need the Web jars dependencies:

https://github.com/eclipse/sw360/blob/master/frontend/sw360-portlet/pom.xml

updated to latest stable (if new versions do not introduce a heavily breaking API of course) and tested.

**Comment by lepokle** [comment]
See https://github.com/eclipse/sw360/pull/428

**Comment by mcjaeger** [comment]
That is OK, because we also have this banner message when someone attempts using it: https://github.com/eclipse/sw360/pull/397
