### ISSUE TITLE
Dependencies update of Ektorp

### ISSUE THREAD

**Issue by mcjaeger** [eclipse/sw360#413]
Updating the dependecies here:

https://github.com/eclipse/sw360/blob/master/pom.xml

(BTW: pls check second declaration here: https://github.com/eclipse/sw360/blob/master/libraries/lib-datahandler/pom.xml )

to latest stable of ektorp:

https://github.com/helun/Ektorp/releases

**Comment by imaykay** [comment]
I am working on this issue (no assignment possible at the moment).

**Comment by imaykay** [comment]
Please review and test.

**Comment by imaykay** [comment]
Fixed merge commits on https://github.com/eclipse/sw360/pull/436
