### ISSUE TITLE
Dependencies update of couchdb-lucene

### ISSUE THREAD

**Issue by mcjaeger** [eclipse/sw360#414]
Actually, version 1.X of couchdb-lucene does not appear compatible with couchdb 2.X

In order to migrate to couchdb 2.X (and have search functionality) we would need to update to couchdb-lucene 2.X

**Comment by lepokle** [comment]
May you please clarify this a little bit?

> Actually, version 1.X of couchdb-lucene does not appear compatible with couchdb 1.X
Do you mean "with couchdb 2.X"? The git repo is even stating
> CouchDB-Lucene works with all version of CouchDB from 0.10 upwards.

The sw360chores setup using different docker containers already uses couchdb-lucene 2.1.0 (latest version) and it seems to work.

The sw360vagrant repo seems to use an older version. Should this be updated in this issue? Are there any other repositories for setting up an environment?

Upgrade of couchdb is not part of this issue, correct?

Thank you!

**Comment by mcjaeger** [comment]
(from discussion) check if the ektorp lucene subproject is required

**Comment by mcjaeger** [comment]
(from discussion) maybe check if the lucene framework is actually required

**Comment by lepokle** [comment]
Check if Lucene is really needed for the functionality of SW360

**Comment by lepokle** [comment]
Result: CouchDB seems still lack the support of a full text index, even in 2.3. Therefore Lucene is still necessary to manage the search functionality in SW360.

@imaykay Maybe you can check if ektorp lucene is still necessary.

**Comment by mcjaeger** [comment]
I think we have an issue with this sw360-added patch:

https://github.com/sw360/sw360vagrant/blob/f458f72769c083a82ee8f76489e5152abf7a8a5a/shared/couchdb-lucene.patch

which is not merged on the couchdb-lucene even though there were several releases since then:

https://github.com/rnewson/couchdb-lucene/pull/152/files

-> question is if this PR would be required with the latest release of couchdb lucene ...

**Comment by imaykay** [comment]
Regarding the need of ektorplucene: even though it is very old and seems to be more or less dead, I would not replace it eagerly. There are some usages that can be found by searching for usages of LuceneAwareCouchDbConnector and plain ektorp seems to not support couchdb-lucene (because this is not part of the plain couchdb).

Regarding the question of the patch I hope @lepokle will have a quick answer as he already had the deepdive into couchdb-lucene and the different stacks.

**Comment by lepokle** [comment]
As far as I can see the patch is still necessary for using couchdb-lucene with a context other then root (/).
