### ISSUE TITLE
Test with Couchdb 2.2 or later (2.3.1)

### ISSUE THREAD

**Issue by mcjaeger** [eclipse/sw360#415]
after the dependencies updates have been performed, we need to make test with couchdb 2.2 - in the ideal case on an updated productive test.

**Comment by bs-matil** [comment]
I would love to see couchdb upgraded so I'm looking for the missing parts. This Issue states that couchdb 2.x works just fine and only the query endpoint changes https://github.com/rnewson/couchdb-lucene/issues/259 are there any other problems known here?

**Comment by bs-matil** [comment]
While understanding the issue with all of this I found the following:
* currently couchdb lucene is used with an ektorp wrapper https://github.com/ldriscoll/ektorplucene which is utterly unmaintained and will not work with newer ektorp versions. 
* all we actually need is a new (maybe self written) provider which wraps the lucene index schema.
* The index settings are currently anyways stored as plaintext for example e.g. https://github.com/eclipse/sw360/blob/a1a92a975df0773644972a119fdf1852ef4227b9/backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/ComponentSearchHandler.java#L36
* The only thing we have to redo is the wrapping of the LuceneDocument and we have to rebuild the complete querie path and how the query results are converted back to thrift objects. Which seems to be the most compley issue here.

Still I only try to unterstand this issue and scratched only the sureface. Any help is appreciated.

**Comment by mcjaeger** [comment]
for now, sw360 runs with couchdb 2.X:

https://github.com/sw360/sw360vagrant/wiki

and also the support for couchdb 3 is under testing:

https://github.com/sw360/sw360vagrant/pull/38
