### ISSUE TITLE
Visibility of attachment usage without any WRITE permission

### ISSUE THREAD

**Issue by maierthomas** [eclipse/sw360#426]
Currently all users can try to change the attachment usage for projects in the view mode.
Therefore users can check/uncheck attachment usages and the everyone can see the "save attachment usage" button. In case that users have no admin privileges or in general no write access an error occurs as liferay banner after saving.

For users without write access the button should not be visible and all checkbox should be disabled.

**Comment by smrutis1** [comment]
I would like to work on it.
