### ISSUE TITLE
Update to recent version of thrift

### ISSUE THREAD

**Issue by maxhbr** [eclipse/sw360#429]
we currently use thrift version 0.9.3 which is rather outdated. It would be better to migrate to version 0.12.0. Especially since thrift 0.9.3 can no longer be compiled on ubuntu 18.04 due to incompatibility of openssl.

**Comment by maxhbr** [comment]
Corresponding PR: https://github.com/eclipse/sw360/pull/431

**Comment by mcjaeger** [comment]
well today it is 0.14 ... https://github.com/eclipse/sw360/issues/1114 closing here
