### ISSUE TITLE
Infinity loop for attachment usages by expanding empty projects

### ISSUE THREAD

**Issue by maierthomas** [eclipse/sw360#444]
Type: Project
Page: Detail View
Tab: Attachment Usage

If a user expands an empty (no subprojects, no releases) project in the attachment usage view, <br> the system tries to expand this project endless.

**Comment by mcjaeger** [comment]
solved:

<img width="798" alt="Screenshot 2021-03-25 at 23 03 30" src="https://user-images.githubusercontent.com/3418977/112549601-59831e80-8dbe-11eb-9a4a-29af9d93ff7f.png">
