### ISSUE TITLE
UR errors / glitches when editing

### ISSUE THREAD

**Issue by mcjaeger** [eclipse/sw360#468]
Stuff when working on the component portlet when testing https://github.com/eclipse/sw360/pull/458

1. Components:

Each time user tab out of component name field , application shows a message "To Avoid duplicate components, check there similar ones! Does yours already"

2. Releases:

If user tries to add a new release with any of the existing release name then on click of Add release , application gives an error message "Components is temporarily unavailable." and shows a blank screen.

**Comment by nutanv1contr** [comment]
I would like to work on this issue.

**Comment by mcjaeger** [comment]
(from discussion) let's focus on the second point only.
