### ISSUE TITLE
Missing datatables.js in frontend/sw360-portlet/src/main/webapp/js/

### ISSUE THREAD

**Issue by longnv519** [eclipse/sw360#479]
Hi everyone,

I would like to add new issue now!
We have no any file name "datatables.js" in current SW360 source code, but this file is required everywhere and makes almost of "html data table" fail to load.

Bellow picture is an error example:
![error](https://user-images.githubusercontent.com/34670763/53547024-76f24980-3b60-11e9-92ab-3f5f716689ba.png)

As I see, put "datatables.js" from [https://datatables.net/download/](url) into "frontend/sw360-portlet/src/main/webapp/js/" can solve this problem.

**Comment by mcjaeger** [comment]
maybe there has been a recent PR merge that has led to this error, because normally, this table is shown, just tested this week two pull requests coming along this table (every time a user want to pick a release form a component, this table is shown). Thanks for pointing this out, needs check.

**Comment by longnv519** [comment]
@mcjaeger Of course, it's the latest commit:

![version](https://user-images.githubusercontent.com/34670763/53548844-28937980-3b65-11e9-959d-2e22e6fe52b3.png)

**Comment by longnv519** [comment]
One more reason could be considered, some how the js lib file "datatables.js" has been called from web cache/browser cache (Maybe "datatables.js" was stored in cache from older source code).
That mean even you don't have it in the source code, the testing still passed.

**Comment by mcjaeger** [comment]
closed, fixed with liferay 7.2 because there are no manual includes anymore.
