### ISSUE TITLE
REST API: (undocumented) create/upload attachments feature

### ISSUE THREAD

**Issue by gernot-h** [eclipse/sw360#485]
$SUBJECT basically says it all: REST API currently lacks support to create/upload an attachment.

This is an essential task for many SW360 use cases, e.g. to add releases with attachments to be processed by open source clearing team. Currently, I can create components and relases via REST, but file upload still has to be performed via web UI.

**Comment by longnv519** [comment]
Hi @gernot-h 
Actually, current REST API does support to upload an attachment.
Let's see some codes:

https://github.com/eclipse/sw360/blob/e9099300a66b5a65b62d7cc5fd2f802b71c834e0/rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/component/ComponentController.java#L207

and

https://github.com/eclipse/sw360/blob/e9099300a66b5a65b62d7cc5fd2f802b71c834e0/rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/release/ReleaseController.java#L198

**Comment by gernot-h** [comment]
Oh, that's cool, thanks! I will try it...

However, I see no traces of it in https://github.com/eclipse/sw360/tree/master/rest/resource-server/src/docs/asciidoc, so it's undocumented yet, right?

**Comment by gernot-h** [comment]
Unfortunately, I don't seem to be able to construct a correct request. :-( 

After several tries, I was able to create a request with the needed "file" and "attachment" part (I assume the latter shall contain JSON-encoded metadata?), but now the server says "Content type 'application/octet-stream' not supported" - so I'm in desparate need of the usual "curl" example shown in the documentation... :)

**Comment by longnv519** [comment]
Please try this one, it works for me:
`curl -i -X POST -H "Content-Type: multipart/form-data" -H "Content-Type: multipart/mixed" -F file=@"/path/to/file" -F attachment={"filename": ""};type=application/json' --header "Authorization: bearer {your-identify}" http://localhost:8080/resource/api/releases/{release-id}/attachments`

**Comment by gernot-h** [comment]
Cool, thanks for figuring this out!! This seems to work perfectly! Just successfully uploaded text and binary files of various sizes. :-D Whoever implemented this, I owe her/him a big thank you as this will save me a lot of hassle... (So far I used Selenium web scraping to automate file uploads :) ).

**Comment by gernot-h** [comment]
I wonder why the API insists of receiving the "attachment" part while it actually ignores its content. :)

**Comment by longnv519** [comment]
It's no big deal, you're welcome

**Comment by mcjaeger** [comment]
actually resolved apparently by discussion. Updates also related to: https://github.com/eclipse/sw360/pull/518
