### ISSUE TITLE
REST API: link releases to project / update project

### ISSUE THREAD

**Issue by gernot-h** [eclipse/sw360#486]
It seems impossible to link releases to existing projects via REST API - at least I have no clue how to do it.

Documentation doesn't mention possibility to update a project, PATCH request seems to be unsupported for api/projects. 

If I understand #434 correctly, it should be possible to set linkedReleases when creating a new project, but I also don't understand how this could be done - so if this is possible, please also document the syntax to be used for setting linkedReleases in the POST request in REST API documentation.

TIA!

**Comment by mcjaeger** [comment]
merged at https://github.com/eclipse/sw360/pull/525
