### ISSUE TITLE
Overloaded after linking a project with a large amount of components

### ISSUE THREAD

**Issue by mctungnh** [eclipse/sw360#492]
I have about 2000 components in my local SW360 application (version: 3.4.0 | commit 3a8562f). After linking one of my project with all components, I browsed in the project, SW360 was overloaded and couldn't display "Linked Releases And Projects" field.

Below is the error log:

![memory_error](https://user-images.githubusercontent.com/48663916/54504902-4421c100-4968-11e9-97be-e119c7b01051.png)

**Comment by mcjaeger** [comment]
please see

`$TOMCAT_HOME/bin/setenv.sh` 

and check the Java heap space setting which is for your tomcat container, something like

`-Xmx1024m`

Maybe it is set to 1GB also in your system. If you habe 8GB of RAM, it could be easily 2GB or 3GB ...

**Comment by mctungnh** [comment]
I worked. Thanks for your support!
