### ISSUE TITLE
Sending to FOSSology "Error" is confusing users

### ISSUE THREAD

**Issue by smrutis1** [eclipse/sw360#494]
We should remove the fossology sending feature or we should actually display a different error message which says that maybe the fossology link is not configured. right now users think of sending the stuff to fossology to get a clearing and are upset that there is "error" which implies to them that they will have a clearing.

Maybe there should be a user dialog message and then there is nothing written then as status or something like "FOSSology not configured"

**Comment by mcjaeger** [comment]
(from discussion)
* app should check on the startup time if fossology connection works. if not -> show disable icon on pages
* then, in admin - fossology menu item, one could re-call "Check Connection" and if that works, the application shall display a full (normal) fossology icon to indicate a working connection.
