### ISSUE TITLE
Create Documentation: codescoop.thrift (like other Thrift Files)

### ISSUE THREAD

**Issue by mcjaeger** [eclipse/sw360#521]
The internal thrift API is a API for developers of SW360. Therefore the thrift files should documentation.  Documentation for this file:

https://github.com/eclipse/sw360/blob/master/libraries/lib-datahandler/src/main/thrift/codescoop.thrift

should be added

**Comment by blaumeiser-at-bosch** [comment]
@mcjaeger Can this be closed?

**Comment by mcjaeger** [comment]
yes, because we moved code scoop
