### ISSUE TITLE
Component(Spreadsheet export): Duplicate columns in the spreadsheet export of "components with releases"

### ISSUE THREAD

**Issue by nutanv1contr** [eclipse/sw360#541]
**Steps to reproduce:**
1.Go to "Components" tab and select "Components with release" from the export to spreadsheet drop down then click on export to spreadsheet.
2.Download the spreadsheet and open it.
**Actual Result:**
1.There will be two columns with name as "component type" and "release: component type" with same data.

**Expected results:**
There should not be duplicate column in the spreadsheet.

**Comment by mcjaeger** [comment]
it is not necessarily a bug, since this is exporting the raw data ...

**Comment by mcjaeger** [comment]
has now a prefix for all the attributes fro the release data set:

<img width="599" alt="Screenshot 2021-03-29 at 23 10 55" src="https://user-images.githubusercontent.com/3418977/112900655-138ec900-90e4-11eb-8b4b-35ad5fd51cf5.png">
