### ISSUE TITLE
REST API: remove custom access tokens

### ISSUE THREAD

**Issue by imaykay** [eclipse/sw360#544]
Part 3 of #512 

The current implementation of custom access tokens that every user can generate on his own if the property `rest.apitoken.generator.enable=true` in `sw360.properties` is set, should be removed since we by then will have better ways to deal with SSO environments to get access tokens for the REST API.

There is no need to finish this issue before #512 is useable because the feature can just be disabled. But in my opinion it would be cleaner to remove the code.

In addition, the documentation in this wiki and the generated api-guide might need some rework.

**Comment by mcjaeger** [comment]
ove rthe time, it turned out that custom access tokens are quite useful for some setups of SW360

**Comment by mcjaeger** [comment]
(not removing them)
