### ISSUE TITLE
SW360 don't generate the license information with suffix "+"(Exp: GPL-2.0+,...).

### ISSUE THREAD

**Issue by BinhTH-tsdv** [eclipse/sw360#555]
.rdf file contains license with suffix "+". For ex: GPL-2.0+, LGPL-2.1+, GPL-3.0+, ..., but SW360 don't generate the license information.

In FOSSology, the license information include GPL-2.0+, LGPL-2.0+ LGPL-2.1+, follow:
![image](https://user-images.githubusercontent.com/39551943/59240733-34e0a580-8c2f-11e9-951b-bf6e140bfe99.png)

But SW360 generate the xhtml file. The xhtml file don't have  the license as: GPL-2.0+, LGPL-2.0+, LGPL-2.1+. Follow:
![image](https://user-images.githubusercontent.com/39551943/59241021-32328000-8c30-11e9-8d94-1c2fc2a1ad02.png)

Version: all commit.

**PLEASE HELP ME.**

**Comment by BinhTH-tsdv** [comment]
After a period of time, I knew that the issue belong about FOSSology. 
I'd like to close the ticket.

**Comment by bs-jokri** [comment]
@BinhTH-tsdv great that you found the solution to your problem and thanks for sharing your insights.
