### ISSUE TITLE
Display missing elements of the component tab

### ISSUE THREAD

**Issue by BinhTH-tsdv** [eclipse/sw360#557]
I added ~1000 components. I click on component tab, but the screen display only 200 components.
Screen:
![image](https://user-images.githubusercontent.com/39551943/59252341-1f32a680-8c56-11e9-99e0-63b4221d5745.png)

VERSION: 3.4.0- COMMIT: 3a8562f
Is this bug of the SW360?

**PLEASE HELP ME?**

**Comment by mcjaeger** [comment]
look like a bug

**Comment by hieupvtsdv** [comment]
This is not a bug. But it is a feature.
You can config 'DEFAULT_VIEW_SIZE' at line 43 in:
sw360/frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/common/CustomFieldHelper.java 

Example: I set DEFAULT_VIEW_SIZE = 1500;

![setlimit](https://user-images.githubusercontent.com/46513598/62511777-6ba5f700-b83f-11e9-9112-34b925937127.png)

**Comment by lepokle** [comment]
@mcjaeger should that be closed?
