### ISSUE TITLE
Project UI : Set to default text feature is not working correctly for License info header

### ISSUE THREAD

**Issue by nutanv1contr** [eclipse/sw360#559]
Steps to reproduce;
1.Open project in edit mode.
2.Go to administration tab and click on "Set to Default Text" button under License Info Header.

Actual Result:
1.If the text contains  double quote then the corresponding texts will not be displayed on the screen.
Expected result:
1.The license info header should be displayed as it is by adding "Set to Default Text".

**Comment by akapti** [comment]
Tested the changes, and functionality is working as expected.
Double quoted text is not getting removed when "Set to Default Text" button is clicked.
