### ISSUE TITLE
Project UI: It must not be possible to assign a project to the Clearing Team 'Unknown'

### ISSUE THREAD

**Issue by akapti** [eclipse/sw360#563]
If a project is assigned to the clearing team 'Unknown' we do not known where it really belongs to. This must not happen.
We have many projects that are assign to 'Unknown'.
Saving a project must only be possible for a valid clearing team. 'Unknown' shall get removed from the combo box.

![image](https://user-images.githubusercontent.com/50870174/59583430-e765ac00-90f8-11e9-9097-7e93bd566b06.png)

**Comment by maxhbr** [comment]
I think enforcing the setting of a clearing team is a harsh restriction and is not applicable to all instances of SW360. I would prefer to keep the `Unknown` default. Especially since it might be necessary to unset that value or maybe there is no valid choice.

(ping @mcjaeger )
