### ISSUE TITLE
Project UI : Set to default text feature is not working correctly for Obligation.

### ISSUE THREAD

**Issue by nutanv1contr** [eclipse/sw360#582]
Steps to reproduce;
1.Open project in edit mode.
2.Go to administration tab and click on "Set to Default Text" button under Obligation.
3.If the text contains double quote then the corresponding texts will not be displayed on the screen.

Need to look for all of such occurrences and fix them if similar behavior exist.

**Comment by mcjaeger** [comment]
it is about this text field

![Screenshot 2019-10-15 at 10 15 01](https://user-images.githubusercontent.com/3418977/66813415-fe949900-ef34-11e9-90fd-09a88c67795a.png)

**Comment by nutanv1contr** [comment]
> it is about this text field
> 
> ![Screenshot 2019-10-15 at 10 15 01](https://user-images.githubusercontent.com/3418977/66813415-fe949900-ef34-11e9-90fd-09a88c67795a.png)

Yes @mcjaeger .
