### ISSUE TITLE
Project UI: License Obligation Tracker at Project Level

### ISSUE THREAD

**Issue by akapti** [eclipse/sw360#594]
Feature to read all obligation from the CLI files of linked components and display the same in "Obligation Tab" at project level.

* Should display linked components
* Display Main License and Other License (concluded)
* Upon selection of license, should display the corresponding obligation.
* Each obligations should have an action field and comment field and corresponding files of the selected license. (as displayed in the attached picture)

[Clixml-Licenses_with_Obligations.zip](https://github.com/eclipse/sw360/files/3425256/Clixml-Licenses_with_Obligations.zip)

(from discussion) by Michael
* there is admin tab which contains also license information
* the licensing part from the admin tab should be maybe moved to a joint licensing or obligation view

![image](https://user-images.githubusercontent.com/50870174/61769443-eb779e80-ae07-11e9-9e55-96df4e37deda.png)

**Comment by mcjaeger** [comment]
I think the basic version is there
