### ISSUE TITLE
FOSSology integration refactoring

### ISSUE THREAD

**Issue by mcjaeger** [eclipse/sw360#607]
The current FOSSology integration is based on the ssh connection using the command line tools.

The goal is to replace the ssh connection with an integration using the REST API of FOSSology.

General:
* Replace ssh code with REST code

Configuration could be simplified:
* URL, login information which is a token (access key) now
* One incoming folder where the FOSSology uploads

FOSSology Admin Portlet:
* Configuration for REST Connectivity
* Start up check for if config of fossology is working (and thus icon is active)

Workflow:
* Source code must be there
* Send source code attachment to FOSSology to given folder using given technical user's access key ("token")
* Trigger scan (just a default set of scan options)
* Trigger report
* Wait for report gen
* Download Report (SPDX Document) and attach it as component license information attachment

Specialities:
* external tool requests uses a source code attachment -> external tool request reference to source code attachment shall lock it
* Status updates shall be refreshed by user at first iteration
* Report format is spdx2 (other do not make sense right now)
* Downloaded report in spdx2 format as component license information type attachment

Limitations, scope:
* make the first version just focussing on one (technical user) loads to fossology into one predefined folder (setting in sw360 needs the folder id, and not the name)
* remove fossology button at projects listing (resulting in a list of releases) and focus only at the fossology sending from the context of a release.
* focus of a release could be at
  * release overview of components
  * clearing status in release
  * clearing status, list of releases, for each release also one button

**Comment by mcjaeger** [comment]
(from discussion)
* attachments shall not be locked (because in FOSSologm, it is likely that the user finds out that the attachment is wrong, thus the user should be easily able to replace it.
* rather, the status enum could be extended with, for example, the value `outdated`.
* The `report available` should also kick in if the `component license information (xml)` file type is present. Accordingly, the `report approved` for approved / confirmed attachments of the same type.
* The attachment could be renamed for a file name `releasename-version-YYYYMMDD-HHMM-SPDX.rdf` for this release, because users will download them, iand multiple files with the same will be confusing.

**Comment by gernot-h** [comment]
Some Siemens departments seem to prefer to organize Fossology folders by component, not by project. Would it be possible to somehow support this, too - for example by allowing a target folder setting per attachment?

A great plus would also if we could set these IDs and trigger Fossology uploads via REST API.
