### ISSUE TITLE
Merge wizard for releases

### ISSUE THREAD

**Issue by mcjaeger** [eclipse/sw360#628]
Using the component merge request, the merge wizard for releases should be added with the same approach / similar approach, because only releases from the same component shall be merged, so the initial search is maybe different.

Note that the release is referenced in projects much more often, as well:
* there are more complex fields
* attachment usage might be affected
* project release relation
* attachments:
  * **source attachments are equal** from both releases (as well as other attachments) : merge (but mind the attachment usage and external tool requests (which should be merged to the most progressed one)
  * **source attachments are different** from both releases: should not be, second release necessary, do not merge, user has do clean up first.
* external tool requests

**Comment by lepokle** [comment]
Releases may not be merged if there are any open or pending moderation requests for them (#630)

**Comment by lepokle** [comment]
Form discussion:
- Two release can be merged if at least one pair of source attachments is equals
- source attachment attributes from target are kept
- Not equal source attachments are merged as any other attachments (by selection)
- clearing state is recalculated automatically

**Comment by gernot-h** [comment]
I think this is already implemented and can be closed, no?
