### ISSUE TITLE
Merges need check for moderation requests

### ISSUE THREAD

**Issue by mcjaeger** [eclipse/sw360#630]
For Component (#199) and releases (#628) and vendors (#629), there shall be a check if the are any open moderation requests for the affected documents. If these exist, there should be a message to the user that moderation requests should be resolved first before being able to perform the merge.

For all merge requests, the allowed users (clearing_admin, sw360_admin, admin) shall be able to merge directly, without moderation request. Other users are just not allowed for that.

**Comment by lepokle** [comment]
This is already done for Components.

**Comment by lepokle** [comment]
This will be done during the main tickets.
