### ISSUE TITLE
Bug (License UI): Display link to license generates wrong url [Liferay 7 only]

### ISSUE THREAD

**Issue by akapti** [eclipse/sw360#635]
**Description:**
- Clicking on `Main Licenses` hyperlink in _`Components tab`_ opens `Not Found` page.
example: `AGPL-3.0`.
![image](https://user-images.githubusercontent.com/50870174/64340227-46a1d100-d003-11e9-96d2-a639c4aea776.png)

- though the license is present in _`Licenses tab`_, and one can open the detailed view as shown in below screenshot.

![image](https://user-images.githubusercontent.com/50870174/64340285-6507cc80-d003-11e9-9e4b-2b6909313b94.png)

- Similarly, the issue is present in _`Component Details`_ and _`Release Details`_ page.
Clicking on `Main Licenses` hyperlink in `Summary` tab gets redirected to _`Component Details`_ or _`Release Details`_ page.
Component Details Page screenshot:
![image](https://user-images.githubusercontent.com/50870174/64340535-0858e180-d004-11e9-8c00-8ef8f057b46b.png)

This issue is present in Liferay 7, and might be because `FriendlyURL` for _`license portlet`_ returns `/licenses1` instead of `/licenses`

**Comment by lepokle** [comment]
Hi @akapti,
thanks for the great analysis! It is just a misconfiguration inside liferay. I've pushed a new configuration file for private pages.

If someone does not want to reimport all private pages, please follow the following steps:

1. Login as Liferay Admin
1. Goto Licenses
1. Click on the `cog` at the top right corner of the page
![image](https://user-images.githubusercontent.com/499823/65372864-15b5d300-dc76-11e9-8521-f21e4b3238a9.png)
1. Change the friendly url to `/licenses`
![image](https://user-images.githubusercontent.com/499823/65372871-2d8d5700-dc76-11e9-8ab0-81b9fb315074.png)
