### ISSUE TITLE
How to add project sw360 to eclipse?

### ISSUE THREAD

**Issue by cuongvt93** [eclipse/sw360#637]
How to add project sw360 to eclipse.
I try import it to my eclipse tool, but it always errors when i'm doing "Maven update project".
Thanks for your support!

**Comment by nutanv1contr** [comment]
I had to explicitly add the dependent project/libraries to build path. for most of the cases it is 'datahandler' .
Steps:
1. Perform mvn clean install. 
2. Right click on project>>Java Build Path>>Libraries>>Add JARs and add datahandler to the build path.

**Comment by cuongvt93** [comment]
> I had to explicitly add the dependent project/libraries to build path. for most of the cases it is 'datahandler' .
> Steps:
> 
> 1. Perform mvn clean install.
> 2. Right click on project>>Java Build Path>>Libraries>>Add JARs and add datahandler to the build path.

Thanks for your answers, i will re import.

**Comment by lepokle** [comment]
Did you import directly in eclipse? I had good experiences with running 
```
mvn eclipse:eclipse
```
from command line and then selection `Open existing project` inside eclipse.
Since LR7, there should be no manual steps needed after import.

**Comment by lepokle** [comment]
@cuongvt93 
Please close the ticket if question is answered.
