### ISSUE TITLE
Licenses cannot be set inside Release of a component

### ISSUE THREAD

**Issue by lepokle** [eclipse/sw360#639]

**Comment by mcjaeger** [comment]
seem to work for me:
* go to a release
* edit
* select a license 
* Save
-> license is there in view mode.

What is the issue exactly?

**Comment by lepokle** [comment]
Hi @mcjaeger ,
it seems that there are two license field on the edit mask:
![image](https://user-images.githubusercontent.com/499823/65372954-f8353900-dc76-11e9-89cf-aa6eb9d599f7.png)
(Row 4, Column2) and (Row 7, Column1).

The second field is not updated therefore I thought it did not work.

Is there any other field missing? Or can the second fields just be removed?

**Comment by lepokle** [comment]
Seems to be fixed with #654. Seems I was not on master.
