### ISSUE TITLE
REST: Get component by name not working with name contain character "+"

### ISSUE THREAD

**Issue by hieupvtsdv** [eclipse/sw360#656]
Example: name="gtk+2.0" or "dvd+rw"
Request: 
curl -sS -X GET  'http://'${host}':8080/resource/api/components?name=<name>' -H 'Content-Type: application/hal+json' -H 'Authorization: Bearer <access_token>'
Response:
{
  "_embedded" : {
    "sw360:components" : [ ]
  },
  "_links" : {
    "curies" : [ {
      "href" : "http://localhost:8080/resource/docs/{rel}.html",
      "name" : "sw360",
      "templated" : true
    } ]
  },
  "page" : {
    "size" : 10,
    "totalElements" : 0,
    "totalPages" : 0,
    "number" : 1
  }
}

**Comment by mcjaeger** [comment]
`%2B` ?

**Comment by hieupvtsdv** [comment]
Thank you for your support.
I replaced '+' with '%2B' and Getting was successfully.
I will close this ticket. Do you confirm that?
