### ISSUE TITLE
Liferay 7: Migrate from Regular roles to Site Roles

### ISSUE THREAD

**Issue by mcjaeger** [eclipse/sw360#658]
It seem slike we do not have consistently used site roles in the code and this becomes apparent now:

* Liferay has three role types: regular, organisation, site
* For `CLEARING_ADMIN`we would like to use the site role type
* Current code uses the regular type in most cases
* however, new liferay setup demands to have the roles like `CLEARING_ADMIN`as site role - also looks more consistent as well

What could be checked:
* CSV import / export in User Portlet (see Admin section): should work with site roles, currently sets regulart roles
* LoginHook: uses regular roles
* drop liferay role handling and maybe do this entirely with thrift API and a custom interface in Users Portlet

**Comment by fvl-phuong** [comment]
I got the message "Components is temporary unavailable" yesterday while testing ver 5.1.0. After create new organization and User Role/Role as suggested but I still got this issue. I think this bug related to the issue I am facing. Hoping that a new fix will be released soon. 
Thanks.
Phuong

**Comment by mcjaeger** [comment]
@fvl-phuong sorry for not answering earlier: the setup user cannot be used to work on the portal, please follow the import of users as pointed out here:

https://github.com/eclipse/sw360/wiki/Deploy-Liferay7

**Comment by mcjaeger** [comment]
I think right now, the sw360 roles are site roles now
