### ISSUE TITLE
Write admin action to fix component <-> release relations

### ISSUE THREAD

**Issue by lepokle** [eclipse/sw360#664]
Components and releases are linked in two ways:
1. components contain a list of release ids
1. each release contains a reference to its component

Especially on merging components, this relation can become inconsistent (e.g. due to errors during merge and the lack of transactions in couch db).

The new job shall search for such inconsistencies and fix them. Since merging might me the main cause of these errors, auto-fixing should change the reference inside the release sind this is the last operation during merge. Merge order is:
- change release list in components
- change reference inside releases

Therefore most likely the reference inside the relase is broken.

**Comment by mcjaeger** [comment]
the merging has been exercised quite some times recently, it seems to work...
