### ISSUE TITLE
REST : Wrong CLI used for license information generation

### ISSUE THREAD

**Issue by smrutis1** [eclipse/sw360#686]
If there is more than one CLI file for a release ... which one is used to generate the license information via RestAPI ?
A selection of the CLI files for the releases of a project  license information via the webUI works perfectly well ... exactly those CLI are taken to generate the license information which have been selected.
However when the license information gets generated via the RestAPI this is not the case.

**Comment by nutanv1contr** [comment]
Tested the PR. Below is my observation.
1. Open project>> goto atachment usage and select an attachment then generate license info from UI and rest end point. both are consistent. 
2. In license info generation page exclude few of the license and save the changes. license info generation from UI is generating license document without the excluded licenses. but from rest end point it is considering all the licenses from the selected attachment.
