### ISSUE TITLE
Slack invite link is no longer active.

### ISSUE THREAD

**Issue by albert-hejy** [eclipse/sw360#694]
I'm interested in this project and want to join the slack discussion, but the Slack invite link on the wiki page is no longer active.
https://github.com/eclipse/sw360/wiki

Could you help to check it?
Thanks.

**Comment by mcjaeger** [comment]
thanks for pointing out, yes will do.

**Comment by mcjaeger** [comment]
yes, it is no longer active

**Comment by LiXiaoming-FNST** [comment]
@mcjaeger  could you share a new link ? Thanks.

**Comment by mcjaeger** [comment]
@LiXiaoming-FNST could pls try this one?

https://join.slack.com/t/sw360chat/shared_invite/enQtNzg5NDQxMTQyNjA5LThiMjBlNTRmOWI0ZjJhYjc0OTk3ODM4MjBmOGRhMWRmN2QzOGVmMzQwYzAzN2JkMmVkZTI1ZjRhNmJlNTY4ZGI

**Comment by albert-hejy** [comment]
@mcjaeger It works, thanks.
