### ISSUE TITLE
Password reset requirement to SW360 stage

### ISSUE THREAD

**Issue by janszalay** [eclipse/sw360#739]
Hi,

My token to SW360 stage REST API has expired. I used following URL to generate new token https://stage.sw360.siemens.com/authorization/oauth/token?grant_type=password&client_id=[clientId]&client_secret=[clientSecret]   
After entering this URL it requires username and password. I don't remember my password.
Can you please reset my password to SW360 stage server?

Kind Regards,

Jan Szalay

**Comment by mcjaeger** [comment]
@janszalay please use code.siemens.com for operational issues ... please note that GitHub is public and the community is not the target for the expired access on our stage server at Siemens.
