### ISSUE TITLE
Link is not work on a wiki page. 

### ISSUE THREAD

**Issue by hakssung** [eclipse/sw360#764]
On a wiki page : https://github.com/eclipse/sw360/wiki/Deploy-Upgrade-to-Liferay-7.2, 
I clicked the below link: 

**Prerequisites**
You need a clone of the SW360 repository https://github.com/siemens/sw360/tree/lepokle/%23398/liferay-7-jar to follow this guide. ...

but, it displayed "Page not found - GitHub"

**Comment by mcjaeger** [comment]
OK, thanks, in general we in the process of updating our wiki. Regarding the liferay, it is also not optimal how they distribute it (how I think) because it is very hard to get a fixed link for this.

**Comment by mcjaeger** [comment]
wiki has been updated, also with install information: https://github.com/eclipse/sw360/wiki
