### ISSUE TITLE
REST puts can put wrong data

### ISSUE THREAD

**Issue by mcjaeger** [eclipse/sw360#771]
There Is insufficient data validation when records are created over the REST API. It did not appear in the Ui so far, because the user interface has implicitly avoided that.

Observation: if over the REST API wrong couch ids are set in reference fields (for example in project-release relation), then this reference is not validated. The data can be written to the DB, but retrieving the record will fail. Then the user is confused a lot.

There should be validation of couched ids fields are backend level so also calls from REST API will be failing once a reference is used which is not in the DB.

**Comment by gernot-h** [comment]
Thanks for creating this issue - in my case, adding wrong release links to a project via REST API did not only create confusion, but I ended up with defective projects in SW360 which I could neither fix via web UI nor via REST API, not even deletion was possible.
