### ISSUE TITLE
Component normalization question

### ISSUE THREAD

**Issue by vbasem** [eclipse/sw360#778]
While playing around with sw360, I came across the question how does sw360 normalize the data around components from different source. For example:

Component "log4j-core" in Sw360 has the id : 123
In Fossology it has the id 456
In security center its called "log4j core" and has it E451

How do you work with the described situation?

Thank you in advance!

**Comment by mcjaeger** [comment]
For fossology there is an internal mapping in the "External Tool Request" data structure. The main thing is that currently there is no UI to review external tool requests. The data structure is there and maintains multiple external tools requests per release.

In future we might have multiple tool requests for different analysis tools). For all other things, there is the external ids.

Note that you can setup default values of external ids in the sw360.properties file. You find this in the bundle or you can save your own sw360.properties file in `/etc/sw360`.  You could add external ids from fossology in the external ids as well if you wish to do so.

**Comment by vbasem** [comment]
Thank you for clarifying the question. With all the tools out there it seems to be really challenging to unify this information. I believe having rest of the tools map their Ids with Ids from clearly defined database might be a solution long term. But for now its still a manual process.
