### ISSUE TITLE
Export of projects / projects with releases broken

### ISSUE THREAD

**Issue by mcjaeger** [eclipse/sw360#795]
It seems like currently, the export of projects in the project list view, export spreadsheet is broken, regardless of the option, projects only or with releases, the resulting sprewadsheed document is empty. It has the header row though. but no other rows are found.

Attached an example, there should be five projects from different test users.

[projects-2020-02-28(4).xlsx](https://github.com/eclipse/sw360/files/4269289/projects-2020-02-28.4.xlsx)

**Comment by nam-np** [comment]
Hi, I am interesting this issue. And I checked, now it is normal work?

**Comment by mcjaeger** [comment]
uh, I am sorry, I think it is solved:

https://github.com/eclipse/sw360/pull/520

it is working on one of our test instances now as well. Sorry for the confusion
