### ISSUE TITLE
Could not create local repository at /home/dira271641/.m2/repository

### ISSUE THREAD

**Issue by dineshr93** [eclipse/sw360#804]
Hi 

I am trying to run sw360 via docker in Ubuntu 16.04 server by following 
[Deploy-Docker](https://github.com/eclipse/sw360/wiki/Deploy-Docker)
Since its server, the /home/dira271641/ folder cant be created/doesnt exist. 
How to resolve this?

```
dira@server:/usr/local/src/sw360$ mvn package -P deploy -Dbase.deploy.dir=/usr/local/src/sw360chores/_deploy -DskipTests
[ERROR] Could not create local repository at /home/dira271641/.m2/repository -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/LocalRepositoryNotAccessibleException
dira@server:/usr/local/src/sw360$
```

**Comment by mcjaeger** [comment]
Hello @dineshr93 , I think it is not clear from where you're executing it. IN case you re executing it right insider the container: will likely not work you need to do this outside the container.

**Comment by dineshr93** [comment]
I am executing this in Ubuntu server

**Comment by mcjaeger** [comment]
Hello @dineshr93, creating a maven repository is something you need to make sure in your environment. If your user cannot create a maven repo, it is maybe that maven has not been installed properly. Just some ways to check:

* can you run maven on other projects? for example? 
https://github.com/gabrielf/maven-samples
* Have tried to create a folder manually at the given location to see what the shell tells you for this point?

Maybe also the following stackoverflow conversation helps:

https://stackoverflow.com/questions/30847251/could-not-create-local-repository-at-var-root-m2-repository

**Comment by dineshr93** [comment]
I overcame this issue
