### ISSUE TITLE
Reordering of Attachment File Type values

### ISSUE THREAD

**Issue by akapti** [eclipse/sw360#805]
For any new component release added in SW360, the first attachment file type is usually the **source file** **(SRC)** as per the current workflow. Most of the users overlook the right selection of the File **Type** value corresponding to the attachment. This results in the following problem:

* The uploaded attachment (source files) will inherit the default value from the list. i.e. **Document (DOC)**

This mistake affects the entire workflow further. When user clicks the **Generate Source Code Bundle** for downloading the sources, the packages uploaded with the wrong file **type** value will not appear in the list.

This creates a lot of additional work for both the project and the clearing support team.

**Proposed Solution**

To solve the above issue, the easiest work around would be to make the value **source file (SRC)** as the default value for attachments.

The **preferred new order** for the file type values would be the following:

1. Source File - SRC
1. Clearing Report - CRT
1. Component License Information (CLI XML) - CLX
1. ......

Since these are the mostly used values in the **Type** field.

**Comment by mcjaeger** [comment]
(merged)
