### ISSUE TITLE
Enrich additional data feature on component and release page

### ISSUE THREAD

**Issue by AlbertHjy** [eclipse/sw360#809]
## Background
Our company is trying to migrate from other application to SW360 as FOSS components management system, but we found that there are some fields not supported in the current SW360 version. And current additional data is hard for us to force users to create the same key.
So I give the proposal to enrich the additional data group on the component and release page.
***
## Short Description
The idea is to create custom fields in Liferay(Control Panel->Configuration->Custom Fields) and then use Expando API to retrieve these fields in portlet and show these fields in the additional data group.
***
## Implementation details.
1. Create custom fields in Liferay(Control Panel->Configuration->Custom Fields) 
![image](https://user-images.githubusercontent.com/61676785/76506605-67e9eb00-6486-11ea-80cb-a8870c2c0a77.png)
![image](https://user-images.githubusercontent.com/61676785/76506508-3bce6a00-6486-11ea-85d6-db27f6b4b9d5.png)

- I prefer to create custom fields to User, which already used to store component/release/project filter
- select hidden if you want to hide an existing field
- name the field with the pattern: [Page Identifier]-[Filed ID]-[Field Name]
   e.g. component-100-Legal Acknowledgment,  release-200-Legal Acknowledgement
  - Page Identifier is used to identify where is the custom filed will be used, 
  - Filed ID will also be used to sort the fields in each page,
  - Field Name is used to be shown as the field label
- Starting value in text box type will be used as the validation pattern.
   e.g. If you input "\d{0,}" in Starting value, you can only input number in the field
- Supported Custom field types

- [x] Text-field, for single line
- [x] Text Area, for multi lines
- [x] Drop down, for single select, option(s) is/are required
- [x] Checkbox, only support one option
- [x] Date picker

2. Use Expando API to get the custom fields. Following is some example code.
```
// If created in User
com.liferay.portal.kernel.model.User liferayUser = UserUtils.findLiferayUser(request, user);
ExpandoBridge exp = liferayUser.getExpandoBridge();
Map<String, Serializable> attributes = exp.getAttributes();
attributes.forEach((key, value) -> {
    Serializable defaultValue = exp.getAttributeDefault(key);
    // Dropdown and Checkbox options
    System.out.println("Dropdown or Checkbox options:" + defaultValue);
    UnicodeProperties unicodeProperties = exp.getAttributeProperties(key);
    unicodeProperties.forEach((propertyKey, propertyValue) -> {
        System.out.println("propertyKey: " + propertyKey + ", propertyValue: " + propertyValue);
    });
    System.out.println("Attribute Key: "+ key + ", Attribute Value: " + value);
});

// If created in page/site
List<Layout> layouts = LayoutLocalServiceUtil.getLayouts(0, 1000);
for (Layout layout : layouts) {
    System.out.println(layout.getLayoutId());
    ExpandoBridge layoutExp = layout.getExpandoBridge();
    attributes = layoutExp.getAttributes();
    if (attributes == null) {
        continue;
    }
    attributes.forEach((key, value) -> {
        Serializable defaultValue = layoutExp.getAttributeDefault(key);
        // Dropdown and Checkbox options
        System.out.println("Dropdown or Checkbox options:" + defaultValue);
        UnicodeProperties unicodeProperties = layoutExp.getAttributeProperties(key);
        unicodeProperties.forEach((propertyKey, propertyValue) -> {
            System.out.println("propertyKey: " + propertyKey + ", propertyValue: " + propertyValue);
        });
        System.out.println("Attribute Key: "+ key + ", Attribute Value: " + value);
    });
}
```
And put the custom field's attributes into a new CustomFiled bean to pass to JSP.
CustomFiled snippet
```
public class CustomField {
    private String fieldKey;
    private String fieldLabel;
    private int fieldId;
    private CustomFieldType fieldType;
    private String fieldPattern;
    private String value;
    private List<String> options;
    private boolean isHidden;
}
```

3. JSP uses CustomFiled to render UI. (Additional Data feature will still be there)
The following is a sample UI.
![image](https://user-images.githubusercontent.com/61676785/76506541-4c7ee000-6486-11ea-9200-5e1e90cedc16.png)

4. When saving data, all the custom fields will also be saved to additional data.

**Comment by mcjaeger** [comment]
(from disciussion) @albert-hjy How about having a conversation / telco about the status and how we can go ahead with it?

**Comment by albert-hjy** [comment]
@mcjaeger  created [PR](https://github.com/eclipse/sw360/pull/829) for this issue.

**Comment by mcjaeger** [comment]
@albert-hjy we could close it, right?
