### ISSUE TITLE
How to properly destroy & run docker with the default existing settings?

### ISSUE THREAD

**Issue by dineshr93** [eclipse/sw360#815]
I have changed the username setting from email to userid in the portal. And probably just enabled the ldap authentication option field.

![image](https://user-images.githubusercontent.com/4498415/77041803-931d8e80-69e0-11ea-8b31-f21b5963d13a.png)

After logout, I was not able to login into setup account.

Tried `setup@sw360.org` with `sw360fossy` gives Authentication failure.
Tried just `setup `with `sw360fossy ` gives Auth. Failure.

So I planned to `sudo ./sw360chores.pl --cleanup`  //destroy 
&  `sudo ./sw360chores.pl --build -- up`   //build from scratch

Even building from scratch doesnt change to default email setting. Authentication fails.

How to revert to default setting so that I can login into it.

**Comment by dineshr93** [comment]
Hi @mcjaeger Are the configurations(for ldap & user details change from email address to userid) are saved outside the project source directory? If so can you let me know the location of it?

**Comment by mcjaeger** [comment]
@dineshr93 I think you were in the call once, can we close this issue?

**Comment by dineshr93** [comment]
Yes. I am planning to reinstall completely
