### ISSUE TITLE
Feat UI: Add new Role 'Clearing Team' in SW360

### ISSUE THREAD

**Issue by akapti** [eclipse/sw360#820]
With the new feature of `Clearing Request` being rolled out, it is required to have a new role created to monitor and process clearing requests created by users.
At present the editing of clearing request is not possible for multiple members, since only one email is used.
The new role added will enable the clearing team members to monitor the CR.

**Comment by mcjaeger** [comment]
as mentioned in the PR, `team` is just not optimal opposed to `admin`, `user` or `expert`

**Comment by mcjaeger** [comment]
solved here: https://github.com/eclipse/sw360/pull/821
