### ISSUE TITLE
Include docker deployment like in chores in the SW360 repo

### ISSUE THREAD

**Issue by blaumeiser-at-bosch** [eclipse/sw360#825]
Move the sw360 repo to a state that allows to clone it and run sw360 out of the box out of this repository. The idea is to move the stuff in chores in a reasonable way into the sw360 repo.

Reasoning:
- Having the deployment in an extra repo makes the deployment a second class citizen
- SW360 is easier to adopt with a one repo approach
- Information is contained in one wiki only, replacing the searching for information in multiple sources
- Having all in one repository allows to ease the building of the software, e.g., the complex copying of the build results so that the chores scripting finds them is not needed anymore if all paths are clear within the checked out repo.

**Comment by sschuberth** [comment]
For completeness, chores is currently hosted at https://github.com/sw360/sw360chores.

Another, orthogonal way to deploy SW360 not via Docker but a VM is https://github.com/sw360/sw360vagrant.

IMO, we should try to find out which of the two works best for the community to deploy SW360 and consider making that the "blessed" approach by moving its code to this core SW360 repository.

**Comment by blaumeiser-at-bosch** [comment]
Hello @sschuberth , that is, why there is the issue with pushung the chores stuff into the sw360 repo. We have already discussed that.

**Comment by sschuberth** [comment]
> We have already discussed that.

Where "we" here does not include *me*, which is why our team had a meeting on this (and related) topics with @mcjaeger today, which helped to clarify some misunderstandings on all sides.

**Comment by blaumeiser-at-bosch** [comment]
Hello @sschuberth , that is, why there is the issue with pushung the chores stuff into the sw360 repo. We have already discussed that with Michael and volunteered to do so. Idea was to not use chores directly, but a derivate from our deployment.

**Comment by neubs-bsi** [comment]
@mcjaeger how do we go forward on this?

**Comment by mcjaeger** [comment]
... eiei (sorry for late reply, from discussion:) 

* vagrant stays alone as well as chores
* simple docker file to be added to sw360 main project
* after "v2" version in  https://github.com/sw360/sw360chores/pull/81 is merged ask publicly for maintainers, willing to maintain the docker compose setup ...

**Comment by neubs-bsi** [comment]
@mcjaeger 
We will not be adding a simple dockerfile to the sw360 main project. 
Maybe you could investigate once more, if the one you mentioned having internally could be contributed.

**Comment by mcjaeger** [comment]
yes, we would like to do that

**Comment by mcjaeger** [comment]
it was provided here: https://github.com/eclipse/sw360/pull/1140
