### ISSUE TITLE
Error while merge of component, release, vendor

### ISSUE THREAD

**Issue by JaideepPalit** [eclipse/sw360#826]
While merging Component, Release or Vendor,
Error message pops out , indicating JS error.
Even though table load , Next button is disabled and Abort button is enabled.
Therefore not able to proceed to next step after selecting the Source Component.

![mergeCompUpload](https://user-images.githubusercontent.com/56534710/78870395-acf04580-7a63-11ea-8319-53a295d17087.png)

**Comment by mcjaeger** [comment]
was solved here: https://github.com/eclipse/sw360/pull/827
