### ISSUE TITLE
Error: In SW360, Fossology administration is temporarily unavailable

### ISSUE THREAD

**Issue by dineshr93** [eclipse/sw360#834]
Followed procedure: https://gist.github.com/roycyt/b6ddd241caf734732d1780d5de27a6ec

using latest stable release: sw360-8.1.0-M1

This ticket is in continuation with https://github.com/sw360/sw360chores/issues/75
Installed sw360 via docker chores project.

fossology connectivity page is showing 

![image](https://user-images.githubusercontent.com/4498415/79743855-f4f44f80-8322-11ea-9330-3a0f069e3f08.png)

**error** 

[Fossology_page_ErrorLog.txt](https://github.com/eclipse/sw360/files/4553259/Fossology_page_ErrorLog.txt)

**error highlights**

```
ERROR [http-nio-8080-exec-14][FossologyAdminPortlet:73] Error retrieving fossology config from backend.
org.apache.thrift.transport.TTransportException: HTTP Response code: 404


ERROR [http-nio-8080-exec-14][PortletRequestDispatcherImpl:303] Unable to dispatch request: java.lang.InstantiationException: bean fossologyConfig not found within scope
ERROR [http-nio-8080-exec-14][PortletServlet:119] javax.portlet.PortletException: javax.servlet.ServletException: java.lang.InstantiationException: bean fossologyConfig not found within scope
javax.portlet.PortletException: javax.servlet.ServletException: java.lang.InstantiationException: bean fossologyConfig not found within scope


Caused by: javax.servlet.ServletException: java.lang.InstantiationException: bean fossologyConfig not found within scope


Caused by: java.lang.InstantiationException: bean fossologyConfig not found within scope


ERROR [http-nio-8080-exec-14][render_portlet_jsp:131] null
java.lang.InstantiationException: bean fossologyConfig not found within scope
```

Also refer https://sw360chat.slack.com/archives/C68C2RYS3/p1586447237060000

**Comment by mcjaeger** [comment]
@dineshr93 did you try to re-install the lar file?

**Comment by dineshr93** [comment]
@mcjaeger  Now I have done. The problem still persists along with component page issue mentioned in  https://github.com/sw360/sw360chores/issues/75

**Comment by mcjaeger** [comment]
I think it is possible to install and run the fossology portlet. also there has been a number of updates since then.
