### ISSUE TITLE
Uninstall script for thrift that is installed via scripts/install-thrift.sh

### ISSUE THREAD

**Issue by dineshr93** [eclipse/sw360#840]
I am new to shell script If I want to uninstall thrift completely which I installed via [scripts/install-thrift.sh](https://github.com/eclipse/sw360/blob/master/scripts/install-thrift.sh) is  it fine just to replace the keyword install with remove in that script file ?
 how to uninstall thrift & its dependencies completely?

**Comment by mcjaeger** [comment]
The bast way woul dbe actually to install thrioft from packages, maybe it couldbe checked if that is an option with one platform ...

**Comment by mcjaeger** [comment]
has been provided by Oliver btw: https://github.com/eclipse/sw360/pull/939
