### ISSUE TITLE
Error connecting to backend in "Re-Check connection" of Admi/Fossology

### ISSUE THREAD

**Issue by frannicot** [eclipse/sw360#843]
Using latest stable release from https://github.com/eclipse/sw360/releases/tag/sw360-8.2.0-M1

Followed procedures: 
  https://github.com/eclipse/sw360/blob/master/README.md#required-software
  https://github.com/eclipse/sw360/blob/master/README.md#commands
  Installed sw360 without docker.

I got my API token from Fossology (https://github.com/fossology/fossology/wiki/Install-from-Source#7-start-the-fossology-scheduler-daemon):
![2020-04-30_11h11_56](https://user-images.githubusercontent.com/32058875/80959164-85905c80-8e06-11ea-9ab2-2dae34293916.png)

I got my id = 9 in the browser URL section to get my Fossology ID:
![2020-05-04_13h01_03](https://user-images.githubusercontent.com/32058875/80959679-9392ad00-8e07-11ea-9b35-e762d9e93be7.png)

I have registered my API token from Fossology and my id = 9 in SW360 / Admi / Fossology with success, but "checking the connection" fails. Here are the images of an id = 9:
![2020-05-04_13h04_02](https://user-images.githubusercontent.com/32058875/80959862-fb48f800-8e07-11ea-8a9d-77ca16eda8a1.png)

I did the same for another identifier (id = 7). Same problem.

Could you tell me if this is a SW360 bug?
Here is the sw360 log file with "Error connecting to backend" :
[catalina.txt](https://github.com/eclipse/sw360/files/4574312/catalina.txt)

Note 1 : from https://www.fossology.org/get-started/basic-rest-api-calls/
I also use the editor of the Swagger project at http://editor.swagger.io/ to get my API token from Fossology. It does not work
![2020-04-30_11h22_45](https://user-images.githubusercontent.com/32058875/80960535-59c2a600-8e09-11ea-9d56-4897606a0724.png)

Note 2 :
I got my id=9 in the browser URL section to get my Fossology ID because I tried to get, without success:
sudo curl -k -s -S -X GET http://"my vm ip address"/repo/api/v1/folders -H "my Fossology API token"
I replaced localhost with my vm IP address = 127.0.0.1
This command does not work because if I understood correctly, I did not deploy Fossology and sw360 on a different server of vm .
![2020-05-04_13h30_39](https://user-images.githubusercontent.com/32058875/80961669-b58e2e80-8e0b-11ea-8fc7-f252fad56c81.png)

**Comment by mcjaeger** [comment]
I think it is maybe because in the JWT token from FOSSology the server host name is encoded. Maybe 127.0.0.1 does not work therefore. Could you pls check with fossology 3.8 where this was changed?

**Comment by frannicot** [comment]
I saw with @GMishx who found my curl problem. This is not a bug.
See the resolution of the problem in https://github.com/fossology/fossology/issues/1710.
The access token is wrong because my apache configuration file is incorrect.
Now it works:
![2020-05-14_14h30_05](https://user-images.githubusercontent.com/32058875/82033567-31ef0000-969d-11ea-9fb1-8bd39246c431.png)

**Comment by frannicot** [comment]
This is not a bug. I close this issue.
