### ISSUE TITLE
Feature request: Wiki page for ldap configuration

### ISSUE THREAD

**Issue by dineshr93** [eclipse/sw360#855]
Hi team
Can we have the procedure for configuring ldap?

I tried by giving all the creds in "control panel-> Configuration -> instance setting -> ldap"
it simply doesn't work.

Also how to change default @sw360.org login requirement of username field to just username with LDAP?
Any help on this topic would be appreciated.
Thanks

**Comment by mcjaeger** [comment]
see your point, but in fact, to get LDAP running, it is entirely plain Liferay. There is an extension written by us to simplify group handling. but LDAP configuration should be entirely a Liferay portal task:

https://help.liferay.com/hc/en-us/articles/360017896112-LDAP
https://stackoverflow.com/questions/23469710/liferay-with-ldap

**Comment by mcjaeger** [comment]
LDAP we have used at Liferay 6.2 times, but the Liferay 7.X has not been tested anymore. The main issue with ldap is also that it is user name and password based, often considered insecure.
