### ISSUE TITLE
Can we Migrate datas(project, component & license) from localinstance to server instance 

### ISSUE THREAD

**Issue by dineshr93** [eclipse/sw360#856]
I have created a data in project tab, component tab & license tab in sw360.
I want my server instance to have the same data as that present in local instance
There are feature to export in xlsx. But import function only supports spdx/rdf format. License tab doesnt even have the import feature.

Is there way to migrate datas(project, component & license) from local instance to server instance?

**Comment by mcjaeger** [comment]
yes, you would need to:

* copy the couchdb databas files in `/var/lib/couchdb`.
* export users form the source instance and import users on the target instance uing the users page in the admin menue

But it would mean that you re replacing what is on the target machine in the couchdb files to replace, do not know if that is OK.

**Comment by dineshr93** [comment]
Thanks Michael
