### ISSUE TITLE
problem connecting to FOSSology with the folder id in SW360

### ISSUE THREAD

**Issue by frannicot** [eclipse/sw360#857]
Using the latest stable version of https://github.com/eclipse/sw360/releases/tag/sw360-8.2.0-M1

From the source, I installed and manually configured SW360 and FOSSology on the same virtual machine without docker or vagabond.
https://github.com/eclipse/sw360/blob/master/README.md#required-software
https://github.com/eclipse/sw360/blob/master/README.md#commands

Apache CouchDB 1.7.0 started on http://127.0.0.1:5984/
I have SW360 running on the tomcat server (port 8080 -> http://localhost:8080/en/web/guest/home) and FOSSology on apache (port 80 -> http://localhost/repo/).

I have a problem with folder id in SW360 / Admin / Fossology
I clicked on "save the configuration" and "recheck the connection" with 3 folder ids (1 or 7 or 9), it works.
These 3 folder ids are given by the curl command:
![2020-05-15_10h58_35](https://user-images.githubusercontent.com/32058875/82042963-14289780-96ab-11ea-8423-1717ad475afe.png)

I am surprised that another folder id = 20 or 5 or ... (like any folder id) also works, after clicking on "save the configuration" and "recheck the connection" !!
![2020-05-14_14h43_38](https://user-images.githubusercontent.com/32058875/82044310-6965a880-96ad-11ea-9776-7dce4fbd8bc1.png)

Is it normal ?

**Comment by mcjaeger** [comment]
@frannicot not it is not normal to point to a folder in sw360 which does not exist on fossology.

**Comment by mcjaeger** [comment]
I have setup the sw360 to fossology connection three times now at different occasions and did not see a malfunction from there with the folder ids. 

i think what is required anyways, is that the server or users can maintain multiple fossology connections (different folders, different servers, different tokens) to make it useful in future.

**Comment by KoukiHama** [comment]
> i think what is required anyways, is that the server or users can maintain multiple fossology connections (different folders, different servers, different tokens) to make it useful in future.

I think so too and I may be able to develop and contribute this function in near feture.
