### ISSUE TITLE
Issues related to Unified View of Clearing status.

### ISSUE THREAD

**Issue by JaideepPalit** [eclipse/sw360#858]
- Unified View of Cleating status takes lot of time to load in case of large DB.
- Also breaks and renders empty table if portlet url is different like `licences` ->`licences1`.
- `list View` and `Tree view` buttons are of uneven height.
- Console error in project details view for `createVulnerabilityTable`

![console_error](https://user-images.githubusercontent.com/56534710/82292438-8c070280-99c8-11ea-97f1-7b0749c467fd.JPG)

**Comment by mcjaeger** [comment]
already merged
