### ISSUE TITLE
Component creation failed in SW360

### ISSUE THREAD

**Issue by maanasiDivekar** [eclipse/sw360#862]
Hi Team,

I am working on the integration of ORT tool with SW360Antenna and SW360. 
SW360Antenna is working as a bridge between ORT and SW360. 
SW360 is deployed using Kubernetes and other tools (ORT and SW360Antenna are on Ubuntu server) 
To do so I am following the below steps:
1. Run the ORT to get the analyzer-result.yml file
2. pass the above file in SW360Antenna configuration file with other parameters such as a link to the SW360, username,password of the SW360 web portal, client-id and client-secret. 
3. Run the SW360Antenna jar file 

After doing so I am able to do the integration of all the system but it is throwing error while creating the components. as below,

**Error Logs on server:** 
2020-05-25T16:22:55,320 ERROR org.eclipse.sw360.antenna.sw360.rest.SW360ComponentClient Request to create component prelude-ls failed with 400 BAD_REQUEST
2020-05-25T16:22:55,337 ERROR org.eclipse.sw360.antenna.sw360.rest.SW360ReleaseClient Request to create release prelude-ls failed with 500 INTERNAL_SERVER_ERROR
2020-05-25T16:22:55,881 ERROR org.eclipse.sw360.antenna.sw360.rest.SW360ComponentClient Request to create component chalk failed with 400 BAD_REQUEST
2020-05-25T16:22:55,904 ERROR org.eclipse.sw360.antenna.sw360.rest.SW360ReleaseClient Request to create release chalk failed with 500 INTERNAL_SERVER_ERROR
2020-05-25T16:22:56,458 ERROR org.eclipse.sw360.antenna.sw360.rest.SW360ComponentClient Request to create component @istanbuljs/schema failed with 400 BAD_REQUEST
2020-05-25T16:22:56,476 ERROR org.eclipse.sw360.antenna.sw360.rest.SW360ReleaseClient Request to create release @istanbuljs/schema failed with 500 INTERNAL_SERVER_ERROR
2020-05-25T16:22:57,040 ERROR org.eclipse.sw360.antenna.sw360.rest.SW360ComponentClient Request to create component parse-json failed with 400 BAD_REQUEST
2020-05-25T16:22:57,059 ERROR org.eclipse.sw360.antenna.sw360.rest.SW360ReleaseClient Request to create release parse-json failed with 500 INTERNAL_SERVER_ERROR
2020-05-25T16:22:57,674 ERROR org.eclipse.sw360.antenna.sw360.rest.SW360ComponentClient Request to create component eslint-plugin-es failed with 400 BAD_REQUEST
2020-05-25T16:22:57,691 ERROR org.eclipse.sw360.antenna.sw360.rest.SW360ReleaseClient Request to create release eslint-plugin-es failed with 500 INTERNAL_SERVER_ERROR

**Error Log on Kubernetes**
ERROR VulnerabilityDatabaseHandler:243 - releaseIds cannot be null/empty

Is someone working on similar things or having similar issue then please guide me on the same. 

Thanks and Regards,
Manasi

**Comment by mcjaeger** [comment]
@maanasiDivekar good to hear that you work on this. I have not experienced that. But as with all reporting with all software:

* which versions have you used?
* what is your platform (e.g. OS)
* how did you install it (right from maven?)

Then, have you tried to just send some REST requests to the sw360. That you could do with CURL. or, very simple, you use one of the many rest client plug ins available for chrome or firefox. This allows you maybe to cross check that your sw360 instance is OK.

Other than that, I would be also interested for hearing about the experience with O.R.T. and antenna.

**Comment by maanasiDivekar** [comment]
Hi @mcjaeger ,
 Version are as below, 
1. SW360: 8.1.0
2. ORT: 1.21.1
3. SW360Antenna: SNAPSHOT 1.0.1
I am using Ubuntu for the toolchain. SW360 instance is deployed on a different server using Kubernetes. 

Yes, I have installed it right from maven n other necessary required Softwares. 

I have checked with the CURL request. I am able to create a component in SW360 using CRUL. So it seems SW360 is working fine. I am suspecting the issue in SW360ANtenna. Somehow it is not able to map the parameter "ID" from ORT analyzer result to SW360's "releaseID" parameter. may be because of the the component creation is failing. 

So far, with ORT I have pretty much good experience. I mean principally its working according to what it is intended to do. But though it has many issues as well so it involves some manual configuration changes and some I couldn't understand what it is. Still working o it.

**Comment by sschuberth** [comment]
> ORT: 1.21.1

I'd be curious where that version comes from, as we currently do not have any binary releases of ORT, and the most recent version is 0.1.0-SNAPSHOT 😉 

> I am suspecting the issue in SW360ANtenna.

Me too. @oheger-bosch can you maybe help to find out whether the problem is with the SW360 client library?

> So far, with ORT I have pretty much good experience.

I'm happy to hear that 😄 

> But though it has many issues as well

Please ensure to file any issues you encounter with ORT at https://github.com/oss-review-toolkit/ort/issues.

**Comment by maanasiDivekar** [comment]
Hi @sschuberth, I was checking in the file build.gradle.kts. M not not sure how to check version in kotlin. I found something like this in build.gradle.kts file. 

tasks.withType<KotlinCompile>().configureEach {
        kotlinOptions {
            allWarningsAsErrors = true
            jvmTarget = "1.8"
            apiVersion = "1.3"
        }

Can you guide me on where to check the version?

**Comment by sschuberth** [comment]
Basically, just run `ort --version`. But as mentioned, since we have no binary releases yet, all you get right now is a "coarse" version of 0.1.0-SNAPSHOT which tells you nothing about from which Git commit the version was built. But this is actually something you should know yourself since it was *you* who built ORT 😉

**Comment by maanasiDivekar** [comment]
Hi @sschuberth , Sorry, My bad! 
I followed the steps mentioned on the GitHub of ORT. (https://github.com/oss-review-toolkit/ort/blob/master/docs/getting-started.md). I did follow the instruction you provided to get the ort version. But it seems this is not the command for Ubuntu. Well m not sure on this I got this 
error: $ ort --version
-sh: 18: ort: not found
I thought the version or SNAPSHOT details would be in the build.gradle file similar to what we get in pom.xml for maven projects. 

My main focus is on the Scanning Results of ORT and checking to what extent it is suitable for the company's requirements. This also includes the integration part via SW360 using SW360Antenna

**Comment by oheger-bosch** [comment]
Hi, my theory regarding the SW360 client library is that the version in use is too old. There has been a change in SW360 recently which added a new mandatory property to components (the _categories_ property which was optional before). New versions of the client library set this property to a default value, but older versions do not. This would explain the 400 BAD REQUEST errors in the log when components are created.

**Comment by maanasiDivekar** [comment]
Hello @oheger-bosch  @sschuberth, The issue got resolved. I made few changes in configuration file of sw360chore and also I updated the version on sw360antenna(as suggested by one of the experts on the slack platform), Also I want to make a point here is, as my all the systems are deployed on the same server It was also giving me the SSL certificate issue, hence I changed the settings in sw360chores as a localhost URL and it worked properly.
