### ISSUE TITLE
Accepting the Moderation request, changes project visibility to "Group & Moderators"

### ISSUE THREAD

**Issue by akapti** [eclipse/sw360#871]
For a `Project` with visibility set to `Everyone`,
If an `Admin` Accepts the `Moderation Request` then project visibility get changed to `Group & Moderators`.
If `Clearing Admin` Accepts the `Moderation Request`, it creates one new `Moderation Request` with project visibility changes in it.

**Comment by mcjaeger** [comment]
right now it seems like the moderation request is only sent to creator and moderators of the project ...

**Comment by akapti** [comment]
I guess this issue has already been fixed as part of PR: https://github.com/eclipse/sw360/pull/910/ as mentioned here in comment: https://github.com/eclipse/sw360/pull/910#issuecomment-651317506
