### ISSUE TITLE
SW360 can't jump to the license information with suffix "+"

### ISSUE THREAD

**Issue by chanrai** [eclipse/sw360#872]
I found the following bug in SW360 (sw360-8.1.0-M1)(https://github.com/eclipse/sw360/commit/29404853c730d78b387ed9d12b516d4bcef23e85), which I think is related to the issue below

`https://github.com/eclipse/sw360/issues/555`
https://github.com/eclipse/sw360/issues/555

Like the attached screen capture, 

SW360 can't jump to the license information with suffix "+"(Exp: GPL-2.0+,...) at Component list.

And, SW360 can jump without problems by clicking the license name that in the "Summary" of the component.

Thank you! 

![comp_list](https://user-images.githubusercontent.com/35596645/83599607-9966e400-a5a7-11ea-8ab8-f2d977e01910.jpg)

![License_List](https://user-images.githubusercontent.com/35596645/83599621-9ec42e80-a5a7-11ea-845d-51fd07847e79.jpg)

![componet_summary](https://user-images.githubusercontent.com/35596645/83599627-a2f04c00-a5a7-11ea-828a-63006b9c7835.jpg)

![license_info](https://user-images.githubusercontent.com/35596645/83599912-5a855e00-a5a8-11ea-9967-0244f24c56c6.jpg)

**Comment by KoukiHama** [comment]
I tried Branch: master (ff870d0) , ang get same issue

![suffix_error](https://user-images.githubusercontent.com/39894802/83603466-73454200-a5af-11ea-9a10-e0e7271b4174.jpg)

**Comment by nam-np** [comment]
Hi, with verson 11.0.0:
- License not include "+", in my server need to change:

![image](https://user-images.githubusercontent.com/41797157/94769549-8260c300-03dc-11eb-8758-d7f209ba23b0.png)

![image](https://user-images.githubusercontent.com/41797157/94769480-580f0580-03dc-11eb-9a3c-40691a1e5941.png)

- License include "+", it same behavior:
> SW360 can jump without problems by clicking the license name that in the "Summary" of the component.

And now I found a solution.

**Comment by KoukiHama** [comment]
#635  is same with issue abovecomment

**Comment by KoukiHama** [comment]
Fixed by #1267
