### ISSUE TITLE
Projects getting overwritten in SW360 (integration with ORT and SW360Antenna)

### ISSUE THREAD

**Issue by maanasiDivekar** [eclipse/sw360#884]
Hello Team,
I am working on an integration between ORT, SW360Antenna, and SW360. The integration is successful, but the major issue I have come across is if I try to add a second project in SW360   it overwrites the earlier project. Can you please help me with it?

**Comment by mcjaeger** [comment]
please help and provide us with version of the sw360 and antenna ...

**Comment by maanasiDivekar** [comment]
Hello @mcjaeger , my apologies for not describing in detail. this issue was in antenna and got resolved by the team. I have updated the antenna version so far I am still working on it and testing it from different scenarios. For the reference below is the GitHub bug. 

https://github.com/eclipse/antenna/pull/542
https://github.com/eclipse/antenna/issues/541
