### ISSUE TITLE
User can assign himself to a project to get extended rights

### ISSUE THREAD

**Issue by AlexFTrapp** [eclipse/sw360#909]
Hi,

I just came accross a possible security-risk in sw360. A User can assing himself write access without approval of the project owner or moderators.
Steps to reproduce
- Use Account that has a normal "user"-Role
- Change a foreign Project that is open to the group of the user, but the user has no write-access to it
- create moderation request: **add user himself as a role that is not yet filled. e.g. lead architect**
- Save Moderation restest to get extended rights for this project although the moderation request is not yet approved
- From now on the user can edit the original document

I don't know whether this is a feature or a bug. But considering there is such a thing as "moderation requests", I don't think the above is a desired behaviour.

Greets Alex

**Comment by mcjaeger** [comment]
I think the PR was merged, so current master fixes this bug.

**Comment by AlexFTrapp** [comment]
Merged fix works fine for me and my scenario.
