### ISSUE TITLE
Error while loading some of the licenses

### ISSUE THREAD

**Issue by smrutis1** [eclipse/sw360#933]
An error is occurring while loading some of the individual licenses. And renaming product to project in some of the places to maintain consistency.

**Comment by mcjaeger** [comment]
@smrutis1 the issue is actually very shrt, maybe it could be checked what it actually means.

**Comment by smrutis1** [comment]
@mcjaeger just cross checked, looks like the issue has been fixed which was about renaming "product clearing report" to "project clearing report" and license loading issue.
