### ISSUE TITLE
How to populate License type feild in License section?

### ISSUE THREAD

**Issue by dineshr93** [eclipse/sw360#936]
Way to populate License type Feild

![image](https://user-images.githubusercontent.com/4498415/89183893-92634e80-d5b5-11ea-8bc2-c3edb33bde5e.png)

**Comment by KoukiHama** [comment]
@mcjaeger  
 What kind of options is  required for License type?
 Could you tell me the some example?

**Comment by mcjaeger** [comment]
We have an idea, but I am not sure, thoughts:

1. white licenses: standard obligations such as list text, list copyrights
2. yellow licenses: special obligations (eg. do not endorse your product based on ....)
3. red license: maybe risk for business case, to be checked.

but I am not sure about if other like it too ...

**Comment by dineshr93** [comment]
Also we can expand 3 more options of license types. 1. Permissive 2. Weak copy left 3. Strong copyleft

**Comment by KoukiHama** [comment]
@mcjaeger  Thank you for answer. I can image how to use "License type field"

> white licenses: standard obligations such as list text, list copyrights
yellow licenses: special obligations (eg. do not endorse your product based on ....)
red license: maybe risk for business case, to be checked.

I think that your taxonomy method is not bad but user should be able to customize License type field  by [sw360.properties](https://github.com/eclipse/sw360/blob/master/frontend/sw360-portlet/src/main/resources/sw360.properties) and default value ought to be blank.

**Comment by KoukiHama** [comment]
@mcjaeger 
After our internal discussion with my colleague, we plan to add "License type" section in admin Page.
These are the images for this.

 1. Admin Menu
![image](https://user-images.githubusercontent.com/39894802/116336869-3c55cb80-a814-11eb-86fb-a7cafa164b6d.png)

 2. License Type list
![image](https://user-images.githubusercontent.com/39894802/116336891-48418d80-a814-11eb-9112-f00b9e2b0332.png)

 3. Add License Type
![image](https://user-images.githubusercontent.com/39894802/116336923-5394b900-a814-11eb-88fc-14986e36cb9c.png)

 4. Delete License Type
![image](https://user-images.githubusercontent.com/39894802/116336953-5d1e2100-a814-11eb-89f8-84a6d81a26f4.png)

**Comment by KoukiHama** [comment]
And "License type" is defined in thrift like this. 
I could not understand purpose of these definition. 

https://github.com/eclipse/sw360/blob/4bf2932ba060384f5cd6975ef0e1fac78692dca8/libraries/lib-datahandler/src/main/thrift/licenses.thrift#L64-L70

**Comment by KoukiHama** [comment]
Solved by #1264
