### ISSUE TITLE
‘Show License Info' button doesn't work

### ISSUE THREAD

**Issue by drej** [eclipse/sw360#938]
I tried to build sw360 6.0 (upgrade to 8.2.0 lately) natively on a server with OS RHEL 7 following the steps shared by Mr. Hama (https://qiita.com/K-Hama/items/cd1c7f6e9e812bb8faf8#couchdb-lucene%E3%82%92%E3%82%BD%E3%83%BC%E3%82%B9%E3%81%8B%E3%82%89%E3%83%93%E3%83%AB%E3%83%89).

Everything just looks fine but 'Show License Info' button in components - name(version) - clearing details shows nothing.
I checked log in tomcat/logs, it said 'unable to access the spdx listed licenses at http://www.spdx.org/licenses. using local file copy of spdx listed licenses. org.apache.thrift.transport.ttransportexception: java.net.sockettimeoutexception: read timed out'.
Then I tried to curl http://www.spdx.org/licenses from my server but get a 'moved permanently'. It looks like spdx.org redirecting every access with a 'www' to a 404 page.

I cannot found string 'www.spdx.org/licenses' in source files so I can just remove the 'www' and rebuild.
Would you please tell me where did I make the mistake? How can I do to make this function work (change the url in somewhere or prepare a local file somehow)?

**Comment by KoukiHama** [comment]
@drej 
hello, thank you checking my blog. I try to find the reason of your problem. At first, could you tell me your commit id of sw360.

**Comment by drej** [comment]
@KoukiHama 
Thank you for responding. I am using the tag 'sw360-8.2.0-M1', the commit id is 0eaba4b226cead9795170abc4769d408d9735287.

**Comment by KoukiHama** [comment]
@drej 
Do you want to know this image's Show License Info?
![image](https://user-images.githubusercontent.com/39894802/89265457-78864200-d66f-11ea-8251-2e9116e1f574.png)

And, if it is yes, could do you tell me how to attache spdx files in  component/release?
If you want to get license info from this button, you need to prepare spdx files for this.
In my case, I made these spdx file made by fossology.

**Comment by drej** [comment]
@KoukiHama 
Yes, that is the button I'm trying to let it work.
I connected sw360 and fossology (3.7.0 running on docker) and upload a random oss source for test.
I received spdx file from fossology, set file status as 'accepted' and checked the 'component license information' in clearing details.
And I got 'no license information found in file' as above sometimes, sometimes just a 500 error.

**Comment by drej** [comment]
Finally I found it was a proxy setting issue.
