### ISSUE TITLE
Error when edit project has release

### ISSUE THREAD

**Issue by nam-np** [eclipse/sw360#957]
1. Create a project (add a release to project).
2. Edit project (change project name is same name with existed project).

_Note: Version: 8.2.0_

Page load:

![image](https://user-images.githubusercontent.com/41797157/90874333-c5854a80-e3c9-11ea-8144-710487c3847e.png)

**Comment by nam-np** [comment]
My expected same as behavior of scenario:
1. Create a project (not add a release to project).
2. Edit project (change project name is same name with existed project).

(After appear messase "A project with the same name and version already exists.", still keep edit page)

**Comment by mcjaeger** [comment]
unfortunately still there, going back: the data is lost.

<img width="1010" alt="Screenshot 2021-03-30 at 00 01 29" src="https://user-images.githubusercontent.com/3418977/112905694-20fb8180-90eb-11eb-8178-358ef60c599d.png">

**Comment by afsahsyeda** [comment]
I will be working on this issue.

**Comment by KoukiHama** [comment]
Great! I assigned you.
