### ISSUE TITLE
Adding obligation in licenses tab is  broken

### ISSUE THREAD

**Issue by KoukiHama** [eclipse/sw360#959]
[I also comment this issue in sw360 slack.](https://sw360chat.slack.com/archives/C015HNHB0H5/p1598019036000300?thread_ts=1597911306.001300&cid=C015HNHB0H5)

On  "liferay 7.3.3 and sw360 (e1a46bf)" installed by vagrant, 
I can not add obligation in licenses tab by all roles
Maybe, #599 is same issue.

![image (1)](https://user-images.githubusercontent.com/39894802/90991471-520b5500-e5e4-11ea-926d-0263e93e2a4f.png)

![image (2)](https://user-images.githubusercontent.com/39894802/90991470-50419180-e5e4-11ea-86f9-c9a664a0eb6b.png)

And Log.
[tomcat_log_update_license.txt](https://github.com/eclipse/sw360/files/5115177/tomcat_log_update_license.txt)

**Comment by mcjaeger** [comment]
I think it is really broken, thanks for reporting it.

**Comment by KoukiHama** [comment]
I checked this is solved.
